### ISSUE TITLE
[Bug]: wrong Hardware Generation and wrong Frimware for Solax X3-Hybrid G2

### ISSUE THREAD

**Issue by Alfred99-HA** [wills106/homeassistant-solax-modbus#1014]
### Describe the bug

Newly versions of "Solax Inverter Modbus" show in "Device Info" Model, Firmware and Hardware Generation.
However both informations are not displayed the real situation.

My System is as G2 system according to info from Solax and also according to layout of G2 versus G3 Inverter. It displays for Software: DSP1: 2.07 / DSP2 2.01 / ARM 2.03

However "Solax Inverter Modbus" indicates Gen3 with Firmware DSP v3.71 ARM v3.53

Maybe there is any connex to https://github.com/wills106/homeassistant-solax-modbus/issues/917

### Integration Version

2024.08.10

### Homeassistant core version

2024.8.2

### Inverter brand

Solax Powe

### Plugin used

plugin_solax.py

### Serial prefix

H3UE10

### Inverter firmware versions

DSP1: 2.07 / DSP2 2.01 / ARM 2.03

### Connection Method

TCP / Ethernet

### Dongle firmware

none

### Detailed Error Log

![image](https://github.com/user-attachments/assets/fa9be5b3-3460-4f9f-aaac-064f5e3e0422)
![image](https://github.com/user-attachments/assets/cbb922c7-f6b6-4fc3-8a97-9b2abe37b09e)

**Comment by wills106** [comment]
> Software: DSP1: 2.07 / DSP2 2.01 / ARM 2.03

I'm assuming you got those values from the LCD of the Inverter.
They are fixed at that regardless of what the actual firmware is.

The Gen3 is just a text field:
https://github.com/wills106/homeassistant-solax-modbus/blob/17e52d78bc852e97edcd875549a363ffa5609e8e/custom_components/solax_modbus/plugin_solax.py#L187-L188

https://github.com/wills106/homeassistant-solax-modbus/blob/17e52d78bc852e97edcd875549a363ffa5609e8e/custom_components/solax_modbus/plugin_solax.py#L5873-L5878

Your Inverter uses the Gen3 Hybrid registers and are taken from "Hybrid X1&X3-G3 ModbusTCP&RTU V3.29- English"
Although it doesn't help that SolaX have given the G3 X3's a number of different names in the cloud such as Gen1/Gen2 etc
They have complicated things even more by renaming the modbus doc to "Hybrid X1 G3&X3-G2 ModbusTCP&RTU V3.29- English" but the content is identical.
