### ISSUE TITLE
[Bug]: Entity name changes in 2024.08.14 break update buttons for Solis inverters

### ISSUE THREAD

**Issue by jshiell** [wills106/homeassistant-solax-modbus#1028]
### Describe the bug

Hi,

After upgrading to 2024.08.14 a bunch of entity names have changed, e.g. `timed_charge_start_h` became `timed_charge_start_hours`. However, this appears to have broken the update buttons (e.g. `solis_update_charge_discharge_times`). When clicking on these you now get an error referring to the old IDs, e.g. "Failed to perform the action button/press. 'timed_charge_start_h'". I presume something just got missed with the name changes - at first glance it appears the button functions (e.g. `value_function_timingmode`) still use the old IDs.

[This appears to be the commit that caused the changes.](https://github.com/wills106/homeassistant-solax-modbus/commit/0d98722496d519ec0f5e9d9cbdd6492c8a6fdbb5)

Thanks very much for all of your work!

### Integration Version

2024.08.14

### Homeassistant core version

2024.8.3

### Inverter brand

Solis

### Plugin used

plugin_solis.py

### Serial prefix

603101

### Connection Method

Waveshare

**Comment by jshiell** [comment]
Updating the IDs in the button functions appears to fix it.

**Comment by SzosszeNET** [comment]
Moreover it appears that change from hours/minutes to m/h been back and forth a couple times in the last couple updates...

**Comment by timstephenson20** [comment]
Simple enough fix for Solis from the looks of things - have updated the parameter names in the button functions and added a PR.

**Comment by wills106** [comment]
I have released [2024.09.1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.09.1) with this change.

**Comment by simondrake** [comment]
Thanks @wills106
