### ISSUE TITLE
[Bug]: POWER_VOLT_AMPERE_REACTIVE deprecated from HA Core 2025.9

### ISSUE THREAD

**Issue by PistolaPeteUK** [wills106/homeassistant-solax-modbus#1042]
### Describe the bug

Just as a heads up I upgraded to HA 2024.9 and got the following warning:

POWER_VOLT_AMPERE_REACTIVE was used from solax_modbus, this is a deprecated constant which will be removed in HA Core 2025.9. Use UnitOfReactivePower.VOLT_AMPERE_REACTIVE instead, please report it to the author of the 'solax_modbus' custom integration
 

### Integration Version

2024.08.14

### Homeassistant core version

2024.09

### Inverter brand

Solis

### Plugin used

plugin_solis.py

### Serial prefix

603104

### Connection Method

Waveshare TCP adaptor

### Detailed Error Log

Logger: homeassistant.const
Source: helpers/deprecation.py:197
First occurred: 10:36:48 (1 occurrences)
Last logged: 10:36:48

POWER_VOLT_AMPERE_REACTIVE was used from solax_modbus, this is a deprecated constant which will be removed in HA Core 2025.9. Use UnitOfReactivePower.VOLT_AMPERE_REACTIVE instead, please report it to the author of the 'solax_modbus' custom integration

**Comment by wills106** [comment]
I have released [2024.09.1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.09.1) with this change.

**Comment by wills106** [comment]
Closing as corrected.
