### ISSUE TITLE
Solis - S6-EH3P8K-H-EU -  entities for string 3 & 4 missing

### ISSUE THREAD

**Issue by kowi-k** [wills106/homeassistant-solax-modbus#1043]
### Describe the bug

Hi, 
the integration is working fine so far, but the entities for string/mppt 3+4 are missing.
Register for eg pv current 3 (33054) reads the correct data. 

![image](https://github.com/user-attachments/assets/dcf7df1c-90e5-42ab-8045-41d0a3801556)

### Integration Version

2024.8.14

### Homeassistant core version

2024.8.3

### Inverter brand

Solis

### Plugin used

plugin_solis.py

### Serial prefix

103305

### Connection Method

waveshare rs485

### Detailed Error Log

log is empty

**Comment by wills106** [comment]
I have released [2024.09.1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.09.1) with MPPT3 & MPPT4.

**Comment by kowi-k** [comment]
Thanks a lot! Works perfect!

**Comment by wills106** [comment]
Closing down as complete.
