### ISSUE TITLE
[Bug]: 'IGrowatt' - 'MOD 6KTL3-XH (BP)' On-grid Battery Discharge Stop SOC does not adjust

### ISSUE THREAD

**Issue by FISK-PUMA** [wills106/homeassistant-solax-modbus#1052]
### Describe the bug

When adjusting "EMS Discharging Stop SOC"  only " off-grid Battery Discharge Stop SOC" changes on my Growatt inverter/battery, "On-grid Battery Discharge Stop SOC" still the same.  (10%)
![Skærmbillede 2024-09-12 kl  18 52 34](https://github.com/user-attachments/assets/fd0d09e4-0e91-406e-a6dc-a0d4e43159dc)
![Skærmbillede 2024-09-12 kl  18 53 45](https://github.com/user-attachments/assets/5dfe198e-ba3d-4256-b11c-7ed4a71472e3)

### Integration Version

2024.09.01

### Homeassistant core version

2024.9.1

### Inverter brand

Growatt

### Plugin used

plugin_growatt.py

### Serial prefix

JCM0DB

### Connection Method

RS485-USB

**Comment by TonyMathiesen** [comment]
Which battery system are you having? 
I use the MOD 8KTL3-XH (BP) and APX HV battery system, and I only have the one discharging stop SOC in the user interface. 
What does your setup list under property?
![image](https://github.com/user-attachments/assets/741f7bc2-91bd-4384-ab19-1cadc93252dd)

**Comment by FISK-PUMA** [comment]
I also have a APX HV battery system. My BMS is a [https://parametre.online/0voz58nhg7659vhuerxj.png] Growatt APX 98020-P1

But firmware in the battery/BMS was updated by growatt last week maybe that is way?

See battery information i picture

BR.
Mads

[cid:f72fa267-c3d0-4676-b705-a2faae9e16a4]
[cid:99691f2f-d2c0-473e-8a2a-172dd16ceb2c]
________________________________
Fra: TonyMathiesen ***@***.***>
Sendt: 13. september 2024 10:51
Til: wills106/homeassistant-solax-modbus ***@***.***>
Cc: FISK-PUMA ***@***.***>; Author ***@***.***>
Emne: Re: [wills106/homeassistant-solax-modbus] [Bug]: 'IGrowatt' - 'MOD 6KTL3-XH (BP)' On-grid Battery Discharge Stop SOC does not adjust (Issue #1052)


Which battery system are you having?
I use the MOD 8KTL3-XH (BP) and APX HV battery system, and I only have the one discharging stop SOC in the user interface.
What does your setup list under property?

image.png (view on web)<https://github.com/user-attachments/assets/741f7bc2-91bd-4384-ab19-1cadc93252dd>

**Comment by TonyMathiesen** [comment]
Hi Mads. 
Can you try sending the picture again? I can only see a 1x1 pixel.
That could very well be due to a new firmware. I got mine installed a month ago. Will check about the firmware and see if I can get it added - as it makes really good sense to have the option to set an on-/offgrid SOC level.

**Comment by FISK-PUMA** [comment]
Hi Tony

I hope pictures are better now. 🙂

Br. Mads


________________________________
Fra: TonyMathiesen ***@***.***>
Sendt: 13. september 2024 18:36
Til: wills106/homeassistant-solax-modbus ***@***.***>
Cc: FISK-PUMA ***@***.***>; Author ***@***.***>
Emne: Re: [wills106/homeassistant-solax-modbus] [Bug]: 'IGrowatt' - 'MOD 6KTL3-XH (BP)' On-grid Battery Discharge Stop SOC does not adjust (Issue #1052)


Hi Mads.
Can you try sending the picture again? I can only see a 1x1 pixel.
That could very well be due to a new firmware. I got mine installed a month ago. Will check about the firmware and see if I can get it added - as it makes really good sense to have the option to set an on-/offgrid SOC level.

**Comment by TonyMathiesen** [comment]
Hi Mads. 
There is no picture attached, maybe it is because it is a reply via mail.
BR Tony.

**Comment by FISK-PUMA** [comment]
HI Tony 
I now  using github hope thats better .
![Skærmbillede 2024-09-14 kl  09 19 43](https://github.com/user-attachments/assets/2feb81c6-fb3a-4b63-92fe-9d78abd1e956)
![Skærmbillede 2024-09-14 kl  09 19 26](https://github.com/user-attachments/assets/f2e7abdb-4de8-4274-b8da-61828df7cd46)
BR. Mads

**Comment by TonyMathiesen** [comment]
Hi Mads. 
Now I can see the pictures 👍🏼 Thanks. 
I can see you are using different version. I will contact Growatt or my installer to get the firmware update, or do you have the files? I believe that I might have found the register that we need to add to the plugin to get both in the integration. 
BR Tony

**Comment by FISK-PUMA** [comment]
Hi Tony

No i dont have the files, Growatt did the update, remote.


That sounds good 🙂

BR. Mads

________________________________
Fra: TonyMathiesen ***@***.***>
Sendt: 14. september 2024 17:37
Til: wills106/homeassistant-solax-modbus ***@***.***>
Cc: FISK-PUMA ***@***.***>; Author ***@***.***>
Emne: Re: [wills106/homeassistant-solax-modbus] [Bug]: 'IGrowatt' - 'MOD 6KTL3-XH (BP)' On-grid Battery Discharge Stop SOC does not adjust (Issue #1052)


Hi Mads.
Now I can see the pictures 👍🏼 Thanks.
I can see you are using different version. I will contact Growatt or my installer to get the firmware update, or do you have the files? I believe that I might have found the register that we need to add to the plugin to get both in the integration.
BR Tony

**Comment by TonyMathiesen** [comment]
Hi Mads
Growatt did the firmware upgrade remotely yesterday. I have found the register and created a pull request #1056 to add the on-grid level. You can check the pull request if you want to test it. 

In the mail correspondence with Growatt the supporter mentioned:
> Keep in mind that these options are proportional to the Depth of Discharge (DoD) of your battery, set at 90%. Please do not change these values by more than 20%, as it could cause your batteries to over-discharge.

I asked a bit into it, and in general he would not recommend to adjust the stop SOC levels as it also impacts other parameters. One should be cautious to avoid stressing the battery cells, and one should monitor the parameters after every adjustment.

**Comment by wills106** [comment]
Do you know what version number of the Firmware is required?
Also do we expose it in HA?

**Comment by TonyMathiesen** [comment]
Hi @wills106 
Appears the firmware control version needs to be "ZBDB-0008", before I had "ZBDB-0006".
It is possible to read it out, however the last part seems to be handled differently than what is listed in the documentation. 
![image](https://github.com/user-attachments/assets/15859069-f959-495a-baf2-aa6beaf39d52)

If read out directly from the registers, two first is ascii and the last one is just the number. 
![image](https://github.com/user-attachments/assets/4affb87d-39fc-40cf-800f-8539ed05bc81)

From app: 
![image](https://github.com/user-attachments/assets/e9fafd20-5fdb-49fc-b769-1b58bcad5437)

**Comment by wills106** [comment]
Just released [2024.09.4](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.09.4) with the change.

**Comment by FISK-PUMA** [comment]
Hi Tony

Very nice that you found a solotion.  🙂

Info from Growatt dosent sound that good, right now I only want to adjust the levet by 20% between 30-10%.
 it is becuse i want to save some power on the battery, so that I can use that in the expensive morning hours. Maybe i should find another way to fix this. 😉

Thank you very much for your help🙂
BR.
Mads

________________________________
Fra: TonyMathiesen ***@***.***>
Sendt: 17. september 2024 17:08
Til: wills106/homeassistant-solax-modbus ***@***.***>
Cc: FISK-PUMA ***@***.***>; Author ***@***.***>
Emne: Re: [wills106/homeassistant-solax-modbus] [Bug]: 'IGrowatt' - 'MOD 6KTL3-XH (BP)' On-grid Battery Discharge Stop SOC does not adjust (Issue #1052)


Hi Mads
Growatt did the firmware upgrade remotely yesterday. I have found the register and created a pull request #1056<https://github.com/wills106/homeassistant-solax-modbus/pull/1056> to add the on-grid level. You can check the pull request if you want to test it.

In the mail correspondence with Growatt the supporter mentioned:

Keep in mind that these options are proportional to the Depth of Discharge (DoD) of your battery, set at 90%. Please do not change these values by more than 20%, as it could cause your batteries to over-discharge.

I asked a bit into it, and in general he would not recommend to adjust the stop SOC levels as it also impacts other parameters. One should be cautious to avoid stressing the battery cells, and one should monitor the parameters after every adjustment.
