### ISSUE TITLE
ESPHome Integration

### ISSUE THREAD

**Issue by BEMSman** [wills106/homeassistant-solax-modbus#1092]
### Description

Is there any possibility this could also be provided as an ESPHome integration?

### Suggested Solution

An ESPhome Integration to allow for easy integration with other ESPhome entities

**Comment by wills106** [comment]
I don't have the time to support another integration and no need to use ESPHome for this project, as my Inverter has built in ethernet.

**Comment by wills106** [comment]
Closing down as not something I can support.

**Comment by rosenrot00** [comment]
For those interested, I made my SolaX work with this https://github.com/rosenrot00/esphome_modbus_bridge. @wills106 maybe you could mention on your compatible adapters page that it’s in beta, so people with an ESPHome device lying around can try it out. I guess not much should be needed to verify it works for other inverters as well - if it wouldn't right now.
