### ISSUE TITLE
[Bug]: SolaX X3-MIC Gen 1 (MC502T*) does not show any data in Home Assistant 2024.10.3

### ISSUE THREAD

**Issue by michaelbeelman** [wills106/homeassistant-solax-modbus#1108]
### Describe the bug

SolaX X3-MIC Gen 1 (MC502T*) does not show any data in Home Assistant 2024.10.3.

Short description: The exception code 0x02 tells us that the register address you’re querying is out of range or doesn’t exist (anymore) for this inverter.

I seem to have an issue with my X3-MIC with this info (from Home Assistant):

X3-MIC
door SolaX Power
Firmware: DSP v1.None ARM v1.None
Hardware: Gen1
Serienummer: MC502TF4172046

Since the update from 2024.05 to 2024.10.3 I'm no longer receiving data through the RS485>USB connection. Any clues?

<img width="1014" alt="Scherm­afbeelding 2024-10-21 om 16 03 23" src="https://github.com/user-attachments/assets/519eb4e5-1689-4829-a250-39ed6ed64be4">

I'm receiving this raw data on the bus:

![image](https://github.com/user-attachments/assets/ce818d99-69f8-4e07-9237-44882b7b60bc)

This is what ChatGPT tells me about it, when provided the Modbus RTU manual for this specific inverter model:

![image](https://github.com/user-attachments/assets/400f9131-7a0d-4e07-a77f-30e86a3b8fae)

Modbus RTU Manual:
[Solax Power X3-MIC three phase inverter Modbus-RTU comms protocol(1).pdf](https://github.com/user-attachments/files/17490041/Solax.Power.X3-MIC.three.phase.inverter.Modbus-RTU.comms.protocol.1.pdf)

I hope this issue can be fixed quickly, hoping it's just a small update on the register addresses for this model?

### Integration Version

2024.10.4

### Homeassistant core version

2024.10.3

### Inverter brand

SolaX Power

### Plugin used

plugin_solax.py

### Serial prefix

MC502T

### Inverter firmware versions

Unknown

### Connection Method

RS485<>USB converter (FT232RL)

### Dongle firmware

No dongle.

### Detailed Error Log

2024-10-23 12:40:33.872 WARNING (MainThread) [custom_components.solax_modbus.plugin_solax] SolaX: reading serial number from address 0x0 failed; other address may succeed

### Additional context

The Modbus RTU protocol manual you’ve provided gives clear instructions on how to interpret data from your Solax X3-MIC inverter. Let’s decode the message you’re receiving:

You mentioned that you’re receiving the following bytes repeatedly: b'\x01\x83\x02\xc0\xf1'

	1.	Slave Address (1 byte):
	•	\x01: This is the slave address, typically representing the ID of the device on the Modbus network. Here, 01 means you’re communicating with device ID 1.
	2.	Function Code (1 byte):
	•	\x83: This is the function code. The manual describes function codes such as 0x03 for “Read Holding Registers” or 0x04 for “Read Input Registers.” However, when the high bit is set (as in 0x83), this indicates an error response. Specifically, 0x83 corresponds to an error in a “Read Holding Registers” (0x03) operation.
	3.	Exception Code (1 byte):
	•	\x02: This byte indicates the exception code. In Modbus, an exception code of 0x02 means “Illegal Data Address”, which suggests that the register address you are trying to read is not valid for the device.
	4.	CRC Checksum (2 bytes):
	•	\xC0\xF1: These two bytes are the CRC-16 (Cyclic Redundancy Check) used for error checking. They confirm the integrity of the data, but in this case, they’re part of the error response message.

What This Means:

The inverter is returning an error because the register you’re trying to access is not valid or available on the device. The exception code 0x02 tells us that the register address you’re querying is out of range or doesn’t exist for this inverter.

**Comment by michaelbeelman** [comment]
Using mbpoll same results:

![image](https://github.com/user-attachments/assets/dd65e54c-67ac-40ee-8b0e-0c54328463bc)

**Comment by michaelbeelman** [comment]
Hi, is it possible for someone to have a look at this please? I know it was a major leap from 2024.5 to 2024.10 and I’m not 100% sure it is the integration itself, but I can’t recall changing anything else at the time. I would sincerely appreciate an update on this issue.

**Comment by michaelbeelman** [comment]
I did some further digging with debug logging and found out that the inverter connects successfully connects at /dev/rs485solax:0, and it can read the serial number from 0x300. The main issue appears when reading holding registers in the 0x318 to 0x33f range (decimal 792 to 831), which includes information like RTC and firmware versions.

Trying the same holding registers via mbpoll results in Illegal Data Address.

<img width="909" alt="image" src="https://github.com/user-attachments/assets/03d9bca6-7981-42cc-95ee-8a2a0e9f79b0">

But if I would check the input register for the Working Mode it nicely returns 2: Working.

<img width="872" alt="image" src="https://github.com/user-attachments/assets/f6577a79-5978-4597-85b8-0e5291921ba9">

So, to me that means that the Inverter is active in 'Working mode' and the Modbus RTU protocol is functional over RS485 serial bus, as I can also read individual values as per the manual and following the registers in plugin_solax.py. I think all is good there, except... the holding registers 0x318 to 0x33f range (decimal 792 to 831), where both Home Assistant and mbpoll fail consistently with: Illegal data address. 

Can this be investigated and fixed, please?

**Comment by wills106** [comment]
If you change `MU802T` to `MC502T` in both locations does it start working again?

https://github.com/wills106/homeassistant-solax-modbus/blob/5ed71377690e7bf0f6b47f6b52d40066e678a94d/custom_components/solax_modbus/plugin_solax.py#L6100-L6113

**Comment by michaelbeelman** [comment]
Hi wills106,

Yes, that did the trick! Will you add it to the blacklist in the next release? I will keep it in here for now, as it's working fine.

Thanks for your reply, spot on from the start, your efforts are much appreciated.

Michael

**Comment by wills106** [comment]
It isn't in 2024.11.1 But I'll add it into a future release. 2024.11.1 doesn't offer anything new for the X3 MIC.

I am guessing your Inverter is either completely missing those registers, or your on an older Firmware version before they got added? As you can see 'MU802T' has the same issue.

**Comment by michaelbeelman** [comment]
I have never performed a firmware upgrade and it’s one of the earlier models. Either way, I don’t seem to miss any relevant information this way, so the blacklist option works fine for me. I will close the issue. Again, my sincere thank your for your support on this integration.

**Comment by michaelbeelman** [comment]
See above, it was solved by adding my inverter to the blacklist (X3 MIC first gen, MC502T*).
