### ISSUE TITLE
[Bug]: X1-RetroFit mis categorised as a Gen4 inverter

### ISSUE THREAD

**Issue by JBayangosB** [wills106/homeassistant-solax-modbus#1119]
### Describe the bug

Hi, 

According to Solax documentation my inverter is actually a Gen3

### Integration Version

2024.10.3

### Homeassistant core version

2024.10.3

### Inverter brand

Solax power

### Plugin used

plugin_solax.py

### Serial prefix

PRI502

### Inverter firmware versions

Firmware: DSP v1.42 ARM v1.35

### Connection Method

Ethernet

### Dongle firmware

n/a

**Comment by wills106** [comment]
Does your Inverter look like:
https://www.solaxpower.com/products/x1-ac/

Or:
https://www.solaxpower.com/products/x1-retro-fit/

**Comment by JBayangosB** [comment]
It looks more like this one: 

https://www.solaxpower.com/products/single-phase-hybrid/

Which also aligns with what I've observed with the app and when speaking to Evergen who were managing my battery.

![Screenshot_20241103-233637.png](https://github.com/user-attachments/assets/78ea1021-1c59-416c-9231-eb0a827758b5)

In hindsight this makes sense because I never had success using the force discharge options as they would always reset when I applied them which I believe are gen4 features.

Lemme know if I can provide more details 👌

**Comment by wills106** [comment]
Just noticed you mentioned your connecting over ethernet. Does the PRI have built in ethernet like the Hybrid Gen3 then? As the X1-AC didn't have built in ethernet, only RS485. So you would have to use something like a Waveshare or PocketWiFi when the PocketWiFi decides to work.

**Comment by wills106** [comment]
Strange how it identifies as a X1-Hybrid-G3 am I correct in thinking you have no PV connectors on this Inverter then?

**Comment by JBayangosB** [comment]
I had a look at it and it seems like it's possible for it to accept PV, but my system is tied to the AC. I do have a solar system but it is not directly connected to this inverter

**Comment by wills106** [comment]
Just released [2024.11.2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.11.2) with this change.
