### ISSUE TITLE
After install can't find Integration Configuration

### ISSUE THREAD

**Issue by Auke78** [wills106/homeassistant-solax-modbus#114]
After install the integration under HACS I can't find the integration in the HomeAssistant Integration screen. I can only go to the Integration page under HACS. But at this way I won't come into the Configuration Screen unfortunately.
How can I come to the Configuration?

Home Assistant 2022.9.4
Supervisor 2022.08.6
Operating System 8.5
Frontend-versie: 20220907.2

SolaX Inverter Modbus 0.6.1

**Comment by wills106** [comment]
Have you restarted Home Assistant following installing it through HACS?

When you have gone to "Settings" > "Devices & Services" have you tried to clear your browser Cache or at least performed "Ctrl + F5" to force a proper reload of the webpage?

**Comment by Puntoboy** [comment]
Yep, needs a ctrl+F5.

**Comment by wills106** [comment]
@Auke78 are you sorted now?

**Comment by Auke78** [comment]
Yes, I did the steps you discribed and it worked well. Thanks!

**Comment by wills106** [comment]
I'll close the issue down then.

**Comment by Auke78** [comment]
Thnx!

Op vr 16 sep. 2022 om 11:27 schreef wills106 ***@***.***>
