### ISSUE TITLE
Solis S5-EH1P4.6 Modbus error spams logfile

### ISSUE THREAD

**Issue by Wiki591** [wills106/homeassistant-solax-modbus#1171]
### Describe the bug

I get three times per second an error:

`WARNING (MainThread) [pymodbus.logging] Failed to connect [Errno 11] Could not exclusively lock port /dev/ttyUSB0: [Errno 11] Resource temporarily unavailable`

Having a look, who uses the TTL-RS485 stick:

```
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
python3 3208 root   18uW  CHR  188,0      0t0  434 /dev/ttyUSB0
```
Any ideas?

### Integration Version

2024.11.2

### Homeassistant core version

2024.11.2

### Inverter brand

Solis

### Plugin used

plugin_growatt.py

### Serial prefix

103103

### Connection Method

RS485-USB

**Comment by wills106** [comment]
Just for info you can also use `/dev/serial/by-id` instead of `/dev/ttyUSB0`
Then it doesn't matter if it swaps between USB0 & USB1 etc
https://homeassistant-solax-modbus.readthedocs.io/en/latest/modbus-adaptor-setup/#usb-to-rs485-adaptor
