### ISSUE TITLE
SolaX x1 bost 3,6kw g4

### ISSUE THREAD

**Issue by LxMoura** [wills106/homeassistant-solax-modbus#1177]
### Describe the bug

Com a última actualização deixou de apresentar dados - todos os sensores “desconhecido”
Qual a solução ???

### Integration Version

 2024.12.1

### Homeassistant core version

2024.12.5

### Inverter brand

SolaX power

### Plugin used

plugin_solax.py

### Serial prefix

XB4A36JC019009

### Inverter firmware versions

034-000

### Connection Method

Wi-Fi 

### Dongle firmware

Wi-Fi

**Comment by ertho22** [comment]
Same problem.
I‘m using the LAN/WLAN-Dongle.

**Comment by wills106** [comment]
Can you all try [2024.12.2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.12.2)

**Comment by ertho22** [comment]
> Can you all try [2024.12.2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.12.2)

Works perfect for me, thank you.

**Comment by wills106** [comment]
Closing down as resolved.
