### ISSUE TITLE
Problem with multiple instances

### ISSUE THREAD

**Issue by maxgrosse1** [wills106/homeassistant-solax-modbus#170]
The integration works perfectly fine. Though, when working with multiple (e.g. 2) instances of this integration, the problem occurs that all instances are not working any more, i.e. they seem to be stuck and do not deliver any data. The polling interval has been set to 2s and 5s respectively.

**Comment by wills106** [comment]
Can you please use the Issue Template.

**Comment by wills106** [comment]
Closing due to no response.
Please feel free to raise the Issue again, but follow the issue Template.
