### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by t0nyb** [wills106/homeassistant-solax-modbus#190]
**Describe the bug**
Defined by error report

**Mandatory details**
1. Integration version:beta 7.24
2. HA version: 22.11
3. First 4 digits of Serial: 6031
4. Connection Method: serial

**Detailed Error Log**

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/solax_modbus/plugin_solis.py:273 
Integration: SolaX Inverter Modbus (documentation, issues) 
First occurred: 11:25:37 (1 occurrences) 
Last logged: 11:25:37

Error setting up entry solax for solax_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/solax_modbus/__init__.py", line 92, in async_setup_entry
    plugin = importlib.import_module(f".plugin_{plugin_name}", 'custom_components.solax_modbus')
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/solax_modbus/plugin_solis.py", line 273, in <module>
    scale = value_function_rtc,
NameError: name 'value_function_rtc' is not defined

Detailed Error Log, if you press on the individual error further information is displayed.
This is the content we need, the description alone doesn't provide enough context.

If there are no log's showing for SolaX try the following depending on your language settings, you can find the full logs under:

Settings → System → Logs > at bottom of page press “LOAD FULL LOGS”

Now the full logs are loaded. If you scroll down, you will see them.
Once the full logs are shown, you can either use the search function in your browser to search for “solax” related entries or use the search entry field on top of the page.

Search for

solax

and report us the logs. Make sure to replace sensitive information by xxxx (if any)

**Additional context**
Sorry if this is the wrong place to report - I'm a user not a developer

**Comment by wills106** [comment]
0.7.0b25 Should fix this, noticed it while adding in the Solis RHI-3P10K-HVES-5G

**Comment by wills106** [comment]
Could you also try 0.7.0b27 to see if it detects your Inverter serial number I am not sure which version of the Modbus docs these Inverters are using.

When upgrading make sure you remove the Integration from the Integration page. Update & Restart HA and then add the Integration again on the Integration page.
HA holds the old version of code till you remove and re-add.

**Comment by t0nyb** [comment]
This error originated from a custom integration.

Logger: custom_components.solax_modbus.plugin_solis
Source: custom_components/solax_modbus/plugin_solis.py:112 
Integration: SolaX Inverter Modbus (documentation, issues) 
First occurred: 15:43:40 (1 occurrences) 
Last logged: 15:43:40

unrecognized asolis inverter type - serial number : 60312202232200

**Comment by t0nyb** [comment]
asolis because it doesn't like duplicate names and hopefully the entities will be top of the tree

**Comment by wills106** [comment]
Which beta is this? 0.7.0b27?

Is this with plugin_solis_old.py?

Also what model Inverter are you using and is it single or 3 Phase?

It's a different serial to the RHI-6K-48ES-5G which starts 603105. This being a 6kW mode 3105
603122 I am assuming is 6kW and whichever model 3122 refers to.

**Comment by t0nyb** [comment]
Hi

Thanks for your help
The log was from solis new

Single phase 3.6Kwh RHI-3.6K-48ES-5G

This lot from Solis old:

This error originated from a custom integration.

Logger: custom_components.solax_modbus.plugin_solis_old
Source: custom_components/solax_modbus/plugin_solis_old.py:107 
Integration: SolaX Inverter Modbus (documentation, issues) 
First occurred: 16:36:48 (1 occurrences) 
Last logged: 16:36:48

unrecognized solis_old inverter type - serial number : unknown

**Comment by wills106** [comment]
Ok, I'll update with your serial. I was expecting it to be a 6kW Inverter not, 3.6kW. But I don't understand how the serial numbers are structured yet.

**Comment by wills106** [comment]
I have just release 0.7.0b28 with your Serial number in solis_old

I will eventually swap the naming between solis and solis_old. As your Inverter is the newer style. (I will let you know when the names are swapped)

**Comment by wills106** [comment]
If you serial was read correct in plugin_solis.py I have just released 0.7.0b29 with your Serial in plugin_solis.py

**Comment by t0nyb** [comment]
From version 29

Using soils:

This error originated from a custom integration.

Logger: custom_components.solax_modbus.plugin_solis
Source: custom_components/solax_modbus/plugin_solis.py:112 
Integration: SolaX Inverter Modbus (documentation, issues) 
First occurred: 17:22:24 (1 occurrences) 
Last logged: 17:22:24

unrecognized aaasolis inverter type - serial number : 60312202232200

**Comment by t0nyb** [comment]
Version 29

This error originated from a custom integration.

Logger: custom_components.solax_modbus
Source: custom_components/solax_modbus/plugin_solis.py:166 
Integration: SolaX Inverter Modbus (documentation, issues) 
First occurred: 18:53:30 (1 occurrences) 
Last logged: 18:53:30

Something went wrong reading from modbus
Traceback (most recent call last):
  File "/config/custom_components/solax_modbus/__init__.py", line 292, in read_modbus_data
    res = self.read_modbus_registers_all()
  File "/config/custom_components/solax_modbus/__init__.py", line 362, in read_modbus_registers_all
    res = res and self.read_modbus_block(block, 'input')
  File "/config/custom_components/solax_modbus/__init__.py", line 351, in read_modbus_block
    self.treat_address(decoder, descr)
  File "/config/custom_components/solax_modbus/__init__.py", line 322, in treat_address
    self.data[descr.key] = descr.scale(val, descr, self.data)
  File "/config/custom_components/solax_modbus/plugin_solis.py", line 166, in value_function_rtc
    return datetime.strptime(val, '%d/%m/%y %H:%M:%S')
  File "/usr/local/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '53/31/00 18:07:11' does not match format '%d/%m/%y %H:%M:%S'

**Comment by wills106** [comment]
Do any of the sensors show readings? Or does RTC block it all? I didn't really look into the RTC bit much.

**Comment by wills106** [comment]
0.7.0b30 removes RTC. I can revisit that another day. Do you get any working sensors?

**Comment by t0nyb** [comment]
no none. 

will load 30 and report back

**Comment by t0nyb** [comment]
Excellent!!

Most sensors working, grid import and export not.

Logs:

This error originated from a custom integration.

Logger: custom_components.solax_modbus
Source: custom_components/solax_modbus/__init__.py:277 
Integration: SolaX Inverter Modbus (documentation, issues) 
First occurred: 19:28:59 (4 occurrences) 
Last logged: 19:34:05

'H' format requires 0 <= number <= 65535: also cannot read input registers at device 1 position 0x50990
Traceback (most recent call last):
  File "/config/custom_components/solax_modbus/__init__.py", line 331, in read_modbus_block
    if typ == 'input': realtime_data = self.read_input_registers(unit=self._modbus_addr, address=block.start, count=block.end - block.start)
  File "/config/custom_components/solax_modbus/__init__.py", line 277, in read_input_registers
    return self._client.read_input_registers(address, count, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymodbus/client/common.py", line 125, in read_input_registers
    return self.execute(request)
  File "/usr/local/lib/python3.10/site-packages/pymodbus/client/sync.py", line 109, in execute
    return self.transaction.execute(request)
  File "/usr/local/lib/python3.10/site-packages/pymodbus/transaction.py", line 174, in execute
    response, last_exception = self._transact(
  File "/usr/local/lib/python3.10/site-packages/pymodbus/transaction.py", line 271, in _transact
    packet = self.client.framer.buildPacket(packet)
  File "/usr/local/lib/python3.10/site-packages/pymodbus/framer/rtu_framer.py", line 248, in buildPacket
    data = message.encode()
  File "/usr/local/lib/python3.10/site-packages/pymodbus/register_read_message.py", line 33, in encode
    return struct.pack('>HH', self.address, self.count)
struct.error: 'H' format requires 0 <= number <= 65535

Logger: homeassistant.util.async_
Source: util/async_.py:180 
First occurred: 19:28:59 (4 occurrences) 
Last logged: 19:34:05

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for solax_modbus doing blocking calls at custom_components/solax_modbus/__init__.py, line 277: return self._client.read_input_registers(address, count, **kwargs)

**Comment by wills106** [comment]
Could you give a screenshot of all the sensors?

**Comment by infradom** [comment]
0x50990 hex is 330128 decimal
I believe meter_voltage declaration is wrong

**Comment by wills106** [comment]
I'll go back over these registers in the next day or so. These Solis docs are an utter mess.

There are docs with newer dates in them that are for older Inverters I believe.

**Comment by t0nyb** [comment]
![Screen Shot 2022-11-07 at 20 37 21](https://user-images.githubusercontent.com/33989067/200410444-6eb0038a-d469-4e42-bc7c-c04a1d39f28f.png)

**Comment by t0nyb** [comment]
![Screen Shot 2022-11-07 at 20 34 33](https://user-images.githubusercontent.com/33989067/200410921-00fa3e1c-566c-4845-a3ba-cceb5b05409e.png)

**Comment by t0nyb** [comment]
![Screen Shot 2022-11-07 at 20 34 22](https://user-images.githubusercontent.com/33989067/200410982-5f36fc37-ebca-45f5-b41b-c02df29598c2.png)

**Comment by t0nyb** [comment]
![Screen Shot 2022-11-07 at 20 34 13](https://user-images.githubusercontent.com/33989067/200411065-9f4ac998-ecfd-419e-9a48-3942b623dd62.png)

**Comment by wills106** [comment]
That's my SolaX Gen3, do might be different sensors and different order.

**Comment by t0nyb** [comment]
**Do you have any sensors reporting values though?**
Yes most of them

**Comment by wills106** [comment]
That's what I want to see. Then I know which are reporting and which need further work. I can also see if any need the scaling or rounding altering.

**Comment by t0nyb** [comment]
OK I misunderstood

Can you think of an efficient way to do that short of screen shotting every one?

In my myenergi integration for instance I can add all the entities to a dashboard. No option to do that here

**Comment by t0nyb** [comment]
My bad as usual Wait 5

**Comment by wills106** [comment]
Don't you see this?

![image](https://user-images.githubusercontent.com/18155231/200412973-d6b0d6ff-128e-4138-8dcc-3f04ab4c7a83.png)

Or

![image](https://user-images.githubusercontent.com/18155231/200413129-230fabf3-8204-4d65-96c3-7d2638eae926.png)

**Comment by wills106** [comment]
I don't need all of them. But when you are in the Integrations page, if you find any with funny values screenshot around them.

**Comment by t0nyb** [comment]
![Uploading Screen Shot 2022-11-07 at 20.53.28.png…]()

**Comment by wills106** [comment]
I think GitHub is playing up, looks like that Image started to load and gave up?

**Comment by t0nyb** [comment]
Yes I saw that eventually sorry.

will go through them all tomorrow and highlight what I see as anomalous

**Comment by wills106** [comment]
Ok, no rush.

I am very pleased with the progress we have made so far!
I doesn't help when there are 3 or even 4 versions of the documents floating about on the Internet and none of the time stamps make sense.

Thanks for the patience with testing this.

**Comment by infradom** [comment]
> I'll go back over these registers in the next day or so. These Solis docs are an utter mess.
> 
> There are docs with newer dates in them that are for older Inverters I believe.

I believe it is just a typo in the meter_voltage address

**Comment by wills106** [comment]
Updated 0.7.0b31

**Comment by wills106** [comment]
Just released 0.7.0b32 with more sensors and hopefully working Number entities.

**Comment by t0nyb** [comment]
![UNADJUSTEDNONRAW_thumb_50f0](https://user-images.githubusercontent.com/33989067/200510121-6583e455-f556-450c-b921-e192c50e7566.jpg)
![UNADJUSTEDNONRAW_thumb_50ee](https://user-images.githubusercontent.com/33989067/200510192-a3c04401-5374-4752-9d67-e96e30669d2a.jpg)
![UNADJUSTEDNONRAW_thumb_50ed](https://user-images.githubusercontent.com/33989067/200510249-bbd4ec1f-a341-4c63-ba9f-071ae823f165.jpg)
![UNADJUSTEDNONRAW_thumb_50ec](https://user-images.githubusercontent.com/33989067/200510340-511a8dd6-48cf-4253-97c3-d0e6b8b7f183.jpg)

**Comment by wills106** [comment]
Is that on 0.7.0b30?

**Comment by t0nyb** [comment]
yes haven't installed 31 yet will do soon

**Comment by wills106** [comment]
You might as well go to 32

**Comment by t0nyb** [comment]
V32 Log:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/solax_modbus/plugin_solis.py:182 
Integration: SolaX Inverter Modbus (documentation, issues) 
First occurred: 09:26:40 (1 occurrences) 
Last logged: 09:26:40

Error setting up entry Inverter for solax_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/solax_modbus/__init__.py", line 92, in async_setup_entry
    plugin = importlib.import_module(f".plugin_{plugin_name}", 'custom_components.solax_modbus')
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/solax_modbus/plugin_solis.py", line 182, in <module>
    SolisModbusSensorEntityDescription(
TypeError: SolisModbusSensorEntityDescription.__init__() got an unexpected keyword argument 'fmt'

**Comment by wills106** [comment]
I'll correct it. Will push a new release out in a few minutes.

**Comment by wills106** [comment]
Just released 0.7.0b33

**Comment by t0nyb** [comment]
V33 log

And no problem I'm happy to keep testing

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/solax_modbus/plugin_solis.py:672 
Integration: SolaX Inverter Modbus (documentation, issues) 
First occurred: 10:30:53 (1 occurrences) 
Last logged: 10:30:53

Error setting up entry inverter for solax_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/solax_modbus/__init__.py", line 92, in async_setup_entry
    plugin = importlib.import_module(f".plugin_{plugin_name}", 'custom_components.solax_modbus')
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/solax_modbus/plugin_solis.py", line 672, in <module>
    native_unit_of_measurement = POWER_VOLT_AMPERE_REACTIVE,
NameError: name 'POWER_VOLT_AMPERE_REACTIVE' is not defined

**Comment by wills106** [comment]
Opps, forgot to update const.py as it's the first time I have used POWER_VOLT_AMPERE_REACTIVE

**Comment by wills106** [comment]
0.7.0b34 corrects this.

**Comment by t0nyb** [comment]
34 Log:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:520 
Integration: Sensor (documentation, issues) 
First occurred: 12:03:57 (2 occurrences) 
Last logged: 12:04:27

Platform solax_modbus does not generate unique IDs. ID solvent_meter_activepower already exists - ignoring sensor.solvent_meter_activepower

Logger: homeassistant.util.async_
Source: util/async_.py:180 
First occurred: 12:04:12 (8 occurrences) 
Last logged: 12:04:43

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for solax_modbus doing blocking calls at custom_components/solax_modbus/__init__.py, line 277: return self._client.read_input_registers(address, count, **kwargs)

**Comment by t0nyb** [comment]
but sensors working wait for photos

**Comment by t0nyb** [comment]
No problem

Waiting for my Apple photos to update from my ancient phone

**Comment by t0nyb** [comment]
![UNADJUSTEDNONRAW_thumb_50f7](https://user-images.githubusercontent.com/33989067/200574816-87c7624d-e45a-4555-b795-e54fe7d2f7e8.jpg)
![UNADJUSTEDNONRAW_thumb_50f8](https://user-images.githubusercontent.com/33989067/200574863-54f3b27a-1889-45e7-b489-d67c801d2aa4.jpg)
![UNADJUSTEDNONRAW_thumb_50f3](https://user-images.githubusercontent.com/33989067/200574918-5a275ff9-d8a2-447b-abdd-faae55661ec5.jpg)
![UNADJUSTEDNONRAW_thumb_50f6](https://user-images.githubusercontent.com/33989067/200575024-ada6eb76-4cb3-437f-84b8-6a5c89a8b666.jpg)
![UNADJUSTEDNONRAW_thumb_50f4](https://user-images.githubusercontent.com/33989067/200575077-9af55535-0124-41af-9825-2f0892fe600a.jpg)

**Comment by t0nyb** [comment]
![UNADJUSTEDNONRAW_thumb_50f9](https://user-images.githubusercontent.com/33989067/200576293-5f488016-93df-40a8-bd20-d7b9729232e6.jpg)

**Comment by wills106** [comment]
I think the ActivePower, House Load Today / Yesterday, Meter Current seem very high? Or do you have electric heating or/and an EV?
The rest seem to be ok. Can you verify any of them from your Inverter LCD?

**Comment by t0nyb** [comment]
I will look. No EV or electric bar immersion heater sometimes

**Comment by wills106** [comment]
I think I need to add scaling to your Meter Current and Meter Voltage. Your Voltage is 2451v I think it should be 245.1v

**Comment by wills106** [comment]
I don't know much about ApparentPower, ActivePower, ReactivePower etc so not sure what they should even look like?

**Comment by t0nyb** [comment]
Morning

Suggest that house load today, house load total, house load yesterday should be /10.

I have no idea what "meter" and its associated figures mean but they look suspect.

Thanks for your continuing efforts.

My son has the 5KWh version of the same inverter as me. I will forward his serial number when he is home today.

**Comment by wills106** [comment]
Just released 0.7.0b36 with the mentioned changes.

**Comment by wills106** [comment]
Did you try this on your Sons Inverter?

**Comment by t0nyb** [comment]
No but will do hopefully over the weekend. Will report.

**Comment by t0nyb** [comment]
V40 log:

This error originated from a custom integration.

Logger: custom_components.solax_modbus.plugin_solis
Source: custom_components/solax_modbus/plugin_solis.py:97 
Integration: SolaX Inverter Modbus (documentation, issues) 
First occurred: 09:22:26 (1 occurrences) 
Last logged: 09:22:26

unrecognized solvent inverter type - serial number : 60312202232200

**Comment by t0nyb** [comment]
V39 log:

This error originated from a custom integration.

Logger: custom_components.solax_modbus.plugin_solis
Source: custom_components/solax_modbus/plugin_solis.py:97 
Integration: SolaX Inverter Modbus (documentation, issues) 
First occurred: 09:30:19 (1 occurrences) 
Last logged: 09:30:19

unrecognized Solvent1 inverter type - serial number : 60312202232200

**Comment by wills106** [comment]
I have a typo in the Serial Number check. I have a double if statement that breaks it.

I'll release 0.7.0b41 shortly.

**Comment by t0nyb** [comment]
V41 good. Will test with son's inverter. His serial 4 digit prefix is same as mine.

**Comment by t0nyb** [comment]
Serial 6031052226150002

Solis hybrid 6k

working

**Comment by wills106** [comment]
I am getting ready to release these 0.7.0bx as a proper release soon. So this functionality won't be added till after then.
But it is on the Todo list as I also want to read individual Bits on the SolaX as well, as that's where some of the error codes are stored. So it will be a universal improvement.

**Comment by t0nyb** [comment]
Confirm beta 41 working with Waveshare modbus to ethernet adapter

**Comment by t0nyb** [comment]
Beta 46 multiple log errors about inverter type

only 4 entities - none of the 92 entities originally available

**Comment by wills106** [comment]
Can you please share logs so I know what it's failed on otherwise I can't fault find.

**Comment by t0nyb** [comment]
Error unloading entry Solvent5 for solax_modbus
Error evaluating condition in 'export': In 'condition': In 'numeric_state': In 'numeric_state' condition: unknown entity sensor.solvent_battery_soc
Solvent5 error reading input registers at device 1 position 0x8
unrecognized inverter type - serial number : unknown
Solvent5: cannot find serial number, even not for MIC
Solvent5: reading serial number from address 0x300 failed; other address may succeed
Solvent5: reading serial number from address 0x0 failed; other address may succeed

**Comment by t0nyb** [comment]
do you need the complete logs?

**Comment by wills106** [comment]
It looks like you have tried to setup the Integration using the plugin_solax.py instead of the Solis one?

I have made a few small corrections in 0.7.0b47 so you might as well go to that version.
Before updating remove the Integration from the Integration page, upgrade, restart HA and add the Integration again. If you name it the same any dashboards will carry on functioning as normal.

**Comment by t0nyb** [comment]
b49 OK. Sorry I may have been distracted loading 46.
