### ISSUE TITLE
0.7.0b20 SolaX Total Yield

### ISSUE THREAD

**Issue by CristiXP** [wills106/homeassistant-solax-modbus#199]
Since 0.7.0b20 SolaX Total Yield the value is showing 22338800 instead of 22338.8 for ex.
Not fixed in last version.

![image](https://user-images.githubusercontent.com/93781522/201183115-50c1fd86-f357-4b07-943e-3807daa3afd5.png)

**Comment by wills106** [comment]
When you upgraded to 0.7.0b20 did you remove the Integration from the Integration page and add it again after a restart?

We are now on 0.7.0b39 so we have had many code changed since then.

**Comment by CristiXP** [comment]
Installed each of one after. Eachone  brakes the entity and shows x1000, but the 20. I am restoring from backup everytime :)

**Comment by wills106** [comment]
Could you please add all the missing information from the Issue template that has been deleted.
[Link to issue template](https://github.com/wills106/homeassistant-solax-modbus/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by CristiXP** [comment]
---
name: Bug report
about: Create a report to help us improve
title: "[BUG]"
labels: ''
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**Mandatory details**
1. Integration Version:0.7.0b39 
2. HA Version:Home Assistant 2022.11.2
3. Inverter Brand:Solax
4. Plugin Used:SolaX Inverter Modbus
5. First 6 digits of Serial:MP153T
6. Connection Method:modbus

**Detailed Error Log**
Detailed Error Log, if you press on the individual error further information is displayed.
This is the content we need, the description alone doesn't provide enough context.

If there are no log's showing for SolaX try the following depending on your language settings, you can find the full logs under:

Settings → System → Logs > at bottom of page press “LOAD FULL LOGS”

Now the full logs are loaded. If you scroll down, you will see them.
Once the full logs are shown, you can either use the search function in your browser to search for “solax” related entries or use the search entry field on top of the page.

Search for

solax

and report us the logs. Make sure to replace sensitive information by xxxx (if any)

**Additional context**
Add any other context about the problem here.

**Comment by CristiXP** [comment]
This is what is shows on .39 for that entity.

![image](https://user-images.githubusercontent.com/93781522/201288855-28326519-d853-463b-8cb0-f75b6d23c67c.png)

**Comment by wills106** [comment]
The X3 MIC / MIC Pro Gen1 has "Total Yield" as 0.001 scaling
The X3 MIC / MIC Pro Gen2 has "Total Yield" as 0.1 scaling.

I need to try and find a way to detect if the Inverter is Gen1 or Gen2 and adapt the scaling to suit.

**Comment by wills106** [comment]
I think I have spotted the difference in Serial Numbers between the Gen1 and Gen2.
Could you give 0.7.0b40 a try please.

**Comment by CristiXP** [comment]
Confirming that the issue has been fixed. Thank you.

**Comment by wills106** [comment]
I'll close the issue down then thanks.
