### ISSUE TITLE
[BUG] Unrecognized Solis inverter type RHI-3P8K-HVES-5G

### ISSUE THREAD

**Issue by dewafre** [wills106/homeassistant-solax-modbus#210]
Hello guys,
I dont get any entities in HA and the log says "unrecognized SolisSolax inverter type"

**Mandatory details**
1. Integration Version: just installed the last one
2. HA Version:
Home Assistant 2022.11.3
Supervisor 2022.10.2
Operating System 9.3
Frontend-versie: 20221108.0 - latest
3. Inverter Brand: Solis RHI-3P8K-HVES-5G
4. Plugin Used: Solis
5. First 6 digits of Serial: 110C92*********
6. Connection Method: LAN

**Detailed Error Log**
Logger: custom_components.solax_modbus.plugin_solis
Source: custom_components/solax_modbus/plugin_solis.py:97
Integration: SolaX Inverter Modbus (documentation, issues)
First occurred: 16:33:58 (1 occurrences)
Last logged: 16:33:58

unrecognized SolisSolax inverter type - serial number : 110C9222******

**Additional context**
I used the IP of the logger + port 8899

**Comment by wills106** [comment]
Just released 0.7.0b44 which should work with your Inverter now.

**Comment by dewafre** [comment]
Nice, it works perfect!!!
Thx alit



Op vr 18 nov. 2022 17:11 schreef wills106 ***@***.***>:

**Comment by dewafre** [comment]
Hello after reading the wiki and trying to install the energy dashboard I have one little problem.
Can I refer to the https://github.com/wills106/homeassistant-solax-modbus/discussions/211#discussion-4583863

Thx alot !

**Comment by dewafre** [comment]
> Hello after reading the wiki and trying to install the energy dashboard I have one little problem. Can I refer to the [#211 (comment)](https://github.com/wills106/homeassistant-solax-modbus/discussions/211#discussion-4583863)
> 
> Thx alot !

Hello @wills106 

I think i solved the problem by adding **scale = 0.1,** in plugin_solis.py
Is this correct?

**Comment by wills106** [comment]
It's built into the dashboard to reset production values if it drops to zero. (STATE_CLASS_TOTAL_INCREASING)

Does your grid_import_total drop to zero as well? If not you could use that in your dashboard instead?

**Comment by dewafre** [comment]
> It's built into the dashboard to reset production values if it drops to zero. (STATE_CLASS_TOTAL_INCREASING)
> 
> Does your grid_import_total drop to zero as well? If not you could use that in your dashboard instead?

_sensor.solis_grid_import_today => solved scale = 0.1
sensor.solis_meter_grid_import_total => solved scale = 0.01
sensor.solis_grid_export_today => solved scale = 0.1
sensor.solis_meter_grid_export_total => solved scale = 0.01
sensor.solis_meter_total_activepower => solved scale = 0.01_

Ok i will try sensor.solis_meter_grid_import_total & sensor.solis_meter_grid_export_total instead in the energy dashboard and let you know if works OK

**Comment by wills106** [comment]
It should work fine, we have to do a similar thing on the Gen2 SolaX.

On the Gen3 & Gen4 you have "Battery Input Energy Today" which we use for the Dashboard.

The Gen2 doesn't have that register, so you have to use "Battery Input Energy Total"

**Comment by wills106** [comment]
@kai-seipp do the above sensors read ok on your Inverter or do they need scaling how @dewafre has suggested?

**Comment by kai-seipp** [comment]
Hey Guys, 

I don't trust my inverters import / exports readings at all. 
I use a shelly 3EM to monitor these values. So I have not yet really checked them. 

But yes they do need scaling from what I can see. 
Here is what I could find: 

Grid Import Yesterday Shelly: 7,66 kWh
Grid Import Yesterday Solis South Inverter: 84 kWh
Grid Import Yesterday Solis North Inverter: 60 kWh

Grid Export Yesterday Shelly: 3,09 kWh
Grid Export Yesterday Solis South Inverter: 12 kWh
Grid Export Yesterday Solis North Inverter: 12 kWh

**Comment by wills106** [comment]
@blackwhitebear8 @dewafre @kai-seipp 
With 0.7.0b47 do your scaling look correct now?
Also are your timed charge / discharge looking more normal now?
You times for example should be 0-23 hours and 0-59 mins. Before they were probably all random looking?

**Comment by blackwhitebear8** [comment]
The update broke more here xd
![Screenshot_20221127_120123](https://user-images.githubusercontent.com/45701225/204131815-b4f6d32d-db18-428f-8d49-a433d560bc6b.jpg)
Theres no battery connected still

**Comment by wills106** [comment]
Can you share the exact entity names for those two broken ones please.

**Comment by wills106** [comment]
I haven't changed any battery entities so I don't know what's going on with the battery one. Unless you added something that wasn't a battery there?

**Comment by blackwhitebear8** [comment]
I saw there were a few more broken ones
Meter active power
Battery power
And house load becouse it doesnt do anything anymore

**Comment by wills106** [comment]
@blackwhitebear8 could I have a screen shot of how they look and a description of what they should be. I don't know if I have scaled too high or too low.

**Comment by blackwhitebear8** [comment]
well battery should be 0
meter active power is idk what it needs to be becouse house load doesnt show anything anymore
<img width="751" alt="Screenshot 2022-11-27 122224" src="https://user-images.githubusercontent.com/45701225/204132588-024af2fd-bcad-43b9-8b8d-3de249e3bd49.png">

**Comment by blackwhitebear8** [comment]
i m also seeing this now:
Logger: custom_components.solax_modbus
Source: custom_components/solax_modbus/__init__.py:226
Integration: SolaX Inverter Modbus ([documentation](https://github.com/wills106/homsassistant-solax-modbus), [issues](https://github.com/wills106/homsassistant-solax-modbus/issues))
First occurred: 12:27:02 (12 occurrences)
Last logged: 12:27:08

Solis: read failed at 0x8199: house_load_total
Solis: read failed at 0x819b: house_load_today
Solis: read failed at 0x819c: house_load_yesterday
<img width="724" alt="Screenshot 2022-11-27 122727" src="https://user-images.githubusercontent.com/45701225/204132793-c5adc853-02c9-44dd-b428-eb1e7cdda234.png">

**Comment by wills106** [comment]
"Battery Power" and "House Load" haven't been changed in a while.

Does 0.7.0b48 correct the rear fail of:
Solis: read failed at 0x8199: house_load_total
Solis: read failed at 0x819b: house_load_today
Solis: read failed at 0x819c: house_load_yesterday

**Comment by blackwhitebear8** [comment]
Doesnt look like it i also see this now

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.solax_modbus.sensor
Source: custom_components/solax_modbus/sensor.py:124
Integration: SolaX Inverter Modbus (documentation, issues)
First occurred: 12:41:21 (1 occurrences)
Last logged: 12:41:21

input register already declared: 0x816a energy_storage_control_switch

**Comment by wills106** [comment]
0.7.0b49 will correct "Energy Storage Control Switch"

**Comment by blackwhitebear8** [comment]
everything seems back to normal now again only meter active power is still saying 300.000W and by sensors its still expecting KWH for some sensors

**Comment by wills106** [comment]
> meter active power is still saying 300.000W

I am guessing it isn't expecting any round then, it should just be 300w

> still expecting KWH for some sensors

Could you let me know which ones and I can correct the native_unit_of_measurement for them.

**Comment by blackwhitebear8** [comment]
solis meter active power is in kwh (maybe that explains why it has .000 when its displayed in W)
more sensors i havent added / in use atm that do this

**Comment by kai-seipp** [comment]
> @blackwhitebear8 @dewafre @kai-seipp With 0.7.0b47 do your scalings look correct now? Also are your timed charge / discharge looking more normal now? You times for example should be 0-23 hours and 0-59 mins. Before they were probably all random looking?

The entity sensor.solis_meter_active_power must be in W not in kWh. 
Scaling of Grid Import / Export looks good now. Still don't Trust the numbers though... 

I did see you introduced a control for different programs of the inverter. Nice! 
My suggestion is to use the working of what people get in that little documentation Solis is sharing... 
![manual](https://user-images.githubusercontent.com/22188947/204136068-9927a145-71f4-48a2-961a-74964f8ae051.png)

So I assume "Spontaneous Mode" should be "Auto Mode"?

**Comment by wills106** [comment]
Could I have some screen shots of these sensors from the Integration page an not a dashboard.

"Meter Active Power"
"Meter Active Power Total"

If any 3 Phase also:
 
"Meter Active Power L1"
"Meter Active Power L2"
"Meter Active Power L3"

It's hard to tell if the dashboard is doing stuff to the values or not, I need to see the raw numbers then I can correct them.
According to the docs they should all be kW

> So I assume "Spontaneous Mode" should be "Auto Mode"?

Yea I was just going of the docs, I thought it was a funny name!

**Comment by blackwhitebear8** [comment]
Meter Active Power
<img width="416" alt="image" src="https://user-images.githubusercontent.com/45701225/204136672-5a5d53bf-3b73-4dae-b937-e96890ff06bc.png">
Meter Active Power Total
<img width="419" alt="image" src="https://user-images.githubusercontent.com/45701225/204136690-9aa0586f-5bcb-4239-815a-520257fd380c.png">
Meter Active Power L1
<img width="418" alt="image" src="https://user-images.githubusercontent.com/45701225/204136705-0f9eb3a8-9295-45f0-864a-0ecba3d4827b.png">
Meter Active Power L2
<img width="419" alt="image" src="https://user-images.githubusercontent.com/45701225/204136713-be179904-ba6e-4ddd-846b-b593a0da6ba6.png">
Meter Active Power L3
<img width="414" alt="image" src="https://user-images.githubusercontent.com/45701225/204136724-e3814d4a-17eb-4ce7-b9d1-824e8893fe12.png">

**Comment by wills106** [comment]
I forgot there are two Meter Active Power in the docs!
I was looking at the wrong one...

So on a 3Phase the following are correct?

"Meter Active Power Total"
"Meter Active Power L1"
"Meter Active Power L2"
"Meter Active Power L3"

**Comment by wills106** [comment]
For
"Meter Active Power L1"
"Meter Active Power L2"
"Meter Active Power L3"
"Meter Active Power Total"
Could I have a screen shot of all 4 of them from the Integration page like:

![image](https://user-images.githubusercontent.com/18155231/204137332-ccde24aa-a05f-45c4-9c50-507f5f5aa8e6.png)

That way I am see them in the same time instance.
I am assuming L1 + L2 + L3 should = Power Total?

**Comment by blackwhitebear8** [comment]
<img width="358" alt="image" src="https://user-images.githubusercontent.com/45701225/204137835-e2978e9c-3020-416e-bbd4-58cf0ad48ae6.png">

**Comment by wills106** [comment]
So when Active Power Total was -0,488kW was Active Power 488w?

**Comment by blackwhitebear8** [comment]
yes and the - means its being imported - bought atm

**Comment by wills106** [comment]
Right ok, I understand what's going on now. I'll make some corrections.

**Comment by wills106** [comment]
0.7.0b50 should correct this now.

**Comment by blackwhitebear8** [comment]
the extra 0 are gone now

**Comment by wills106** [comment]
Do any other sensors seem to be either named incorrect or scaled incorrect?

**Comment by blackwhitebear8** [comment]
is there a way to get all sensors in a dashboard at once so i can look at them?

**Comment by wills106** [comment]
Best way it to take a screenshot of the Integration Page.

Or create a blank Dashboard page and add them all using the Add to Dashboard Button. They might be more compact that way.

**Comment by blackwhitebear8** [comment]
what do you mean with intergration page?

**Comment by wills106** [comment]
Settings / Devices & Services / 
![image](https://user-images.githubusercontent.com/18155231/204138811-d56b7bd5-730d-42d1-b614-fc07a3062181.png)

You should see a big list.

**Comment by blackwhitebear8** [comment]
you can change configs via there of the inverter????

**Comment by wills106** [comment]
If you click that 1 device you will see all of the entities.

There is the option to set charge / discharge times etc. But untested.

**Comment by blackwhitebear8** [comment]
i hope you can do something with this
![192 168 0 187_8123_config_devices_device_53f8e8c118f44ec0a2d52d43e4aa7ca9](https://user-images.githubusercontent.com/45701225/204139041-866711d0-6fc0-4154-8162-c4e7aec78d81.png)

**Comment by wills106** [comment]
It's a bit low quality and some the units of measurement are chopped off.

But nothing obviously wrong is sticking out to me?

**Comment by blackwhitebear8** [comment]
battery voltage shows 1.7V but there is no battery connected?
what is a bypass load?
meter current shows high A at all times i dont think theres 18amps flowing though it when theres only 1000 watts of usage
and is there a sensor for inverter errors?

**Comment by kai-seipp** [comment]
You can check most of the values shown in HA by comparing them to the ones shown within the Inverters menu. Go there on Info, Meter and click through those. 

This integration can only show what the inverter is passing on.

**Comment by wills106** [comment]
Battery voltage - It might just not be very accurate at low voltages, so it's a phantom rading.
Bypass load - no idea to be honest, it's just in the docs. Anything in your User Manual?
Meter Current - do you think it should be 1.8A?
Inverter Errors - Yes, but not yet implemented. I need to add reading individual bits of a register. It's on the Todo List V2. It's needed for SolaX as well.

**Comment by blackwhitebear8** [comment]
meter current isnt right if it was 1.8 it would be too low idk how it calculates it

**Comment by kai-seipp** [comment]
I checked meter current against my 3EM, yes the decimal must go one to the left. 13,0 should be 1,30

**Comment by wills106** [comment]
My house load is about 350w ~ and the Inverter current is 1.6A to 1.7A

**Comment by blackwhitebear8** [comment]
my load is about 775W and the current shows 22,8A

**Comment by blackwhitebear8** [comment]
2.28A cant be right either?

**Comment by kai-seipp** [comment]
> meter current isnt right if it was 1.8 it would be too low idk how it calculates it

Please check against the values your inverter or what your meter display shows.

**Comment by wills106** [comment]
Yea that works out there about's 415v = 1.86A

**Comment by blackwhitebear8** [comment]
meter shows around 5.1A atm

**Comment by blackwhitebear8** [comment]
20.04 is displayed in HA

**Comment by kai-seipp** [comment]
> 2.28A cant be right either?

Why not, seams quite plausible to me.

**Comment by blackwhitebear8** [comment]
2.28A with 775W load is not correct 😂 should be around 3.3A then

**Comment by kai-seipp** [comment]
Well I will call it a Sunday for today. Maybe we should all try to bundle our feedback and requests a little. I would hate to see Wills personal battery at low power.

**Comment by wills106** [comment]
Well some of your PV will be powering things. Not just grid pull.

**Comment by wills106** [comment]
You will never get things to add up 100%
PV, Battery (when you get one) Grid are all at different voltages. There will also be losses through conversions etc.

I think that 18A does need changing to 1.8A though. It will be close enough.

**Comment by blackwhitebear8** [comment]
<img width="370" alt="Screenshot 2022-11-27 155548" src="https://user-images.githubusercontent.com/45701225/204141768-3196be65-43f8-4ba2-937a-1c9643d5a80e.png">
grid + solar =996W
house only reports 933W wheres my other power?

**Comment by kai-seipp** [comment]
The inverter itself consumes about 20w when active. 
And also: 

You read out via Modbus, about 100 registers. 
By the time you have read out the last the values of register first will already have shifted a little. You should see this as a way to learn where your energy is coming from and going to. Especially over the course of time. 

Don't make it a science. I have three different meters in my setup and all are showing little different values. I my opinion we should aim for "good enough". The time and budget you would have to invest for "perfect" is - this is at least my opinion - just not worth it for a home installation.

**Comment by blackwhitebear8** [comment]
also what happends when the inverter goes off and turns on again does it auto pickup or? becouse after i restarted it yesterday (HA) i needed to restart HA again todat to get data again everything was just showing 0 before that

**Comment by wills106** [comment]
If you restart HA during the evening / night (when the Inverter is asleep) you will loose the connection and you will have to restart HA when the Inverter wakes up.

If you leave HA alone tonight, when the Inverter goes to sleep HA will wait for it. Then it the morning when the Inverter wakes up it will carry on sending data to HA.

**Comment by blackwhitebear8** [comment]
will this eveer be like fixed?

**Comment by wills106** [comment]
It's not a bug.

HA / The Integration can't establish a connection if there is nothing to communicate to.

**Comment by blackwhitebear8** [comment]
can you not add something that it retries connection?

**Comment by wills106** [comment]
No, day to day you shouldn't need to restart HA.
There is already code in there to reduce slowdown when it tries to poll during sleep, it skips 9 out of 10 read requests.

**Comment by blackwhitebear8** [comment]
i think this error means that the inverter is offline?

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.solax_modbus
Source: /config/custom_components/solax_modbus/__init__.py:337
Integration: SolaX Inverter Modbus (documentation, issues)
First occurred: 17:09:24 (245 occurrences)
Last logged: 18:34:57

Solis error reading holding registers at device 2 position 0xa86c
NoneType: None

**Comment by blackwhitebear8** [comment]
sensor house load doesnt reset / go to 0 when the inverter is offline

**Comment by wills106** [comment]
I am going to close down as the Integration now supports '110C' Inverters.

Any further issues, please raise a new issue.
