### ISSUE TITLE
[FEATURE REQUEST] Pgrid Bias setting

### ISSUE THREAD

**Issue by alibasta** [wills106/homeassistant-solax-modbus#223]
With the latest FW update G4 inverters received a Pgrid Bias setting with the following options:

![image](https://user-images.githubusercontent.com/362022/204498742-cf6c7af9-a73c-4b88-88d6-3b2585d671fc.png)

Currently this value does not seem to be visible in the HA integration.

**Comment by wills106** [comment]
Yes, I can add this in.

**Comment by alibasta** [comment]
I'm able to try it out manually. Is it already pushed?

**Comment by wills106** [comment]
Yes

**Comment by alibasta** [comment]
I updated the plugin_solax.py containing the "Pgrid Bias" setting and restared the server. "Pgrid Bias" is _not_ visible as entity. Is there anything more I need to do?

**Comment by wills106** [comment]
Is the select not visible or the sensor or both?
The sensor isn't visible by default but the select should be.

If it's not try removing the Integration from the Integration page and re-adding it.

**Comment by wills106** [comment]
If you are on 0.6.4 you will need to move to 0.7.0bx I have just released 0.7.0b58 with the changes in case you are still on 0.6.4

**Comment by alibasta** [comment]
Thanks!! It works as it is supposed to.
