### ISSUE TITLE
[BUG] In the top right of the screen, to the left of the SolaX Power, it shows unavailable % and a battery symbol

### ISSUE THREAD

**Issue by pchaves1** [wills106/homeassistant-solax-modbus#232]
Hi, hope you're well.

Go to ... Settings => Devices & Services => SolaX => 1 Device
In the top right of the screen, to the left of the SolaX Power, it shows unavailable % and a battery symbol.
I have a Solax Gen4 inverter.

![image](https://user-images.githubusercontent.com/45390982/205986986-9df411c0-74f8-485a-922f-695e80a8676b.png)

I'm using the latest version from today.
Any advice?

Thanks in advance!

**Comment by wills106** [comment]
When you say latest do you mean latest stable 0.6.4 or the latest Beta? As I released two Beta's yesterday.

**Comment by wills106** [comment]
When you went from 0.6.4 to 0.7.0bx did you make sure you removed it from the Integration page and restarted HA before adding it back?

**Comment by pchaves1** [comment]
Sorry, your are correct!
I did not
Now it's OK
![image](https://user-images.githubusercontent.com/45390982/206258058-258218a8-def4-496c-aa99-b52025817e47.png)

**Comment by wills106** [comment]
I'll close this as the bug is fixed in 0.7.0b
