### ISSUE TITLE
Possible Missing Solis Data Value

### ISSUE THREAD

**Issue by J14111** [wills106/homeassistant-solax-modbus#238]
on the Solis official portal it shows you the power going to the battery in watts/kw but I cant find this parameter exposed, its possible its missing or they calculate the value from the volts/amps?

**Comment by wills106** [comment]
You have "Battery Power" which is two way.

You also have "Battery Charge Today" & "Battery Discharge Today"

**Comment by J14111** [comment]
Thanks I will look at that

**Comment by J14111** [comment]
As its two way and it doesnt seem to be + or - do you know how I can differentiate as its messing my graphs up

**Comment by wills106** [comment]
Does [2022.12.7b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2022.12.7b1) have Battery Input / Output Energy the correct way round?

**Comment by J14111** [comment]
I will test thanks

**Comment by J14111** [comment]
I am getting this 
![image](https://user-images.githubusercontent.com/120409046/207617002-b2323521-8eba-4a05-9c87-128debf83e00.png)

I think it may be a shortcoming on the Solis as I have spoken to someone else, I think I will need to do some logic in my reporting to get the correct data unless you have a solution?

**Comment by wills106** [comment]
add '_charge' to the end of it.

Do you see battery_input_power and battery_output_power though?

**Comment by J14111** [comment]
Seems good so rat will have to check once the sun goes down :)

![image](https://user-images.githubusercontent.com/120409046/207619754-89ca34cc-9c72-4118-999e-90409fbb22e1.png)

**Comment by J14111** [comment]
It does not work correctly, Battry Input energy works the same as "Battery Power" used to, it shows both in and out. Battery Output Enegry shows nothing at all

**Comment by wills106** [comment]
There is a register that tells you if the battery is charging or discharging. I guess you could try and build that into a template sensor so you know if "Battery Power" should be positive or negative.

**Comment by wills106** [comment]
I don't know if it will work or not? But try [2022.12.7b2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2022.12.7b2)

I have renamed battery_power_charge back to the original battery_power.
It this works I'll set "battery_power" & "battery_charge_direction" both to hidden / disabled by default.

**Comment by J14111** [comment]
Thanks it shows as a 1% now and its discharging, is that what you expect?

![image](https://user-images.githubusercontent.com/120409046/207634551-6224ee0d-a634-452e-acf3-4358a1ccfad5.png)

**Comment by wills106** [comment]
Well, it's not meant to be 1% (only 1). That's because I copied and pasted without checking 🤣
But other than that yes.

So "Battery Output Energy" should display a value and "Battery Input Energy" should be 0.
Is that correct?

**Comment by wills106** [comment]
[2022.12.7b3](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2022.12.7b3) corrects the % and the incorrect 'DEVICE_CLASS_BATTERY'

**Comment by J14111** [comment]
> Well, it's not meant to be 1% (only 1). That's because I copied and pasted without checking 🤣 But other than that yes.
> 
> So "Battery Output Energy" should display a value and "Battery Input Energy" should be 0. Is that correct?

Yes that appears to be working now but I wont know for sure until I see sun tomorrow now and the batteries charge, thanks so much for all your help. I will let you know how it goes.

![image](https://user-images.githubusercontent.com/120409046/207638922-c7af243f-9171-4845-8e58-1d8ef6c2bbcd.png)
![image](https://user-images.githubusercontent.com/120409046/207639129-3b73a8f1-803c-4666-ba71-ce6f81a24f7b.png)

**Comment by wills106** [comment]
If it works fine I'll release it as a proper release and I'll also disable the view of "battery_power" & "battery_charge_direction" as they don't need to be visible.

**Comment by J14111** [comment]
The sun has come up and it works like a charm thanks so much!

So Charge Direction 1 = battery discharging and 0 = battery charging?

![image](https://user-images.githubusercontent.com/120409046/207816039-8a36ebc8-fa73-4687-9135-1bc714fafef4.png)
![image](https://user-images.githubusercontent.com/120409046/207816093-f4b0f55a-f835-4596-8602-48e1da9095e8.png)

**Comment by wills106** [comment]
Yes that matches what I said here https://github.com/wills106/homeassistant-solax-modbus/issues/238#issuecomment-1351581196
