### ISSUE TITLE
pv_power_total unit of measurement Sofar HYD 10ktl-3ph

### ISSUE THREAD

**Issue by juraurban** [wills106/homeassistant-solax-modbus#244]
PW Power total sensor has wrong decimal value.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/61117883/207314884-1e5fe8b2-874f-409f-83e0-6d0f57d73647.png">

Setting scale = 0.1 at this register, helps.
<img width="310" alt="image" src="https://user-images.githubusercontent.com/61117883/207315948-b4aa9830-9f7d-4d9c-ad03-51b4c059e366.png">

Thank you for fixing that in your code as well.

**Comment by wills106** [comment]
Are you on 2022.12.x I thought I corrected that during 0.7.0bx before releasing the stable branch?

**Comment by wills106** [comment]
With scale at 0.1 does it ever return 2 digits after the decimal ie 2.34kW or is it only ever 2.3kW?
I might need to drop the rounding to 1 as well if it's ever only 2.3

**Comment by wills106** [comment]
PV Power Total is corrected in [2022.12.6](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2022.12.6)

**Comment by wills106** [comment]
Have you managed to test this?
If so and it's correct I'll close the issue down.

**Comment by darkrain-nl** [comment]
For my device the 0.01 and rouding 2 were working fine, now I get this:
![afbeelding](https://user-images.githubusercontent.com/24763370/208235660-4381287b-2499-44e4-b9f5-059edf8778e7.png)

**Comment by wills106** [comment]
I have just checked and you have a PV only Inverter 'SS2E' don't you?

So it must have a slightly different rounding on PV Power Total

**Comment by darkrain-nl** [comment]
> I have just checked and you have a PV only Inverter 'SS2E' don't you?
> 
> So it must have a slightly different rounding on PV Power Total

Yes that is correct, is there any smart way to fix that? 
I do have a workaround and that is to use a different sensor for this reading, I just use sensor.sofar_active_power_output_total which seems to be the same thing anyway in my specific case.

**Comment by juraurban** [comment]
Sorry for late answer. Unfortunately I have had panels covered with layer of snow since last week therefore 0. Shows only 1 decimal
![Uploading 7AFDE8E1-F170-4C94-BC83-CF06A90A649E.png…]()

**Comment by wills106** [comment]
> Yes that is correct, is there any smart way to fix that?

Yes I can have a PV only version and a Hybrid only version of the same sensor with the different scaling required.

**Comment by juraurban** [comment]
![ACE83DAC-590C-4B64-BBF1-5E29FA1748C3](https://user-images.githubusercontent.com/61117883/208236621-fee649f6-4fd6-48aa-b54e-96bb1d152523.png)

**Comment by juraurban** [comment]
![428E2BDD-8D0E-4678-A8FF-F1DAA317B068](https://user-images.githubusercontent.com/61117883/208236648-ef0fa37f-3471-4458-a373-2c12d37b95c3.jpeg)

**Comment by juraurban** [comment]
Inverter shows 10W current production

**Comment by wills106** [comment]
As PV Power Total is only designed from Sofar to be in 0.1 resolution it won't display anything less than 100w

**Comment by wills106** [comment]
[2022.12.8](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2022.12.8) will correct "PV Power Total" scaling on KTLX-G3 Inverters

**Comment by darkrain-nl** [comment]
> [2022.12.8](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2022.12.8) will correct "PV Power Total" scaling on KTLX-G3 Inverters

Thanks, can confirm this works great!

**Comment by wills106** [comment]
I'm going to close this down now as "PV Power Total" is now correct for the Hybrid and PV only Inverters.
