### ISSUE TITLE
Error on 2022.12.4 - KeyError: 'plugin'

### ISSUE THREAD

**Issue by t3lmoazevedo** [wills106/homeassistant-solax-modbus#246]
Updating from 0.6.4 to 2022.12.4 fails on the integration with:

Error setting up entry SolaX for solax_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/solax_modbus/__init__.py", line 90, in async_setup_entry
    _LOGGER.debug(f"Ready to load plugin {config[CONF_PLUGIN]}")
KeyError: 'plugin'

![image](https://user-images.githubusercontent.com/41584793/207543515-e86e1797-25db-4753-a00d-f242227f479d.png)

**Comment by infradom** [comment]
Furthermore, we did not receive contexxt information (Hardware platform, OS platform, HA version, inverter type, ...
So it is very difficult to provide support with so little information

**Comment by t3lmoazevedo** [comment]
@infradom thanks for the tip.
Removing and reinstaling fixed the situation ;) 
Great support here!
