### ISSUE TITLE
Missing radiobuttons on configuration

### ISSUE THREAD

**Issue by gelse** [wills106/homeassistant-solax-modbus#269]
**Describe the bug**
When creating a new config (after removing previous installation / upgrade), the radio buttons for the inverter type are missing, thus leading to invalid user input:
`User input malformed: value must be one of [] for dictionary value @ data['plugin']`

**Mandatory details**
1. Integration Version: 2022.12.12 (also tried 2022.8 and main)
2. HA Version: 2022.12.7

**Detailed Error Log**
there is no error log, it is an UI error.

<img width="260" alt="image" src="https://user-images.githubusercontent.com/49122643/208943649-71a518e5-472e-4fea-9494-3e800a29fce9.png">

**Comment by gelse** [comment]
as a fallback it would be nice to have a how-to somewhere how i can configure the integration via YAML.

**Comment by wills106** [comment]
Have you upgraded from 0.6.4 or earlier without removing the Integration from the Integration page, restarting HA and adding it back to the Integration page?

**Comment by gelse** [comment]
no, i followed the instructions by the book.  
i removed the integration from HA
i removed the integration from HACS
i restarted HA
i added the integration in HACS
i restarted HA again
i tried to add he integration in HA

**Comment by gelse** [comment]
and also, as i said in the description above, there are NO errors of solax in the logs of HA.

**Comment by wills106** [comment]
You are somehow missing the whole section from the config flow where you select which plugin you want.

On the Integration page have you tried forcing a refresh?
Ctrl + F5
Then try adding it again?

**Comment by gelse** [comment]
yes, that was the first thing i tried (i am a developer myself ;-) ) - i just re-tried it, same behaviour.

**Comment by wills106** [comment]
I have just done a fresh HACS download on a separate machine and I can't replicate this.

Has HACS downloaded the plugin_sofar plugin_solax files etc?

**Comment by gelse** [comment]
after removal via HACS:
```
root@omv:~/links/homeassistant/config/custom_components# ls
alexa_media  edgeos  elasticsearch  hacs  monitor_docker  myjdownloader  openmediavault  spotcast  xiaomi_cloud_map_extractor  xiaomi_miot
```
then adding it via HACS:
```
root@omv:~/links/homeassistant/config/custom_components# ls
alexa_media  edgeos  elasticsearch  hacs  monitor_docker  myjdownloader  openmediavault  solax_modbus  spotcast  xiaomi_cloud_map_extractor  xiaomi_miot
```
and the content of solax_modbus seems fine to me.

**Comment by wills106** [comment]
I'm on HA 2022.12.5 I'll try 2022.12.7 later today in case they made a change.

**Comment by gelse** [comment]
aaaand another information:
i just tried to configure it with edge browser (normally: brave), which i NEVER used before to access home assistant at all, and i had the exact same behaviour.
as a last resort i try to configure it via Android in a minute.

but i am a bit ... nervous, i just want to get it working again now. i need the statistics.

**Comment by wills106** [comment]
I'll upgrade to HA 2022.12.7 in a bit to see if I can replicate the issue.

**Comment by gelse** [comment]
regarding logs - i set solax_modbus to debug in the config.

all i get in the logs are the following 3 lines:
```
2022-12-21 17:41:34.733 DEBUG (MainThread) [custom_components.solax_modbus] using pymodbus library 2.x
2022-12-21 17:41:34.749 INFO (MainThread) [custom_components.solax_modbus.config_flow] detected HA core version 2022 12
2022-12-21 17:41:34.749 INFO (MainThread) [custom_components.solax_modbus.config_flow] starting configflow - domain = solax_modbus
```

**Comment by gelse** [comment]
My guess from reading the code:
somehow the dynamic loading of the plugins introduced in 469fb8082bf0344ae5aa110c00c056b1e09a1717 does not work.
perhaps it actually HAS something to do with the fact that i am running it via docker ? some weird permissions maybe? i try to tinker around a bit with that ...

**Comment by wills106** [comment]
My main system is Core in Docker on Unraid.

The other system I tried was HAOS on PI4

**Comment by gelse** [comment]
i added a few lines of debug messages, and indeed - it does not load any plugins:
```
2022-12-21 20:02:02.471 DEBUG (MainThread) [custom_components.solax_modbus.config_flow] Plugin path: custom_components/solax_modbus/plugin_*.py
2022-12-21 20:02:02.471 DEBUG (MainThread) [custom_components.solax_modbus.config_flow] Loaded plugins: []
```

the lines i added are in `config_flow.py`:
L59 (directly before the `PLUGINS=` ): `_LOGGER.debug(f"Plugin path: {PLUGIN_PATH}")`
L63 (directly after the `PLUGINS=` ): `_LOGGER.debug(f"Loaded plugins: {PLUGINS}")`

**Comment by wills106** [comment]
When you do `ls -l` do you have read only for the different groups other than owner? Or has HACS removed read only some how?

![image](https://user-images.githubusercontent.com/18155231/208989856-5824ae89-47d6-47b8-8fa5-46fb89ee6d2a.png)

I'm just going to upgrade HA to 2022.12.7

**Comment by gelse** [comment]
it looks exactly that way, all of them are 644

**Comment by gelse** [comment]
i just realized - PLUGIN_PATH is a relative path, i guess glob tries to find it from the CWD.
what if the CWD is not what we expect ?

**Comment by gelse** [comment]
i guess that's it!
i added the following:
```
_LOGGER.debug(f"Current directory: {os.getcwd()}")
```
and got the following in the logs:
```
Current directory: /run/s6-rc:s6-rc-init:hjCanB/servicedirs/svc-homeassistant
```
i then attached to the container and checked what the directory is:
```
root@acbf3661c008:/run/s6-rc:s6-rc-init:hjCanB/servicedirs/svc-homeassistant# ls
down  event  notification-fd  run  supervise
```

which is NOT the root of the config.
my guess: there is some way to get the actual absolute path of the home-assistant configuration directory path - and that is missing here.

i guess the reason is because i am using the linuxserver.io docker image

**Comment by wills106** [comment]
Is your config folder mapped to a drive on your NAS or however you are running this? Or is it all stored in your docker image?

**Comment by gelse** [comment]
and so it is:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/49122643/208997979-10e7e8bd-30e4-418f-893d-7dadb7265054.png">


what i changed - and i admit it is a dirty hack that only works temporarily, but i think it should point you in the right direction:

in solax_modbus/const.py i changed the following lines:
```
DEFAULT_PLUGIN   = "/config/custom_components/solax_modbus/plugin_solax.py"                                                                                                                                                                                           PLUGIN_PATH      = "/config/custom_components/solax_modbus/plugin_*.py"     
```

which in MY case is the correct location.

i did open heart surgery here, so this bug is NOT closed, but i think it should be straightforward to implement now.

**Comment by wills106** [comment]
This is how my setup is mapped
/config <-> /mnt/user/appdata/Home-Assistant-Core

**Comment by gelse** [comment]
this has nothing to do with mapping of volumes of the docker container, as HA is running inside and it does not know of anything of the outside world.

this has to do with the special way linuxserver.io "simplifies" their images, as they always somehow change the running software for easier volume mappings.

the only way you can solve that (and i learned that the hard way in my job) - never rely on the working directory. NEVER.

**Comment by infradom** [comment]
I think the absolute path might also work on most installations /config/custom...

**Comment by infradom** [comment]
Just tested, and it seems to work with the absolute path on my HAOS
I had to reinstall the integration however ...

**Comment by wills106** [comment]
If people don't remove the Integration prior to updating they are greeted with:

```
2022-12-21 20:43:25.462 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry SolaX for solax_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/solax_modbus/__init__.py", line 95, in async_setup_entry
    plugin = importlib.import_module(f".plugin_{plugin_name}", 'custom_components.solax_modbus')
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.solax_modbus.plugin_'
```

If you try to reconfigure the Integration you loose the plugins.

Deleting and adding the Integration back again doesn't work.

It needs a full removal of the Integration from the Integration page and restarting HA and adding it back in again. For the path changes to take effect.

We'll have a look into a solution that doesn't cause all of the other users pain.

**Comment by gelse** [comment]
i did not have to reinstall when i changed the path, altho i HAD to restart HA.
if i read the logfiles correctly, the integration, and thus the __init__.py, is loaded either on startup when it is configured, or during the first attempt to add a integration configuration.

which actually i just proved, because i made a few more changes and now it will work for every installation:
in const.py:
add this as first line:
```python
import pathlib
```

change this
```python
DEFAULT_PLUGIN   = "custom_components/solax_modbus/plugin_solax.py"
PLUGIN_PATH      = "custom_components/solax_modbus/plugin_*.py"
```
to this
```python
DEFAULT_PLUGIN   = f"{pathlib.Path(__file__).parent.absolute()}/plugin_solax.py"
PLUGIN_PATH      = f"{pathlib.Path(__file__).parent.absolute()}/plugin_*.py"
```

whoever wants it can take credit. ;-)

**Comment by infradom** [comment]
Thanks, but I am still not sur this survives an upgrade, as the result path is probably stored persistently in the config.
I will examine in more detail to see if we need to adapt the string read from config also at startup

**Comment by infradom** [comment]
And why not use absolute paths immediately? The problem of incompatibility lies in the config file entry that needs to be adapted ... I will check the config entry first so see which kind of path it contains in old and new

**Comment by infradom** [comment]
checkedd: The config entry plugin contains a long path in the old version, probably relative,  in the new version: absolute
`'plugin': '/config/custom_components/solax_modbus/plugin_solax.py'`
So when starting up init.py reads this path and determines the name withj const.py getPluginName's function, which probable strips the name in a wrong way...

So we need carefull testing, and I am not sure adding this pathlib library solves the problem (as we can work as well with absolute paths). But there are more small changes needed is what I believe. I will make a proposal ..

**Comment by gelse** [comment]
> Thanks, but I am still not sure this survives an upgrade, as the result path is probably stored persistently in the config.

thats a good concern, but my patch would at least fix the problem for people who have a custom installation directory and/or a different CWD. It of course helps nothing in terms of when you change the file location of the plugins in an upgrade.

> why not use absolute paths immediately? 

well my patch does that, but it calculates the absolute path depending on the location of the current file, which should be correct, wherever the HA config says that the configuration files reside. Unless, of course, in some future version of the integration, you change the location of the plugin files. Then you would have to change that code as well, but that's just obvious.

> as we can work as well with absolute paths

no we can't because there is no guarantee that the configuration directory is /config/

**Comment by infradom** [comment]
OK thanks, all I wanted to say was that the pathlib patch is probably not sufficient if we want our users to be able to upgrade seamlessly

**Comment by gelse** [comment]
yes, i agree with that.

if you want i can take a look into it - calculating the directory on startup and using that throughout the integration should be sufficient, but i would have to read into the details to find every place where the stored path is used.

**Comment by infradom** [comment]
I am working on a solution... the const.py getPluginName() function is probably not needed anymore after another change last weeks

**Comment by gelse** [comment]
actually i think it's the opposite.
if i read that code in __init__.py correctly, it maps any path from the config to a relative filename via getPluginName.

```python
    # ================== dynamically load desired plugin
    _LOGGER.debug(f"Ready to load plugin {config[CONF_PLUGIN]}")
    plugin_path = config[CONF_PLUGIN]
    if not plugin_path: _LOGGER.error(f"plugin path invalid, using default {DEFAULT_PLUGIN}; config dict: {config}")
    plugin_name = getPluginName(plugin_path)
    plugin = importlib.import_module(f".plugin_{plugin_name}", 'custom_components.solax_modbus') 
    if not plugin: _LOGGER.error(f"could not import plugin {plugin_name}")
    setPlugin(name, plugin)
    # ====================== end of dynamic load
```

i just wonder, why the plugin path is stored in the config in the first place, instead of just the plugin name.

**Comment by gelse** [comment]
> ModuleNotFoundError: No module named 'custom_components.solax_modbus.plugin_'

oh my ...
that means, that getPluginName returns empty. would be interesting, what plugin_path is in line 94

**Comment by infradom** [comment]
The modifications I am currently making make sure that the config entry for plugin just constains 'solax' or 'solis', not a path anymore. I do want to keep supporting the old path based entry for a while to avoid yet another breaking update.

**Comment by infradom** [comment]
I used your contribution in a new PR, but I also made the plugin-config independent of paths, and added code to support old and new config entries.
Tested in an upgrade context and tested in a clean new install context
Further tests are welcome (see my PR)

**Comment by wills106** [comment]
The PR closed this down automatically.

I'm just going to test the code change.

**Comment by wills106** [comment]
@gelse does [2022.12.14b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2022.12.14b1) Work fine for you before I release the stable version?

I have tested it on my Docker install and it works smoothly as a code update.

I have also tested it on HAOS as much as I can without connecting to an actual Inverter.

**Comment by gelse** [comment]
i was able to upgrade even without removing the old configuration, integration still works and the GUI also still works.

**Comment by gelse** [comment]
btw you have a typo in the markdown of the index page:
> homsassistant-solax-modbus

**Comment by wills106** [comment]
> i was able to upgrade (to 2022.12.14b1) even without removing the old configuration, integration still works and the GUI also still works.

Thanks, I'll close the issue down then.

**Comment by gelse** [comment]
but ... i just saw the release-notes, and i did not find the error message about the old style plugin name yet... i keep checking my logs

**Comment by wills106** [comment]
It will be changed in the stable release.

**Comment by gelse** [comment]
great, thanks a lot!

but i am feeling tempted to make a full code review like i would at work.... 
... must ... resist ... the ... urge ... ;-)
