### ISSUE TITLE
[BUG] HA unresponsive and slow when its polling

### ISSUE THREAD

**Issue by blackwhitebear8** [wills106/homeassistant-solax-modbus#286]
**Describe the bug**
SInce the last update our HA instance is slow unresponsive and breaks remot eaccess via nabu casa when its polling data from the inverter. When its dark outside so the inverter is off the HA instance becomes responsive again.

**Mandatory details**
Integration Version: 0latest
HA Version: Home Assistant latest
Inverter Brand: solis
Plugin Used: solis
First 6 digits of Serial: 110CA2
Connection Method: Serial (DSD TECH SH-U10 rs485 )

**Detailed Error Log**
there are no errors

If there are no log's showing for SolaX try the following depending on your language settings, you can find the full logs under:

Settings → System → Logs > at bottom of page press “LOAD FULL LOGS”

Now the full logs are loaded. If you scroll down, you will see them.
Once the full logs are shown, you can either use the search function in your browser to search for “solax” related entries or use the search entry field on top of the page.

Search for

solax

and report us the logs. Make sure to replace sensitive information by xxxx (if any)

**Additional context**

**Comment by wills106** [comment]
When you say you are on the latest version of the Integration is that the stable release or the beta release?
What version were you on before when you didn't have the issue?

**Comment by blackwhitebear8** [comment]
i am on stable asfar i know for the plugin
and the issue started after the plugin got updates for other inverters basicly so the last change after my last issue worked great

**Comment by wills106** [comment]
If you look in manifest.py it will tell you which version you have installed.
Code got introduced to deal with sleeping Inverters partway through the development leading up to 2022.12.1 release.

**Comment by blackwhitebear8** [comment]
HA version: Home Assistant 2022.12.8
Frontend-versie: 20221213.1 - latest

intergration version: 2022.12.13 but i see 2023.01.01 is out i will be trying that one now

**Comment by wills106** [comment]
If you connect to your HA instance locally do you get these slow downs? Or is it only when you connect via Nabu Casa?

Are you still getting the Blocking Calls or did you amend your logging like I suggested [here](https://github.com/wills106/homeassistant-solax-modbus/issues/214#issuecomment-1328011729)?

**Comment by wills106** [comment]
If you remove the RS485-USB dongle / the Integration does it go back to normal response?

**Comment by blackwhitebear8** [comment]
Yes

**Comment by blackwhitebear8** [comment]
and if the inverter is sleeping it is responsive aswell again

**Comment by infradom** [comment]
What is your polling rate? Lower than 5 seconds may cause such problems

**Comment by blackwhitebear8** [comment]
2 seconds but we never had problerms before for months it was after an update almost an month ago

**Comment by infradom** [comment]
We did generalize the polling method and cannot guarantee that the system behaves exactly as before when it comes to timings. 
2 seconds may work, but I would not bet on it ... 
When the inverter is asleep, we slow down the polling by a factor 10. This explains the different behaviour

**Comment by infradom** [comment]
Furthermore, each version supports more registers, so this also increases the load on the system.

**Comment by wills106** [comment]
Have you tried going back from 2022.12.8 to see when the problem first started (Previous releases).
Polling at 2s on a 9600 baud is probably pushing the limits of the Inverter. These Solis don't seem the best of communications as it is and they don't follow Modbus protocols. We had to reduce the multi block reads down to 48 registers as they don't comply with the Modbus limit which is over double that.

Also when changing versions have you tried to remove the Integration from the Integration page, restarting HA and adding the Integration after upgrading. To make sure there aren't any bit's of code stuck in HA>

**Comment by blackwhitebear8** [comment]
correction* i see that it was set to 1 second i put it at 2 seconds interval and things look already better.

**Comment by blackwhitebear8** [comment]
it prop wasnt able to get everything within the 1 second becouse everything is normal again now

**Comment by wills106** [comment]
If you get any further slowdowns / read errors I would try changing the poll to 5s before trying anything else.

**Comment by blackwhitebear8** [comment]
well that kinda defeats the purpouse of readig it out via HA we wanted live xd the solis app was limited to 300seconds

**Comment by infradom** [comment]
5 seconds is already a lot better than 300 ..
Dont push us too far ;-)

**Comment by blackwhitebear8** [comment]
there was some update a month ago for wich i had to readd the inverter thats prop when i typed 1 sec instead of 2 :idk: well thanks for the help tho haha

**Comment by wills106** [comment]
I'll close this issue down then if you are back to running as normal.
