### ISSUE TITLE
[Feature Request] Sync inverter time - Solis

### ISSUE THREAD

**Issue by J14111** [wills106/homeassistant-solax-modbus#310]
Hi,

Would it be possible to have an option in the plugin to automatically sync the inverter time daily or weekly with the homeassistant clock at say 2am? this would resolve daylight savings issues, it looks like its possible to set the time via registers on the Solis. Or even better read the time, check its not more than a few seconds out and if it is update it?

![image](https://user-images.githubusercontent.com/120409046/215297856-dd8b0407-1445-4b5c-b05e-88dabbe2abff.png)

![image](https://user-images.githubusercontent.com/120409046/215297789-30cc735d-d13e-40c4-9e7a-c46311b0931f.png)

**Comment by wills106** [comment]
It won't be automatic.
But I can get you a sync button like we have on SolaX.
Then run an automation against it every so often.

**Comment by wills106** [comment]
Just released [2023.01.5b14](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.01.5b14) it should give you the functionality you want.

**Comment by J14111** [comment]
Thanks will give it a go, does it check the time and only sync if needed, just so I know and can avoid excessive register writes?

**Comment by wills106** [comment]
It's purely manual.
Just a sensor you can enable if you wish to see the RTC and a button to Sync it to HA.

So you would need an automation to press the button one a week or once per month etc

**Comment by wills106** [comment]
Updating the RTC should work. But the sensor for RTC won't as reading it wrong.
I'll do an update.

**Comment by wills106** [comment]
Corrected in [2023.01.5b15](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.01.5b15)

**Comment by J14111** [comment]
Thats brillaint thanks!

**Comment by wills106** [comment]
Once you have tested it, are you ok closing the Issue down?

**Comment by J14111** [comment]
Ok will do, I have tried it and no error but I will have to go in the loft to check on the screen, I know I was about 5 mins fast before, I will close now and reopen if needed, thanks again.

**Comment by J14111** [comment]
It works perfectly, I set the time wrong on the inveter then synced and it updated fine, I have set an automation to run it every sunday at 2:02am so that should cover keeping it in sync and DST changes but I guess I will get duplicate wonky data when the clocks go back but thats not much of an issue. Thanks so much!

**Comment by wills106** [comment]
Glad it's helped.
