### ISSUE TITLE
Battery power total rounding to 2 decimal points

### ISSUE THREAD

**Issue by juraurban** [wills106/homeassistant-solax-modbus#323]
Hi, 
Sofar HYD 10 KTL 
can you please fix for me rounding of Battery power total to 2 decimal points ... to the same as Sofar Battery Power 1
<img width="378" alt="image" src="https://user-images.githubusercontent.com/61117883/216783459-d98f8cee-39bd-4460-a86a-106917403a13.png">

**Comment by wills106** [comment]
Register 667 is only rounded to 0.1 according to the documentation:

https://github.com/wills106/homeassistant-solax-modbus/blob/f4254203f16b1f78d5a9f13210e7c937feb178dd/custom_components/solax_modbus/plugin_sofar.py#L1837-L1848

![image](https://user-images.githubusercontent.com/18155231/216788890-8b3fb720-fe92-457d-a431-bb49660e1376.png)

**Comment by juraurban** [comment]
Thanks for comment, I am closing this one.
