### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by blackwhitebear8** [wills106/homeassistant-solax-modbus#325]
Can we get an error sensor that if the in my case solis inverter gets into an error state we can read that out via home assistant.

**Comment by wills106** [comment]
It's already on the Todo List V2 https://github.com/wills106/homeassistant-solax-modbus/discussions/200#discussioncomment-4242410

**Comment by wills106** [comment]
I still have a bug in the current beta for Solis without a battery / not enough battery to last the night.
I have a workaround to push out as a Beta. If that works I might push out a proper release and look at fixing it properly later.

**Comment by wills106** [comment]
I'm closing this issue as [2023.05.1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.05.1) is released.
Which includes what you requested.
