### ISSUE TITLE
Two solax inverter integration

### ISSUE THREAD

**Issue by klio-klio** [wills106/homeassistant-solax-modbus#334]
Hello, I tried to integrate my second inverter today. Had to find out that the display is wrong. The Entetis were integrated from old into new. Battery is displayed in new even though none is connected. PV power is the same. Do I have to pay attention to anything? The old inverter is the X3 8000 hybrid old generation still with network interface. The new one is the X3 Hybrid 15.0 D Modbus connection via COM connection.
![solax](https://user-images.githubusercontent.com/76972213/219951492-e2e81913-31f9-4a65-9d16-824f230133de.jpg)

**Comment by wills106** [comment]
Have you given them both unique names? Ie SolaX West, SolaX SouthEast etc

**Comment by klio-klio** [comment]
Of course... name. Thank you. Mea culpa!!!

**Comment by wills106** [comment]
Is everything running ok now? If so could you close the issue down?
