### ISSUE TITLE
[BUG] - different value of Export Control User Limit between local<>cloud

### ISSUE THREAD

**Issue by lowprize** [wills106/homeassistant-solax-modbus#339]
1. 2023.02.6
2. Home Assistant 2023.2.5
3. Solax
4. over HACS
5. H3UE10
6. Ethernet TCP modbus

Steps to reproduce
1. set Export Control User Limit to 9100 over HA Integration
2. check this value on cloud or app, it is 91 000

![HA-solax](https://user-images.githubusercontent.com/17613941/220909076-69fe5ee0-3b35-493e-be68-d04b90d0495b.png)
![cloud](https://user-images.githubusercontent.com/17613941/220909078-e2bc5038-b787-4e0d-b5bc-e2c6afa1a340.jpg)

.

**Comment by infradom** [comment]
See also issue [BUG] solax_export_control_user_limit entities incorrect by 10x #418
I suggest we add your serial number prefix to the code in one of the next updates.

An alternative solution will be provided with PR https://github.com/wills106/homeassistant-solax-modbus/pull/430 soon
You can set the new entity's value  to 10.

Sorry for the delay in resolving this ...
