### ISSUE TITLE
Support for Solax X3-MIC, Serial number MU50...

### ISSUE THREAD

**Issue by tomasko25** [wills106/homeassistant-solax-modbus#342]
Hello!

I have Solax X3-MIC with serial number starting MU50 connected through Waveshare RS485 to ETH gate. The communication seems to be working and the HA log is here: 
![solax](https://user-images.githubusercontent.com/72974725/222945761-e92177cf-4e16-42bb-b289-ca79101a2b3e.png)
Would it be possible to support also this inverter? 
Thanks!

**Comment by wills106** [comment]
Just released [2023.03.1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.03.1) which adds in support for your Inverter.

**Comment by tomasko25** [comment]
Many thanks!
