### ISSUE TITLE
[Feature Request] Restart invertor button - Solis

### ISSUE THREAD

**Issue by J14111** [wills106/homeassistant-solax-modbus#348]
Hi,

Would it be possible to get a button to restart the inverter, i guess there must be a register for this?

**Comment by wills106** [comment]
There doesn't seem to be an actual restart register. But there is a Power switch one. I have included it in [2023.03.2b2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.03.2b2) it's called "Power Switch"

**Comment by J14111** [comment]
Thanks so much will give it a test

**Comment by wills106** [comment]
Have you been able to confirm if this switch works ok?

**Comment by wills106** [comment]
Have you been able to test this?
Just wondering if I can close some of these issues down.

**Comment by J14111** [comment]
I did a quick test and it seems to stop production and start it again but I havnt been ablet to check on the screen, I think it is more an stop/start switch rather than a restart but thats fine thanks.
