### ISSUE TITLE
 sensor.solis_power_generation_total is reporting this year's total instead of the sum of all years

### ISSUE THREAD

**Issue by rcourtman** [wills106/homeassistant-solax-modbus#373]
*note - this looks like it's probably an issue with the solis inverter itself as I'm seeing the inverter reporting this number incorrectly. But if there is a workaround to it then it would be great to know. I can always use my meter to provide this info, but unfortunately for me, I recently had to switch my meter as it broke (before I had HA set up) so my new meter started from 0. 

The sensor.solis_power_generation_total entity in our system is reporting the total power generation for this year instead of the sum of all years. 

{'entity_id': 'sensor.solis_power_generation_last_year', 'state': '624', 'unit_of_measurement': 'kWh'}
{'entity_id': 'sensor.solis_power_generation_this_year', 'state': '1099', 'unit_of_measurement': 'kWh'}
{'entity_id': 'sensor.solis_power_generation_total', 'state': '1099', 'unit_of_measurement': 'kWh'}

sensor.solis_power_generation_total I would've thought should be 1,723

Additional Information

sensor.solis_power_generation_last_year and sensor.solis_power_generation_this_year entities are reporting accurate data (when checked against the inverters display).

Solis Hybrid, modbus. 

![image](https://user-images.githubusercontent.com/8825017/229303291-4c160fed-2556-4c96-a103-8539cc34d3ab.png)
![image](https://user-images.githubusercontent.com/8825017/229303306-ba85555d-5deb-48ce-a677-c92c2c760471.png)

Fantastic work by the way on this intergration, it works beautifully.

**Comment by wills106** [comment]
'sensor.solis_power_generation_total' is mapped to 33029
'sensor.solis_power_generation_this_year' is mapped to 33037

The only thing I can think of is that in the firmware 'sensor.solis_power_generation_total' is mapped to 33037 so it's reading the wrong value?

Have you asked Solis if there is a firmware update?

**Comment by rcourtman** [comment]
I'm waiting to hear back, will post a response if/when I get one.

**Comment by alienatedsec** [comment]
@rcourtman what is your model and firmware version at the moment?

**Comment by rcourtman** [comment]
> @rcourtman what is your model and firmware version at the moment?

I believe it's the RHI-(3-6)K-48ES-5G
HMI - 42
DSP - 3F

**Comment by alienatedsec** [comment]
@rcourtman Which exact RHI?

`RHI-6K-48ES-5G` is the 6kWh model

**Comment by rcourtman** [comment]
Update*

The Solis team responded and resolved the issue with my inverter remotely. They simply requested me to plug in the Wifi Logger stick, allowing them to access and fix it. It is uncertain whether it was a firmware problem or just an isolated issue with my device. As a result, I will consider this issue resolved. Thanks!  

![image](https://user-images.githubusercontent.com/8825017/232017779-ae1d7177-225d-40fb-8bf0-09ab7e698e87.png)

Thanks

**Comment by rcourtman** [comment]
> 

The 3.6kW model
