### ISSUE TITLE
[BUG] cannot communicate with inverter via modbus tcp after HA update

### ISSUE THREAD

**Issue by txf-** [wills106/homeassistant-solax-modbus#375]
**Describe the bug**
The plugin does not seem to be able to read the inverters registers.

**Mandatory details**
1. Integration Version: 2023.3.1
2. HA Version: 2023.4.1 and 2023.4.2 (was on 2023.3.2)
3. Inverter: Solax X3 Hybrid gen3
6. Connection Method: modbus tcp

**Detailed Error Log**
Since I updated to the 2023.4.1 release of home assistant, this plugin no longer seems to be able to access the inverter via modbus. Using a separate modbus app I am able to query the inverters registers, so it doesn't appear to be connection issues.

```
Logger: custom_components.solax_modbus.plugin_solax
Source: custom_components/solax_modbus/plugin_solax.py:4502
Integration: SolaX Inverter Modbus ([documentation](https://github.com/wills106/homsassistant-solax-modbus), [issues](https://github.com/wills106/homsassistant-solax-modbus/issues))
First occurred: 11:24:05 AM (4 occurrences)
Last logged: 11:52:44 AM

unrecognized inverter type - serial number : unknown
```

In the system log I get the above error and others related to this like

`SolaX: reading serial number from address 0x300 failed; other address may succeed`

`SolaX: reading serial number from address 0x0 failed; other address may succeed`

and finally this one (only happened once, seems related to restarting HA):
```
Logger: pymodbus.logging
Source: custom_components/solax_modbus/__init__.py:318
Integration: SolaX Inverter Modbus ([documentation](https://github.com/wills106/homsassistant-solax-modbus), [issues](https://github.com/wills106/homsassistant-solax-modbus/issues))
First occurred: 12:06:59 PM (1 occurrences)
Last logged: 12:06:59 PM

Connection to (192.168.1.163, 502) failed: [Errno 104] Connection reset by peer
```

Anything changed in HA that has broken the plugin? I can't really see anything that would. 

Something that I have never seen, I don't know if this expected behaviour, but when clicking an entity, they all seem to say that the integration no longer supplies this entity:
![chrome_8bpHEs6uS6](https://user-images.githubusercontent.com/1192015/230769018-6ffbe2a8-b4f7-4649-8770-0a3ecafedcf8.png)

**Comment by wills106** [comment]
I have just updated from 2023.3.x. to 2023.4.2 without an issue.

I would try and power cycle the Inverter. A couple of users lost connection when they went to 2023.3.x but not sure why it would cause them issues as I didn't experience any.

https://community.home-assistant.io/t/universal-solar-inverter-over-modbus-rs485-tcp-custom-component-growatt-sofar-solax-solis/140143/1077
