### ISSUE TITLE
[BUG] 2023.03.1.23 Solis write issues and sleep mode

### ISSUE THREAD

**Issue by dolce08** [wills106/homeassistant-solax-modbus#387]
Inverter: Solis RHI-6K-48ES-5G
Integration Version: 2023.03.1.23
HA version: 2023.4.6
First 6 digits of serial: 60310
Connection method: LAN

Firstly thank you for the awesome integration. Had a couple of errors flagging for the latest beta. So far none of them seem to impact it’s function, apart from automations for updating registries don't always work.

1. [custom_components.solax_modbus] assuming sleep mode - slowing down by factor 10. As I have a hybrid system I would not expect sleep mode to be active. Also this happens during the day so does not seem to be related to battery SOC.
2. [custom_components.solax_modbus] Solis cannot read holding registers at device 1 position 0xa7ff. 
3. ERROR (MainThread) [pymodbus.logging] General exception: unpack requires a buffer of 4 bytes
    ERROR (MainThread) [pymodbus.logging] Modbus IO exception Modbus Error: [Input/Output] Unable to decode request

For 3. Manually changing the ‘Energy storage control switch’ works but if changed by an automation it doesn’t always stick, and changes back to previous mode.

**Comment by wills106** [comment]
> 1. [custom_components.solax_modbus] assuming sleep mode - slowing down by factor 10. As I have a hybrid system I would not expect sleep mode to be active. Also this happens during the day so does not seem to be related to battery SOC.

Unfortunately the Solis Inverters aren't the most reliable at communicating.
There are a few "sleep mode" implemented in plugin_solis this is to prevent the Integration from returning 0 between other values.
For example the Battery SOC wouldn't normally drop from 90% to 0% and back to 90%, so when it looses communications that that register it holds it at 80% until the next valid response.



> For 3. Manually changing the ‘Energy storage control switch’ works but if changed by an automation it doesn’t always stick, and changes back to previous mode.

Are you making sure your Automation exactly matches the options given?

https://github.com/wills106/homeassistant-solax-modbus/blob/df4e1af1b76e3f2b3e3e89bc85bef2f1236b1fc1/custom_components/solax_modbus/plugin_solis.py#L679-L693

I don't know if it would work or not? But you could try sending the number values instead?

**Comment by wills106** [comment]
> 1. [custom_components.solax_modbus] assuming sleep mode - slowing down by factor 10. As I have a hybrid system I would not expect sleep mode to be active. Also this happens during the day so does not seem to be related to battery SOC.

This should be resolved in [2023.05.2b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.05.2b1)

Although there is further enhancements in newer beta releases.
