### ISSUE TITLE
Solax Modbus: Unable to set values

### ISSUE THREAD

**Issue by otava5** [wills106/homeassistant-solax-modbus#396]
**Describe the bug**
After the remote firmware update of the inverter, the values cannot be set. Always after setting, the value will be returned.
Ejecting, reinserting dongle/restarting router/restarting HA didn't help

**Mandatory details**
1. Integration Version: 2023.05.1
2. HA Version: 2023.1.5
3. Inverter Brand: Solax X3 G4 Hybrid
4. Inventer Version: 28 / 30
5. First 6 digits of Serial: H34C10
6. Connection Method: Wifi Dongle 3.0 black

![image](https://user-images.githubusercontent.com/26667859/236562987-5ff92e95-8a9a-4bca-ac8b-fb8329043726.png)

**Comment by wills106** [comment]
Have you tried "Unlocking" the Inverter as mention just before the known issues section of the [Readme](https://github.com/wills106/homeassistant-solax-modbus#known-issues)?

**Comment by otava5** [comment]
Thank you sir it helped ;-)
Can it be locked back??

**Comment by wills106** [comment]
Not at the moment.
I can create a "Select" so you can choose between the two Unlocked modes and Locked.

**Comment by otava5** [comment]
It would be great...
Thanks for the advice, we can close...

**Comment by wills106** [comment]
I have added select "Lock State" into the new Beta release [2023.05.2b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.05.2b1)

**Comment by wills106** [comment]
Closing down as [2023.05.2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.05.2) addresses this issue.
