### ISSUE TITLE
[BUG] Bad items and Divions needs to be higher for growatt hybrid sph3600

### ISSUE THREAD

**Issue by fontexD** [wills106/homeassistant-solax-modbus#398]
grid power seems to be wrong, should be dividied by 10 more

https://ibb.co/mhkCHkw

**Comment by wills106** [comment]
Just released [2023.05.2b3](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.05.2b3) that should correct "Total House Load".

**Comment by fontexD** [comment]
awesome!

i tried to fix it myself by changing the scale but after i changed the number adding a  0 it totaly failed to load the integration

what did u change ? if u can show :)

**Comment by wills106** [comment]
https://github.com/wills106/homeassistant-solax-modbus/commit/86a87fe23188951fa0c11beacb4f717862c3b2f4#diff-046c299de9c82c23a2b80aab480e4764b6d768dbf26f783a29263fda92774c37R1637
