### ISSUE TITLE
Solax error unrecognized inverter type - serial number : MC210TI839XXXX

### ISSUE THREAD

**Issue by KestasG** [wills106/homeassistant-solax-modbus#404]
Setup integration on home assistant and getting errors:
```
This error originated from a custom integration.

Logger: custom_components.solax_modbus.plugin_solax
Source: custom_components/solax_modbus/plugin_solax.py:4619`
Integration: SolaX Inverter Modbus (documentation, issues)
First occurred: 5:47:18 PM (2 occurrences)
Last logged: 5:50:31 PM

SolaX: reading serial number from address 0x0 failed; other address may succeed


This error originated from a custom integration.

Logger: custom_components.solax_modbus.plugin_solax
Source: custom_components/solax_modbus/plugin_solax.py:4684
Integration: SolaX Inverter Modbus (documentation, issues)
First occurred: 5:47:19 PM (2 occurrences)
Last logged: 5:50:31 PM

unrecognized inverter type - serial number : MC210TI839XXXX
``` 
(last for digits replaced with X)

Inverter Solax X3-MIC-G2, connected by Waveshare RS232/485/422 TO POE ETH (B)

**Comment by KestasG** [comment]
After adding serial number to `determineInverterType()` it started working, all values got populated except `Measured Power L1,L2,L3`.

**Comment by wills106** [comment]
Did you include the X3 at the end?
Should look like:

```
elif seriesnumber.startswith('MC210T'):  invertertype = MIC | GEN2 | X3
```

**Comment by KestasG** [comment]
Yes, I did. It gets other metrics for all phases, but not power:
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/7732736/660e8c3e-46a0-477e-a1e4-9b0d42d1e9d6)

**Comment by lcintrat** [comment]
Hi,

The inverter is recognized by the integration, but I have the same issue regarding the `Measured Power L1,L2,L3` sensors, they report 0.
All other sensors are OK as shown by @KestasG 

HA version: `2023.7.1`
Integration version: `2023.06.8`
Inverter: `Solax X3-MIC G2`
Inverter S/N: `MC210T`
Interface: [RS485 / USB adapter - FT232RL](https://www.amazon.fr/dp/B073M68NGF)

**Comment by wills106** [comment]
I have just released [2023.08.4b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.08.4b1) I have moved "Measured Power L1,L2,L3" to a different set of registers which could provide the values? I have also added in the extra registers for the Modbus Power Meter.

**Comment by wills106** [comment]
@KestasG @lcintrat Have either of you managed to test out the Beta?
Just wondering if I can release it as a stable release or not?

**Comment by KestasG** [comment]
Installed the beta, but the sun is already down. Will check the readings in the morning.

**Comment by KestasG** [comment]
Unfortunately, L1, L2, L3 power is still zero.
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/7732736/0db64973-0a8d-42f9-890c-8c31028767a5)

**Comment by wills106** [comment]
Might be a daft question but do you actually have CT Clamps or a Modbus Power Meter connected to your Inverter?
Also did you restart HA after updating through HACS?

The reason being is I have feed back from another user who has working L2 and L3, but having issues with L1 at the moment.

**Comment by lcintrat** [comment]
I have the same results, beta is correctly loaded
```
2023-08-17 08:03:01.758 INFO (MainThread) [custom_components.solax_modbus.sensor] Starting new block at 0x704 
2023-08-17 08:03:01.758 INFO (MainThread) [custom_components.solax_modbus.sensor] adding register 0x704 measured_power_l1 to block with start 0x704
2023-08-17 08:03:01.758 INFO (MainThread) [custom_components.solax_modbus.sensor] adding register 0x706 measured_power_l2 to block with start 0x704
2023-08-17 08:03:01.758 INFO (MainThread) [custom_components.solax_modbus.sensor] adding register 0x708 measured_power_l3 to block with start 0x704
```
But measured values are still 0.

No power meter nor CT clamps connected to the inverter.

**Comment by wills106** [comment]
If you don't have CT Clamps or a Modbus Meter connected these sensors won't return anything.

**Comment by lcintrat** [comment]
Oh OK
Thank you for your help!

**Comment by wills106** [comment]
@KestasG do you have CT Clamp's or a Modbus Power Meter attached to your Inverter?
If you don't I'll close this issue down as these Measured Power sensors rely on them.

**Comment by KestasG** [comment]
I dont have power meter connected to inverter. I'm just wodering how solax show separate phase power on their web site.

**Comment by cewbdex** [comment]
That's probably just power it sends to you. This can be closed then?
