### ISSUE TITLE
[BUG] Solis plugin. Incorrect scale for House Load Total

### ISSUE THREAD

**Issue by wawyed** [wills106/homeassistant-solax-modbus#406]
Hi, it looks like the scale of House Load Total should be 1 and not 0.1.

I'm using Solid Hybrid S5-EH1P5K-L and latest Beta.3 version.

**Comment by wills106** [comment]
@alienatedsec are you able to confirm if your House Load Total seems to be out?

If it's not it might be model specific.

**Comment by alienatedsec** [comment]
@wills106 Correct - should be 1 and not 0.1

The latest from the Android app - more info on where this data resides at the below discussion:
https://github.com/alienatedsec/solis-ha-modbus-cloud/discussions/9#discussioncomment-5630547

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/73167064/416f8cbb-602b-47b1-8965-79e7cddb7537)
