### ISSUE TITLE
[BUG] solax_export_control_user_limit entities incorrect by 10x

### ISSUE THREAD

**Issue by M0LTE** [wills106/homeassistant-solax-modbus#418]
**Describe the bug**
SolaX sensor.solax_export_control_user_limit and number.solax_export_control_user_limit are wrong by a factor of 10.

If I set the latter in Home Assistant to 5000W, the setting in the SolaX app is actually 500W.

If I set the setting in the SolaX app to, say, 6000W, the value of both entities in HA changes to 60KW.

(This also explains my recent difficulties with low export power, since I was setting 9600W (the maximum) in HA and that was actually setting 960W in the inverter.)

**Mandatory details**
1. Integration Version: 2023.05.2b4
2. HA Version: 2023.5.3
3. Inverter Brand: SolaX
4. Plugin Used: SolaX Inverter Modbus
5. First 6 digits of Serial: H4502T
6. Connection Method: RS485-ethernet adapter

**Comment by wills106** [comment]
Are you on a really old firmware? This was possibly resolved through a firmware upgrade #58

**Comment by M0LTE** [comment]
I don't believe it's ever been updated... 
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/37816024/af30f4c0-9ffd-4d74-a7f8-11179a0977a9)

**Comment by M0LTE** [comment]
In that thread I read:

> I also recently allowed my Solax installer to perform a sofware upgrade, **I think the problem was solved already before that upgrade.**

Emphasis mine - I don't think the firmware upgrade is what solved it for @infradom

**Comment by BombusAlpinus** [comment]
Hi got the same issue with an x3 g4 displaying the value diveded by 10.
I've configured 4000W and the HA integration shows 400W.
As far as i know i'm on the latest fw because we checked it when we took the inverter online.
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/28042236/41364199-cda1-407e-b0a8-e25124bda159)
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/28042236/cdb21b8d-9a1f-49cf-9130-2a494e1fcf30)

The inverter itself and e.g. the solax app showing the correct value of 4000w .

![Screenshot_2023-05-26-09-23-00-309-edit_com solaxcloud starter](https://github.com/wills106/homeassistant-solax-modbus/assets/28042236/dd8ceead-8ffc-4ddb-9925-08ba0f601777)

Thanks!

**Comment by wills106** [comment]
I might need to break this sensor down into model specific ones? As my Gen3 X1 is reading correctly at 6000w in both the Integration and cloud.

I'll also have a look into getting these firmware numbers to match what's on the LCD on the Inverter.

**Comment by M0LTE** [comment]
Sounds good.

Please remember it is both the sensor (display) and the number (set) entity
at fault, at least in my case.

**Comment by BombusAlpinus** [comment]
just had a look at my inverters lcd display... but was not able to find the current firmwareversion ...

> I might need to break this sensor down into model specific ones? As my Gen3 X1 is reading correctly at 6000w in both the Integration and cloud.
> 
> I'll also have a look into getting these firmware numbers to match what's on the LCD on the Inverter.

**Comment by infradom** [comment]
I have these firmware versions and the scaling is correct on my X3 Gen4:
<img width="363" alt="image" src="https://github.com/wills106/homeassistant-solax-modbus/assets/11804014/157d7430-c8a8-4d62-91f5-9beb85ee1d35">

**Comment by infradom** [comment]
We did create read_scale_exceptions=EXPORT_LIMIT_SCALE_EXCEPTIONS for some serial number prefixes.
I do fear that not only the serial number determines the behavior, but also one of the version numbers.
Either this parameter or the 'scale' parameter must be adjusted for some models,version combinations.
A quick ugly fix would be to introduce a 'pseudo entity' EXPORT_CONTROL_CORRECTION_FACTOR'  that lets the user adjust the read_scale (or the scale)

**Comment by M0LTE** [comment]
Hey, any further thoughts on this issue?

**Comment by M0LTE** [comment]
Going live with export in around 2 weeks, may I sponsor this bug being fixed please?

**Comment by M0LTE** [comment]
Great, thanks. My position is that I need the software for economic
reasons, and I’m willing to pay for it.

Cheers
Tom

**Comment by infradom** [comment]
Is it possible for you to edit solax_plugin.py and modify following section (line for your prefix added)

```
EXPORT_LIMIT_SCALE_EXCEPTIONS = [
    ('H4', 10 ),     # assuming all Gen4s
    ('H34', 10),     # assuming all Gen4s 
    ('H4502T', 10),  # more specific entry comes last and wins 
#    ('H1E', 10 ), # assuming all Gen4s
]
```

The generic 'H4' statement should cover your inverter, but it is completely unclear why this does not work for you.
Alternatively, you coud modify the value 10 to 1 or even 0.1, just to help me understand what happens

Once we have a good understanding, we can find a final solution.

**Comment by infradom** [comment]
@MOLTE, @BombusAlpinus : see edits to previous post

**Comment by M0LTE** [comment]
@infradom Looking now - but my HA is in a Docker container so it's taking me a little while to access solax_plugin.py

**Comment by infradom** [comment]
> @infradom Looking now - but my HA is in a Docker container so it's taking me a little while to access solax_plugin.py

I have issued a PR request to @wills106 . This contains this change and some other preparations 
So  you can wait for this  ...

**Comment by infradom** [comment]
I believe that for your model, the scale exception should be = 1 instead of 10
I would like to make this dependent on the software version number instead of serial number, but I want your feedback first ...

**Comment by M0LTE** [comment]
So I should wait for a beta release? Or continue to try to locate and edit solax_plugin.py?

**Comment by infradom** [comment]
Up to you, I wait for feedback from @wills106 as I prefer not to make any releases myself

**Comment by infradom** [comment]
Making changes in a docker container can be difficult ... Awaiting a beta might make sense

**Comment by M0LTE** [comment]
I've located it - it's in the config folder on the host which is mounted into the container, trying it now

**Comment by M0LTE** [comment]
This:

```
EXPORT_LIMIT_SCALE_EXCEPTIONS = [
    ('H4', 10 ),     # assuming all Gen4s
    ('H34', 10),     # assuming all Gen4s 
    ('H4502T', 1),  # more specific entry comes last and wins 
#    ('H1E', 10 ), # assuming all Gen4s
]
```

results in the correct behaviour for my inverter. 🏆

**Comment by infradom** [comment]
That is also the content of my PR (with some other preparations to make this cleaner)

**Comment by wills106** [comment]
Just released the Beta [2023.06.1b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.06.1b1)

**Comment by M0LTE** [comment]
@wills106 confirmed still working as expected in 2023.06.1b1, thank you both

**Comment by M0LTE** [comment]
NB for future readers, in a Home Assistant in Docker scenario, `plugin_solax.py` is in `.docker-conf/homeassistant/config/custom_components/solax_modbus`

**Comment by BombusAlpinus** [comment]
> @M0LTE Is it possible for you to edit solax_plugin.py and modify following section (line for your prefix added)
> 
> ```
> EXPORT_LIMIT_SCALE_EXCEPTIONS = [
>     ('H4', 10 ),     # assuming all Gen4s
>     ('H34', 10),     # assuming all Gen4s 
>     ('H4502T', 1),  # more specific entry comes last and wins 
> #    ('H1E', 10 ), # assuming all Gen4s
> ]
> ```
> 
> The generic 'H4' statement should cover your inverter, but it is completely unclear why this does not work for you. Alternatively, you coud modify the value 10 to 1 or even 0.1, just to help me understand what happens
> 
> Example:
> 
> ```
> EXPORT_LIMIT_SCALE_EXCEPTIONS = [
>     ('H4', 10 ),     # assuming all Gen4s
>     ('H34', 10),     # assuming all Gen4s 
>     ('H4502T', 10 ),  # more specific entry comes last and wins 
> #    ('H1E', 10 ), # assuming all Gen4s
> ]
> ```
> 
> **you might even have to set the value to 100** for your prefix (but that will probable worsen the situation)
> 
> Once we have a good understanding, we can find a final solution.
> 
> @BombusAlpinus : your situation seems to be the opposite, so I would need your serial number prefix so that we can add it with factor 10

@M0LTE  in my case the first 4 digits of my inverter serial number are: H3UE

**Comment by infradom** [comment]
> in my case the first 4 digits of my inverter serial number are: H3UE (X3-Hybrid-G3)
@BombusAlpinus : could you give us a couple of more digits, I would like to avoid breaking things for other users as we believe the behavior may not only depend on serial number but also on software version
The serial number hack must be seen as a quick fix until we can make it dependent on software version (or a configuration variable)

**Comment by BombusAlpinus** [comment]
> > in my case the first 4 digits of my inverter serial number are: H3UE (X3-Hybrid-G3)
> > @BombusAlpinus : could you give us a couple of more digits, I would like to avoid breaking things for other users as we believe the behavior may not only depend on serial number but also on software version
> > The serial number hack must be seen as a quick fix until we can make it dependent on software version (or a configuration variable)

@infradom how much digits would you need? do you have another way for me instead of posting it public?

**Comment by wills106** [comment]
If you look in the code we are using more than the first 4 digits anyway as they are used to further breakdown sub models

https://github.com/wills106/homeassistant-solax-modbus/blob/6500e6acd97c59efc3ad1c6b260a3329c7367336/custom_components/solax_modbus/plugin_solax.py#L332-L335

At the moment we don't have enough info to determine if this bug is limited to certain sub models or to firmware versions.

**Comment by infradom** [comment]
@BombusAlpinus We are almost ready with another change that introduces a scaling factor for export_control_user_limit.
Once this change is released, there is no more need to know your serial number prefix.
This configuration entity will be called config_export_control_limit_reedscale and will be disabled by default. In your case, you will have to enable it, and set the value to 10
So if you can wait a couple of days, this will be an alternative solution

**Comment by BombusAlpinus** [comment]
> @BombusAlpinus We are almost ready with another change that introduces a scaling factor for export_control_user_limit. Once this change is released, there is no more need to know your serial number prefix. This configuration entity will be called config_export_control_limit_reedscale and will be disabled by default. In your case, you will have to enable it, and set the value to 10 So if you can wait a couple of days, this will be an alternative solution

@infradom i have no porblem waiting for the fix... so take your time ;) thanks for working on it!

**Comment by infradom** [comment]
@BombusAlpinus : In this case, you wont need to enable the new config_export_control_limit_readscale. Version 2023.06.1 should solve this without any action.

**Comment by hthaller** [comment]
For my Solax X3 Ultra inverter the modbus plugin shows wrong values for "solax_export_control_user_limit" too.

Value in HA/modbus plugin: 1000W
Value in LCD screen on inverter: 10000W

Here is my configuration:

- HA version: 2025.3.2
- Inverter Brand: SolaX X3 Ultra 25K
- Plugin Used: SolaX Inverter Modbus
- First 6 digits of Serial: H3BF25
- Connection Method: RS485-ethernet adapter
