### ISSUE TITLE
Unable to change backflow power setting [BUG] 

### ISSUE THREAD

**Issue by J14111** [wills106/homeassistant-solax-modbus#427]
**Describe the bug**

**Mandatory details**
1. Integration Version: 2023.06.1b1
2. HA Version: 
3. Inverter Brand: Solis
4. Plugin Used: Solis
5. First 6 digits of Serial:
6. Connection Method: TCP

This was working fine but since a recent update I am unable to change the backflow power setting, if I try to change it I see this in the GUI:

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/120409046/c2ec7a1b-b2b5-4795-a96e-b19d24bacea7)

I have tried removing and reinstalling the intergration

**Comment by J14111** [comment]
This is still the same in the latest update, is anyone able to have a look please?

**Comment by jojoBzh** [comment]
Hello,
I had the same problem but resolved now:
Just have a look to this : https://github.com/wills106/homeassistant-solax-modbus/issues/637
Regards
#637

**Comment by wills106** [comment]
Just checked and "Backflow Power" has been updated to have the scale set at 100.
Can this be closed down now?

**Comment by J14111** [comment]
Still having the same issue on the latest beta

<img width="416" alt="image" src="https://github.com/wills106/homeassistant-solax-modbus/assets/120409046/6c3a977b-3cec-4bca-9966-bc38d1507e6f">

**Comment by wills106** [comment]
I miss read and the scale was still at 0.01 and not the 100 mentioned in #637 
I have just released [2024.02.3b4](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.02.3b4) with the change.

**Comment by J14111** [comment]
That seems to have fixed it thanks!
