### ISSUE TITLE
Sofar Solar HYD 15KTL-3P RS485/Modbus connection could see few entities only

### ISSUE THREAD

**Issue by ppiwowar** [wills106/homeassistant-solax-modbus#443]
**Describe the bug**

**Mandatory details**
1. Integration Version:
2. HA Version: Home Assistant 2023.6.1, Operating System 10.2
3. Inverter Brand: Sofar Solar HYD 15KTL-3P
4. Plugin Used: 2023.06.8
5. First 6 digits of Serial: unknown as logger LSE-3 doesn't work
6. Connection Method:

HA(RPI4-8GB) is connected (LAN Ethernet) through Adapter (Ethernet<->RS486) directly to Sofar RS485 port.
I see only temperature entities' values. The others are 'unknown'. 

![Screenshot 2023-06-14 at 15-59-12 Settings – Home Assistant](https://github.com/wills106/homeassistant-solax-modbus/assets/6585704/fc8c8877-2ad9-4918-965e-bc1f00e44b42)
![Screenshot 2023-06-14 at 16-00-13 Settings – Home Assistant](https://github.com/wills106/homeassistant-solax-modbus/assets/6585704/5a50f695-26cc-48af-b876-d3b7e591a382)

**Comment by wills106** [comment]
You should have a error message in your HA log listing your Serial as an unrecognised Inverter.
What's the first 4 digits that it returns?

**Comment by ppiwowar** [comment]
This all I have in the log file after a fresh ha restart:

2023-06-14 17:03:03.631 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration solax_modbus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-14 17:03:03.633 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration mobile_alerts which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-14 17:03:03.634 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

I am not sure, I have a communication problem with Sofar, as I see some data ....?

**Comment by ppiwowar** [comment]
Additional info:
Connection Method: ModBus TCP using WaveShare RS485 TO ETH (B)

**Comment by ppiwowar** [comment]
It took me the entire night. It was all about timeouts on WaveShare RS485 TO ETH (B).
Wills106, your integration is fine. thank you!
Closing, .... but still observing the stability of data flow.

**Comment by wills106** [comment]
If you still need to make further changes can you let me know and I'll update the wiki.

Did you also see the note in the wiki:

In "More Advanced Aettings...",
- Sofar Solar set Modbus Gateway Type to "Auto query storage type"

**Comment by ppiwowar** [comment]
Thanks. I do have the DIN rail mounted mode, but I have no Windows .... so I couldn't use vircom. Shooting blindly I modified:
- Enable multi-host = yes
- Rs485 conflict time gap = 50ms
It started to work then, but I am still testing ....
I am really newbie for HA - where to check for these  "blocking call inside the event loop", pls ?

**Comment by wills106** [comment]
You should only get "blocking call inside the event loop" when using a RS485-USB adaptor.
It doesn't affect Modbus TCP

**Comment by wills106** [comment]
Did you get this working correctly?
Just wondering if I can close this issue down?

**Comment by ppiwowar** [comment]
Let me test it for a week or two. From time to time I have a strange thing - PV Energy and Export Energy meters go backwards?! Pls see HA screen dump. Also changes of entity values come late. Sometimes for some entities I need to wait for 10-20 minutes.Pozdrawiam/Regards, PawelWiadomość napisana przez wills106 ***@***.***> w dniu 31.07.2023, o godz. 10:35:﻿
Did you get this working correctly?
Just wondering if I can close this issue down?

**Comment by wills106** [comment]
I think some of the setting you need to set can only be configured through the Vircom tool. So it might be worth setting up a VM for Windows or taking the Waveshare round to a friends house running Windows so you can check all of the settings correctly.

**Comment by wills106** [comment]
Can this be closed down now?
Were you able to setup your Waveshare with the Vircom tool?

**Comment by ppiwowar** [comment]
Although I have not been able to setup the converter with Vircom, please do close the issue.Pozdrawiam/Regards, PawelWiadomość napisana przez wills106 ***@***.***> w dniu 16.08.2023, o godz. 19:43:﻿
Can this be closed down now?
Were you able to setup your Waveshare with the Vircom tool?
