### ISSUE TITLE
[BUG] Solax Mic X3 Gen 2 8.8K supported but not recognised

### ISSUE THREAD

**Issue by the-real-mcarn** [wills106/homeassistant-solax-modbus#458]
**Describe the bug**
Solax Mic X3 Gen 2 8.8K (serial no. MC208T********) is not listed in the serial number list, causing an unrecognised inverter error while it is compatible with the plugin. Adding the following line to the if else tree in the `determineInverterType` function in `plugin_solax.py` resolves the issue, after which data reading works fine. 

```py
        elif seriesnumber.startswith('MC208T'):  invertertype = MIC | GEN2 | X3 # MIC X3 8.8K
```

**Mandatory details**
1. Integration Version: 2023.06.8
2. HA Version: 2023.6.2
3. Inverter Brand: Solax
4. Plugin Used: SolaX Inverter Modbus
5. First 6 digits of Serial: MC208T
6. Connection Method: RS485 using ZLAN TCP Bridge

**Comment by wills106** [comment]
Closing as released [2023.07.3](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.07.3)
