### ISSUE TITLE
[FR] - Improve data for Growatt Inverter's

### ISSUE THREAD

**Issue by choenig** [wills106/homeassistant-solax-modbus#471]
Hi,

I don't know if this should rather be a discussion or an issue, I just post it here as I guess there are more people reading here :)

I have successfully integrated my Growatt SPH 10000TL3 BH-UP Inverter.

The serial starts with 'YA1' so i added
```
elif seriesnumber.startswith('YA1'):  invertertype = HYBRID | GEN | X3 # Hybrid SPH 4kW - 10kW 3P TL3 BH-UP
```
to get it running.

Now I already improved some of the configuration values in `plugin_growatt.py` to enhance descriptions, scales and I also added some more registers. I also reduced the `block_size` to 64, that fixed some of the received registers.

In any case I'm willing to share my improvements, but it would be really nice to find other users of the SPH TL3 BH-UP inverters to check some values, that look really broken on my setup.

Br
Christian

**Comment by wills106** [comment]
Feel free to submit any improvements either through comment's or PR's.

Unfortunately the Growatt Inverters are a little unloved at the moment as there aren't many users.
Also the growatt_plugin hasn't been fully setup for PV only Inverters which I need to work on.

**Comment by Hans-chr2** [comment]
Hi Christian

What changes did you make ? 
last i tried the mapping for the TL3-BH-UP were wrong.

I have a same inverter as you, just 8kW model, if you have done some mapping i could verify some of them on mine.

**Comment by wills106** [comment]
Just released [2023.07.2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.07.2) which has Firmware starting 'YA1'

**Comment by Hans-chr2** [comment]
I finds the inverter now, nut the mapping seems to be off. 
![billede](https://github.com/wills106/homeassistant-solax-modbus/assets/133807567/6af9df35-2f8d-4b00-b671-3e0adc98e61b)

**Comment by wills106** [comment]
This is the first time a 3Phase Inverter using this set of registers has been used on the Integration.
I'll need to go back over the documents.

**Comment by Hans-chr2** [comment]
I don't know if this helps ? 

 sensors:

  - name: "Fault code"
    unique_id: '0a123585'
    scan_interval: 15
    slave: 1
    address: 0
    data_type: int16
    scale: 1
    precision: 1
    input_type: input
    device_class: monetary

# 1 = checking
# 5 = ?
# 6 = ? OK 
# 9 = Battery open 


#GENEREL INFO
  - name: "Inverter_effekt_sum"
    unique_id: '0a1235852'
    scan_interval: 5
    slave: 1
    address: 35
    state_class: measurement
    unit_of_measurement: "W"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: power

  - name: "Inverter_frekvens"
    unique_id: '0a'
    scan_interval: 7
    slave: 1
    address: 37
    state_class: measurement
    unit_of_measurement: "Hz"
    data_type: int16
    scale: 0.01
    precision: 1
    input_type: input
    device_class: frequency

  - name: "Inverter_temperatur"
    unique_id: '0a695'
    scan_interval: 5
    slave: 1
    address: 93
    state_class: measurement
    unit_of_measurement: "°C"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: temperature



#inverter total energi idag
  - name: "Inverter_energi_idag"
    unique_id: '0a12358526541'
    scan_interval: 60
    slave: 1
    address: 53
    state_class: total
    unit_of_measurement: "kWh"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: energy

  - name: "Inverter_energi_total"
    unique_id: '0a123585541'
    scan_interval: 60
    slave: 1
    address: 55
    state_class: total
    unit_of_measurement: "kWh"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: energy


##SOL INFO###
  - name: "Inverter_PV1"
    unique_id: '0a16518'
    scan_interval: 8
    slave: 1
    address: 3
    state_class: measurement
    unit_of_measurement: "V"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: voltage

  - name: "Inverter_PC1"
    unique_id: '0a54619'
    scan_interval: 8
    slave: 1
    address: 4
    state_class: measurement
    unit_of_measurement: "A"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: current

  - name: "Inverter_PV1_effekt"
    unique_id: '0a12358521'
    scan_interval: 5
    slave: 1
    address: 5
    state_class: measurement
    unit_of_measurement: "W"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: power

  - name: "Inverter_PV1_idag_effekt"
    unique_id: '0a123585526541'
    scan_interval: 60
    slave: 1
    address: 59
    state_class: total_increasing
    unit_of_measurement: "kWh"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: energy

  - name: "Inverter_PV1_total_effekt"
    unique_id: '0a1235852651'
    scan_interval: 60
    slave: 1
    address: 61
    state_class: total
    unit_of_measurement: "kWh"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: energy





##FASER##
  - name: "Inverter_Spænding_L1"
    unique_id: '0a1'
    scan_interval: 5
    slave: 1
    address: 38
    state_class: measurement
    unit_of_measurement: "V"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: voltage

  - name: "Inverter_Strøm_L1"
    unique_id: '0a62'
    scan_interval: 5
    slave: 1
    address: 39
    state_class: measurement
    unit_of_measurement: "A"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: current

  - name: "Inverter_effekt_L1"
    unique_id: '0a12358144752651'
    scan_interval: 5
    slave: 1
    address: 40
    state_class: measurement
    unit_of_measurement: "W"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: power

  - name: "Inverter_Spænding L2"
    unique_id: '0a2'
    scan_interval: 5
    slave: 1
    address: 42
    state_class: measurement
    unit_of_measurement: "V"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: voltage

  - name: "Inverter_Strøm L2"
    unique_id: '0a25'
    scan_interval: 5
    slave: 1
    address: 43
    state_class: measurement
    unit_of_measurement: "A"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: current

  - name: "Inverter_effekt_L2"
    unique_id: '0a1562'
    scan_interval: 9
    slave: 1
    address: 44
    state_class: measurement
    unit_of_measurement: "W"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: power

  - name: "Inverter_Spænding L3"
    unique_id: '0a3'
    scan_interval: 9
    slave: 1
    address: 46
    state_class: measurement
    unit_of_measurement: "V"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: voltage

  - name: "Inverter_Strøm L3"
    unique_id: '0a26'
    scan_interval: 9
    slave: 1
    address: 47
    state_class: measurement
    unit_of_measurement: "A"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: current

  - name: "Inverter_effekt_L3"
    unique_id: '0a156252'
    scan_interval: 9
    slave: 1
    address: 48
    state_class: measurement
    unit_of_measurement: "W"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: power


##Batteri
  - name: "Batteri_afladning"
    unique_id: '0a12356'
    scan_interval: 5
    slave: 1
    address: 1009
    state_class: measurement
    unit_of_measurement: "W"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: power

  - name: "Batteri_opladning"
    unique_id: '0a12378'
    scan_interval: 5
    slave: 1
    address: 1011
    state_class: measurement
    unit_of_measurement: "W"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: power

  - name: "Batteri_Spænding"
    unique_id: '0a12'
    scan_interval: 5
    slave: 1
    address: 1013
    state_class: measurement
    unit_of_measurement: "V"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: voltage

  - name: "Batteri SOC"
    unique_id: '0a27'
    scan_interval: 5
    slave: 1
    address: 1014
    state_class: measurement
    unit_of_measurement: "%"
    data_type: int16
    scale: 1
    precision: 1
    input_type: input
    device_class: battery

  - name: "ACPowerToUser"
    unique_id: '0a1237568'
    scan_interval: 5
    slave: 1
    address: 1015
    state_class: measurement
    unit_of_measurement: "W"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: power

  - name: "ACPowerToUser_Total"
    unique_id: '0a12375689'
    scan_interval: 5
    slave: 1
    address: 1021
    state_class: measurement
    unit_of_measurement: "W"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: power

  - name: "ACPowerToGrid"
    unique_id: '0a1237568569'
    scan_interval: 5
    slave: 1
    address: 1023
    state_class: measurement
    unit_of_measurement: "W"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: power

  - name: "ACPowerToGrid_total"
    unique_id: '0a1237564528569'
    scan_interval: 5
    slave: 1
    address: 1029
    state_class: measurement
    unit_of_measurement: "W"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: power

  - name: "INVPowerToLocalLoad"
    unique_id: '0a1237564f'
    scan_interval: 5
    slave: 1
    address: 1031
    state_class: measurement
    unit_of_measurement: "W"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: power

  - name: "INVPowerToLocalLoadTotal"
    unique_id: '0a1237564fd'
    scan_interval: 5
    slave: 1
    address: 1037
    state_class: measurement
    unit_of_measurement: "W"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: power

  - name: "EnergyToUserToday"
    unique_id: '0a1237564fdd'
    scan_interval: 60
    slave: 1
    address: 1044
    state_class: total_increasing
    unit_of_measurement: "kWh"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: energy

  - name: "EnergyToUserTotal"
    unique_id: '0a1237564fdgd'
    scan_interval: 60
    slave: 1
    address: 1046
    state_class: total
    unit_of_measurement: "kWh"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: energy

  - name: "EnergyToGridToday"
    unique_id: '0a1237qwt564fdgd'
    scan_interval: 60
    slave: 1
    address: 1048
    state_class: total_increasing
    unit_of_measurement: "kWh"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: energy

  - name: "EnergyToGridTotal"
    unique_id: '0a1237564ffdsdgd'
    scan_interval: 60
    slave: 1
    address: 1050
    state_class: total_increasing
    unit_of_measurement: "kWh"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: energy

  - name: "DischargeEnergyToday"
    unique_id: '0a12337564fdgdfd'
    scan_interval: 60
    slave: 1
    address: 1052
    state_class: total_increasing
    unit_of_measurement: "kWh"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: energy

  - name: "DischargeEnergyTotal"
    unique_id: '0a1237564f5dgdfd'
    scan_interval: 60
    slave: 1
    address: 1054
    state_class: total_increasing
    unit_of_measurement: "kWh"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: energy

  - name: "ChargeEnergyToday"
    unique_id: '0a1237564fedg7dfd'
    scan_interval: 60
    slave: 1
    address: 1056
    state_class: total_increasing
    unit_of_measurement: "kWh"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: energy

  - name: "ChargeEnergyTotal"
    unique_id: '0a1237564fdg7dfd'
    scan_interval: 60
    slave: 1
    address: 1058
    state_class: total_increasing
    unit_of_measurement: "kWh"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: energy


  - name: "LocalLoadEnergyToday"
    unique_id: '0a1237564dfd'
    scan_interval: 10
    slave: 1
    address: 1060
    state_class: total_increasing
    unit_of_measurement: "kWh"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: energy

  - name: "LocalLoadEnergyTotal"
    unique_id: '0a1237564fdg7d'
    scan_interval: 10
    slave: 1
    address: 1062
    state_class: total_increasing
    unit_of_measurement: "kWh"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: energy


############################ EPS information
  - name: "EPS_frekvens"
    unique_id: '0a256'
    scan_interval: 15
    slave: 1
    address: 1067
    state_class: measurement
    unit_of_measurement: "Hz"
    data_type: int16
    scale: 0.01
    precision: 1
    input_type: input
    device_class: frequency

  - name: "EPS_load"
    unique_id: '0a25985'
    scan_interval: 15
    slave: 1
    address: 1080
    state_class: measurement
    unit_of_measurement: "%"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: battery

################################ L1 #########################

  - name: "EPS_L1_V"
    unique_id: '0a134'
    scan_interval: 15
    slave: 1
    address: 1068
    state_class: measurement
    unit_of_measurement: "V"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: voltage



  - name: "EPS_L1_A"
    unique_id: '0a278'
    scan_interval: 15
    slave: 1
    address: 1069
    state_class: measurement
    unit_of_measurement: "A"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: current

  - name: "EPS_L1_VA"
    unique_id: '0a1237564528'
    scan_interval: 15
    slave: 1
    address: 1070
    state_class: measurement
    unit_of_measurement: "VA"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: apparent_power

################################ L2 #########################

  - name: "EPS_L2_V"
    unique_id: '0a135'
    scan_interval: 6
    slave: 1
    address: 1072
    state_class: measurement
    unit_of_measurement: "V"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: voltage


  - name: "EPS_L2_A"
    unique_id: '0a279'
    scan_interval: 6
    slave: 1
    address: 1073
    state_class: measurement
    unit_of_measurement: "A"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: current

  - name: "EPS_L2_VA"
    unique_id: '0a123756452889'
    scan_interval: 6
    slave: 1
    address: 1074
    state_class: measurement
    unit_of_measurement: "VA"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: apparent_power

################################ L3 #########################

  - name: "EPS_L3_V"
    unique_id: '0a1675'
    scan_interval: 6
    slave: 1
    address: 1076
    state_class: measurement
    unit_of_measurement: "V"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: voltage

  - name: "EPS_L3_A"
    unique_id: '0a2791'
    scan_interval: 6
    slave: 1
    address: 1077
    state_class: measurement
    unit_of_measurement: "A"
    data_type: int16
    scale: 0.1
    precision: 1
    input_type: input
    device_class: current

  - name: "EPS_L3_VA"
    unique_id: '0a1237545289'
    scan_interval: 6
    slave: 1
    address: 1078
    state_class: measurement
    unit_of_measurement: "VA"
    data_type: int32
    scale: 0.1
    precision: 1
    input_type: input
    device_class: apparent_power


##Holding REG

  - name: "Inverter_minut"
    unique_id: '0a7476dcc'
    scan_interval: 15
    slave: 1
    input_type: holding
    address: 49
    state_class: measurement
    unit_of_measurement: "min"
    data_type: int16
    scale: 1
    precision: 1

  - name: "Inverter_time"
    unique_id: '0a7476c'
    scan_interval: 10
    slave: 1
    input_type: holding
    address: 48
    state_class: measurement
    unit_of_measurement: "hr"
    data_type: int16
    scale: 1
    precision: 1


###Opladning 


  - name: "bat_1_start"
    unique_id: '0a74746c'
    scan_interval: 60
    slave: 1
    input_type: holding
    address: 1100
    state_class: measurement
    data_type: int16
    scale: 1
    precision: 1

  - name: "bat_1_stop"
    unique_id: '01a74746gbvc'
    scan_interval: 60
    slave: 1
    input_type: holding
    address: 1101
    state_class: measurement
    data_type: int16
    scale: 1
    precision: 0


  - name: "bat_2_start"
    unique_id: '0a74237146c'
    scan_interval: 60
    slave: 1
    input_type: holding
    address: 1103
    state_class: measurement
    data_type: int16
    scale: 1
    precision: 1

  - name: "bat_2_stop"
    unique_id: '0a7415746gbvc'
    scan_interval: 60
    slave: 1
    input_type: holding
    address: 1104
    state_class: measurement
    data_type: int16
    scale: 1
    precision: 1

  - name: "bat_3_start"
    unique_id: '0a74751d46c'
    scan_interval: 60
    slave: 1
    input_type: holding
    address: 1106
    state_class: measurement
    data_type: int16
    scale: 1
    precision: 1

  - name: "bat_3_stop"
    unique_id: '0a74123746gb4vc'
    scan_interval: 60
    slave: 1
    input_type: holding
    address: 1107
    state_class: measurement
    data_type: int16
    scale: 1
    precision: 1





  switches:
      - name: opladning
        unique_id: '0a12f35fdsgh85'
        address: 1092
        write_type: holding
        verify:
      - name: Status
        address: 1092
        command_on: 1
        command_off: 0

      - name: bat_1_tidslot
        unique_id: '0af1235fdsgh5'
        address: 1102
        write_type: holding
        verify:
      - name: Status
        address: 1102
        command_on: 1
        command_off: 0

      - name: bat_2_tidslot
        unique_id: '0a1235gfdsgh3'
        address: 1105
        write_type: holding
        verify:
      - name: Status
        address: 1105
        command_on: 1
        command_off: 0

      - name: bat_3_tidslot
        unique_id: '0a135fhdsg3'
        address: 1108
        write_type: holding
        verify:
      - name: Status
        address: 1108
        command_on: 1
        command_off: 0

      - name: Export_limit
        unique_id: 'cfe6e6d3-0e3a-40b7-980d-e266ca3a29ac'
        address: 122
        write_type: holding
        verify:
      - name: Status
        address: 122
        command_on: 1
        command_off: 0

**Comment by Hans-chr2** [comment]
I don't know if this helps

https://pastebin.com/XP9kmvRA

I have the newest modbus manual someware for it. 
https://www.scribd.com/document/592776725/Growatt-Inverter-Modbus-RTU-Protocol-II-V1-24-English-new

**Comment by choenig** [comment]
Hi, juchu a buddy :)

I just created a WIP-pullrequest https://github.com/wills106/homeassistant-solax-modbus/pull/473 that shows what I changed.

@Hans-chr2 Some of your above errors will get fixed by my changes (e.g. the last two values). Those get fixed by reducing the block_size to 64, don't know why :)

Values vor L2 and L3 look broken here, too, but L1 is mostly correct (just as if it was just a 1 phase inverter)

**Comment by choenig** [comment]
This is my state:

![2023-07-23 14 25 28 ha spsx casa 7c83e412a34b](https://github.com/wills106/homeassistant-solax-modbus/assets/70392/22d4bec7-e8cb-4a45-a0ed-782df10d9163)
![2023-07-23 14 25 46 ha spsx casa 02cb52bbe9d3](https://github.com/wills106/homeassistant-solax-modbus/assets/70392/9eff805c-fe60-463f-96f9-b07c3163015a)
![2023-07-23 14 25 58 ha spsx casa 127818359d69](https://github.com/wills106/homeassistant-solax-modbus/assets/70392/79603ca2-545f-4403-a332-c3dffbd119b0)
![2023-07-23 14 26 15 ha spsx casa ec940d7cea80](https://github.com/wills106/homeassistant-solax-modbus/assets/70392/fa1de78a-5cb0-45a5-af13-9aff73541214)
![2023-07-23 14 26 26 ha spsx casa 9e85bef64726](https://github.com/wills106/homeassistant-solax-modbus/assets/70392/661c93f1-6497-4a5d-9ee8-278ccf2e40b4)

**Comment by choenig** [comment]
Hi, 

I just updated the PR.

I switched back to 100 regs/fetch as I found out, that the issue was just a duplicate reg in the configuration. That resulted in misalignments when assigning values (as it is handled as "set of byte values" then).

Now I don't have any errors in the log anymore during fetch :).

I added some more registers but they don't make too much sense to me.

@Hans-chr2 Did you have a chance to test my patch?

Br
Christian

**Comment by Hans-chr2** [comment]
How do i test your patch easy ?

**Comment by choenig** [comment]
This is the link to the file of the PR:

https://raw.githubusercontent.com/wills106/homeassistant-solax-modbus/32728ab222979ada4f832e99de326976d13c19e3/custom_components/solax_modbus/plugin_growatt.py

You can download it and replace `./custom_components/solax_modbus/plugin_growatt.py` with the downloaded one. Then you need to restart HA (quick restart is not enough). I'd suggest to create a copy of the original file before overwriting it ... just in case ;-)

The next official update (done via HACS) will overwrite the file again.

**Comment by Hans-chr2** [comment]
Just a quick overlook, the following are off: 
![billede](https://github.com/wills106/homeassistant-solax-modbus/assets/133807567/10de009c-1f69-41a8-8e62-f41494be4e2d)
![billede](https://github.com/wills106/homeassistant-solax-modbus/assets/133807567/cdf6f128-6606-4bc0-9177-79338132d92b)

**Comment by Hans-chr2** [comment]
The power reading seems to be the only sensors that are off, but i just looked over it quickly. 
When i look at the code, you use: 
![billede](https://github.com/wills106/homeassistant-solax-modbus/assets/133807567/2b758aef-72f3-4d09-9a69-ab1138cfe988)

and i use: 
![billede](https://github.com/wills106/homeassistant-solax-modbus/assets/133807567/49bbb97f-a7de-4c32-9531-6d3be0234ac3)

as stated in the PDF i'm pretty sure all power readings are int32 and there are high power [kW] reading and low [W]

**Comment by wills106** [comment]
> I'm pretty sure all power readings are int32

That's correct if the register is bidirectional it needs to be an int so it can represent positive and negative values.

You will find that positive means import from the grid and negative is exporting to the grid. (Or the other way round)

@choenig once you are happy with the PR let me know and I can merge it.

**Comment by Hans-chr2** [comment]
@wills106 i know, but as i see it the registers are U32 and if that is correct what ChatGPT states, then you will get some very low or very high power readings because the first bit is used to determine positive/negative. 

But i don't know how the change the int type from U32 til int32, i tried it briefly last night but no luck.

**Comment by choenig** [comment]
Using `signed int`s here makes absolute sense, unfortunately the values are still off for me.

The raw data for 1031, 1033 and 1035 (House Load L1-L3) looks like this:

![Screenshot 2023-07-26 at 09 54 03](https://github.com/wills106/homeassistant-solax-modbus/assets/70392/36befc9a-e31e-41bd-802e-4baf87f7f0a5)

And here for 1023, 1025, 1027 and 1029 (AC Power to Grid L1-L3 and Total)

![Screenshot 2023-07-26 at 09 58 53](https://github.com/wills106/homeassistant-solax-modbus/assets/70392/8893cac4-c6b6-4345-9897-6ab234394c71)

That does not look like `signed` ;)

Any other idea?

@wills106 Thanks, I think i'm trying to get these things sorted out, then I'll make it ready for you :)

**Comment by Hans-chr2** [comment]
@choenig i can't find the modbus manual 1,24 from Growatt on my computer anymore. If you can find that manual you can see the data size. 
As i remember all power and energy readings are 32 bit, and i can see on your screen dump above you pull 16 bit.

**Comment by choenig** [comment]
I have the manual here, but where does it say something about signed/unsigned? I only find the information if it is high 16bit and low 16bit like here:

![Screenshot 2023-07-26 at 16 58 16](https://github.com/wills106/homeassistant-solax-modbus/assets/70392/fdc01bc9-cb35-40ce-be19-b4a122c10fcd)

Or am I missing someting?

> As i remember all power and energy readings are 32 bit, and i can see on your screen dump above you pull 16 bit. 

That's correct, but each 32bit field contains of two 16bit fields. 
E.g. for 1035 and 1036: If we combine 214 (two high bytes) and 226 (two low bytes) we get a strange high number. Or is there any advanced way to combine those two values?

> and i use:

[From the previous post]
Do you have a running application that displays those value correctly?

**Comment by wills106** [comment]
If you use GModbus you have the option to read registers as 32bit either a normal number or as a float.

So you would only read:
1031 as "unit = REGISTER_U32," or "unit = REGISTER_S32,"
1033 as "unit = REGISTER_U32," or "unit = REGISTER_S32,"
1035 as "unit = REGISTER_U32," or "unit = REGISTER_S32,"

Depending on which method you need. Pymodbus will read the inbetween registers as part of each 32bit read (reads two 16bit registers to create a 32bit one)

**Comment by Hans-chr2** [comment]
When i use the modbus integration in Home Assistant via the config files i only use the int32 bit, the power values can both be negative and positive.  i also don't read multiple registers only 1 addressee at the time. 

I think we either over complicates things, or there is something i have done that is stupidly lucky in the config. :-D

![billede](https://github.com/wills106/homeassistant-solax-modbus/assets/133807567/4fd9cbab-8f3f-4f65-bb42-7d37b911f628)

**Comment by Hans-chr2** [comment]
Im out of options now... 

![billede](https://github.com/wills106/homeassistant-solax-modbus/assets/133807567/19fcca62-5aa7-4b17-8e91-0126aed3d342)

**Comment by wills106** [comment]
> Im out of options now...

Does House Load L1 & L2 seem correct?
It might be possible there is a Firmware fault with L3?

**Comment by choenig** [comment]
`L1` shows the same as `Total` for me, so I guess `L2` and `L3` are both broken.

**Comment by Hans-chr2** [comment]
![billede](https://github.com/wills106/homeassistant-solax-modbus/assets/133807567/eed69335-ee9a-41c8-b86c-084bae63f8a4)
![billede](https://github.com/wills106/homeassistant-solax-modbus/assets/133807567/e523cec7-0fc2-40a1-b819-0e0ddda684f4)

Regarding L1+L2+L3 i also have the same issue with my generic modbus, so i see the same as @choenig  now.

**Comment by choenig** [comment]
I marked the PR as `ready`, as it does not look that we have something new here, now. 

Let's then see what the holding-registers-side has for us :)

**Comment by wills106** [comment]
Just released [2023.07.4b2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.07.4b2) with the changes.

**Comment by wills106** [comment]
I have just released [2023.07.4b5](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.07.4b5) which redefines all Growatt Inverters. So a lot has changed.

**Comment by choenig** [comment]
I just updated to `b7` and I have not found any issues, yet :)

**Comment by wills106** [comment]
There is an error but I have just released [2023.07.4b8](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.07.4b8) I was accidentally reading 'Grid Export Limit' as a 32bit register.

**Comment by wills106** [comment]
Corrected another error in [2023.07.4b9](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.07.4b9)

**Comment by wills106** [comment]
Does anyone have a 2nd battery system connected to your Inverter?

**Comment by wills106** [comment]
Just released [2023.08.2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.08.2 which fixes an issue with TL-HX / TL3-HX and adds additional sensor entities for TL-HX / TL3-HX Inverters.

**Comment by wills106** [comment]
Can this be closed down now? Or is further work required?

**Comment by wills106** [comment]
Closing down as no further response.

**Comment by igorzavalyshyn-centrica** [comment]
Just a small comment for Growatt inverters' registers. 
According to 1.24v of official Modbus specs, all registers are U16 (unsigned int16) which means we cannot possibly tell if a given power value is negative or positive. So there is no point in using S32 type for power values instead of U32 because you won't ever get a sign bit.
<img width="1104" alt="image" src="https://github.com/wills106/homeassistant-solax-modbus/assets/126454399/3e429b3d-ea3a-4ddf-8063-04ba567f1c99">
