### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wartungsmonteur** [wills106/homeassistant-solax-modbus#476]
**Describe the bug**

**Mandatory details**
1. Integration Version: Last Version
2. HA Version:  Last Version
3. Inverter Brand: Q.Volt HYP-G3
4. Plugin Used:
5. First 6 digits of Serial: H34C10
6. Connection Method: TCP via waveshare

**Detailed Error Log**
Detailed Error Log, if you press on the individual error further information is displayed.
This is the content we need, the description alone doesn't provide enough context.

If there are no log's showing for SolaX try the following depending on your language settings, you can find the full logs under:

Settings → System → Logs > at bottom of page press “LOAD FULL LOGS”

Now the full logs are loaded. If you scroll down, you will see them.
Once the full logs are shown, you can either use the search function in your browser to search for “solax” related entries or use the search entry field on top of the page.

Search for

solax

and report us the logs. Make sure to replace sensitive information by xxxx (if any)

**Additional context**

**Comment by wartungsmonteur** [comment]
Plugin startet nicht, keineVerbindung zum Modbus, 
Anbei ein Logfile

[home-assistant_solax_modbus_2023-07-26T00-32-36.554Z.log](https://github.com/wills106/homeassistant-solax-modbus/files/12166703/home-assistant_solax_modbus_2023-07-26T00-32-36.554Z.log)

**Comment by wartungsmonteur** [comment]
[home-assistant_2023-07-26T00-44-33.604Z.log](https://github.com/wills106/homeassistant-solax-modbus/files/12166736/home-assistant_2023-07-26T00-44-33.604Z.log)

**Comment by wills106** [comment]
Are you sure that's the correct IP address of the Waveshare?
Most home networks default to 192.168.0.x or 192.168.1.x
Can you ping that address and get a response ok?

**Comment by wartungsmonteur** [comment]
Hallo

IP ist korrekt, der waveshare ist unter 192.168.178.107 erreichbar und auch konfigurierbar.

Ich bin am verzweifeln.

Grüße und vielen Dank für eure Hilfen.

**Comment by wartungsmonteur** [comment]
![Uploading 20230726_144026.jpg…]()

**Comment by wartungsmonteur** [comment]
Hier ein Screenshot

**Comment by infradom** [comment]
> Hier ein Screenshot

Screenshot did not yet arrive ... Uploading .....

**Comment by wartungsmonteur** [comment]
![20230726_144026](https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/782d5065-a50e-4a0f-a681-63e182937f51)

**Comment by wartungsmonteur** [comment]
Es geht wieder, der WR müsste ein Update bekommen, 312 Entitäten sichtbar. Ihr seit phantastisch.. Kann ich euch was spenden und übernehmt ihr auch eventuell eine Fernwartung meines Home-Assistenten ?

Vielen lieben Dank

**Comment by infradom** [comment]
One remark: in my opinion, the enable-multihost option is in most cases not needed . Screenshot from the wikil
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/11804014/43ff61e1-065f-40ea-b2ca-57e55ad4a2cc)

**Comment by infradom** [comment]
Do not forget to disable the DEBUG mode again, otherwise your system might be overwhelmed by messages ..

**Comment by wartungsmonteur** [comment]
Alles ok, der neue WR musste ein  Update bekommen.

**Comment by wartungsmonteur** [comment]
Hallo

Wenn ich die beiden Werte im waveshare umstelle geht es nicht mehr. Ich muss Enable Multi-Host auf yes setzen.

**Comment by infradom** [comment]
Strange, for me, it has worked for years now without multi-host
