### ISSUE TITLE
enhancement - add inverter

### ISSUE THREAD

**Issue by tomschlde** [wills106/homeassistant-solax-modbus#480]
Hi all,
can you please add Inverter Solis :  '1801'  PV only  S6-GR1P1.5K like you added the 6KW Model before in [2023.07.1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.07.1)

Added serial '1802' PV Only S6-GR1P6K, configured as a Hybrid at the moment.

TIA
Thomas

**Comment by wills106** [comment]
Please comment on #444 as this is mostly duplicated.
