### ISSUE TITLE
SolaX Grid Export Limit changed to -xxx

### ISSUE THREAD

**Issue by visitdigital** [wills106/homeassistant-solax-modbus#486]
I am seeing a lot of this style event in my Logbook on home assistant. Just checking if that's OK or I need to tweak a setting?

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/1809171/f5a4557a-c301-467d-9c5b-92eb72ec7022)

**Comment by wills106** [comment]
It's normal.

It's a dual purpose sensor in normal use it matches your 'Inverter Power'
But it can also be used to [Force Discharge](https://github.com/wills106/homeassistant-solax-modbus/wiki/SolaX-Gen2-&-Gen3-Modes-of-operation#grid-export-gen-3-only) your Inverter into the grid.
