### ISSUE TITLE
[BUG]? High Grid Import after Inverter Update

### ISSUE THREAD

**Issue by jdedo** [wills106/homeassistant-solax-modbus#495]
After my inverter received an automatic update through the connected Pocket LAN Adapter, I noticed a new option for "peak shaving" in my Solax App. I've been using this integration for several months, and everything worked perfectly until this update. Now, there seems to be an issue. I have a simple automation that toggles between two modes: 'Enabled Self Use' and 'Enabled Feed-in Priority'. However, since the update, the inverter has begun importing power from the grid even when the battery is almost full. I've tried troubleshooting by checking all settings, reinstalling the integration, and restarting the inverter, but the problem persists.

I'm very thankful for the excellent integration you've provided, I would greatly appreciate your assistance with this issue.

**Mandatory details**
1. Integration Version: 2023.08.5
2. HA Version:2023.8.2
3. Inverter Brand:Solax
4. Plugin Used:
5. First 6 digits of Serial:H34A15
6. Connection Method: Modbus TCP with Waveshare RS485 to RJ45 Ethernet

**Detailed Error Log**
[custom_components.solax_modbus.plugin_solax] peak shaving: old_ap_target:-2968 new ap_target:-3382.0 max: -3382.0
[custom_components.solax_modbus.plugin_solax] Evaluated remotecontrol_trigger: corrected/clamped values: [('remotecontrol_power_control', 'Enabled Power Control'), ('remotecontrol_set_type', 'Set'), ('remotecontrol_active_power', -924), ('remotecontrol_reactive_power', 0), ('remotecontrol_duration', 20)]
[custom_components.solax_modbus] ready to repeat button remotecontrol_trigger data: [('remotecontrol_power_control', 'Enabled Power Control'), ('remotecontrol_set_type', 'Set'), ('remotecontrol_active_power', -924), ('remotecontrol_reactive_power', 0), ('remotecontrol_duration', 20)]
[custom_components.solax_modbus] Ready to write multiple registers at 0x7c: [1, 1, 64612, 65535, 0, 0, 20]

<img width="862" alt="image" src="https://github.com/wills106/homeassistant-solax-modbus/assets/64967403/fe97c7de-6823-4027-b61c-418d8f796112">

<img width="250" alt="image" src="https://github.com/wills106/homeassistant-solax-modbus/assets/64967403/ed99eca5-21a5-442e-a872-30ab1bccbeb7">

**Comment by infradom** [comment]
Seems like a side effect of the software updates solax has been pushing out. 
Issues #488 and #492 are also related to his.
There is a 'simple solution' but we hesitate to push it until further tests are successful
We know this is annoying. For the ones with more technical background: a quick fix is suggested in issue #492 
We hope to implement this in a release soon, but to not want to take any risks

**Comment by jdedo** [comment]
@wills106 
It would be great if you could publish a beta version; I'll test it. I have some concerns given the system's criticality. Any advice or things I should be aware of? Thanks for pushing this forward!

**Comment by wills106** [comment]
Should be corrected in [2023.09.1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.09.1)

**Comment by jdedo** [comment]
@wills106 thanks for the update

I tested the remote trigger this morning and noticed that the grid import was much lower than before. However, it's still higher compared to when I switch the inverter to FeedIn mode without using the remote trigger.

I've also observed another strange behavior, as you can see in the chart: when the remote trigger is activated in 'FeedIn' mode, the Grid Export continuously decreases."
<img width="476" alt="image" src="https://github.com/wills106/homeassistant-solax-modbus/assets/64967403/41908196-c1d0-4dfa-83d6-6573776d574c">

<img width="165" alt="image" src="https://github.com/wills106/homeassistant-solax-modbus/assets/64967403/86e0f0da-c91d-45cf-9942-03eb4233f848">

I hope this information is helpful. It would be great if you could assist me in fixing these issues. Thanks!

**Comment by iMatte81** [comment]
Hi,
I've solved my issue using the function Enabled Power Control in Power Control of the master inverter and after calculate the right value of remotecontrol_active_power (by home assistant), this value is:

remotecontrol_active_power = house_load - pv_power_total

but with inverter master and slave system:

house_load = house_load_master + house_load_slave
pv_power_total = pv_power_total_master + pv_power_slave

In this way I can control correctly my plant.

During the configuration of the two inverters with the solax integration I have selected for both the inverters the checkbox Parallel Mode (Master-Slave), is it right?

If I use the enabled_feed_in of the solax integration, the remotecontrol_active_power calculated by the integration for the inverter master is not the total power but the only power of this inverter while my system needs the total power of the two inverters for working correctly.

**Comment by infradom** [comment]
In order to be able to implement this in the source code, yould you answer follwoing question (I am not familiar with the master/slave concept):
- how do you red the pv_power of the slave ? which entity?
- same question for the inverter_load of the slave (that entity is used to compute house_load_nett)

**Comment by iMatte81** [comment]
> In order to be able to implement this in the source code, yould you answer follwoing question (I am not familiar with the master/slave concept):
> 
>     * how do you red the pv_power of the slave ? which entity?
> 
>     * same question for the inverter_load of the slave (that entity is used to compute house_load_nett)

1. I read the power of the slave from the slave directly, using pv_power_total. To calculate the total power of the plant, I add the pv_power_total of the master and pv_power_total of the slave
2. The same as before, I read the parameter house_load and I add master and slave readings

peimar_potenza_ftv:
    unit_of_measurement: "W"
    value_template: '{{ states("sensor.peimar_10kw_pv_power_total" )| float + states("sensor.peimar_6kw_pv_power_total") | float }}'

  peimar_casa_load:
    unit_of_measurement: "W"
    value_template: '{{ states("sensor.peimar_10kw_house_load" )| float + states("sensor.peimar_6kw_house_load") | float }}'


I have configured 2 inverter in the Solax integration

![immagine](https://github.com/wills106/homeassistant-solax-modbus/assets/32608245/d8a36e01-1a39-4aa8-b0a6-5c2aeb650411)

![immagine](https://github.com/wills106/homeassistant-solax-modbus/assets/32608245/0b1295ac-02e4-4158-80d9-e4353dfec4c1)

**Comment by wills106** [comment]
Just so you know I released [2023.09.6](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.09.6) this reverted houseload back to the old style of calculation which I find more accurate and you don't get spikes from Solar affecting it.

> During the configuration of the two inverters with the solax integration I have selected for both the inverters the checkbox Parallel Mode (Master-Slave), is it right?

If the Inverters are in a true Master/Slave setup you only need to add in the First Inverter with PM selected. It should then read in the second Inverter. But you only get a limited set of data.

Are all the Inverters behind the same Modbus Power Meter?

We might be able to read the measured power (Indicated from the Power Meter) and deduct the Current from Each connected Inverter as that data is per phase is given and then calculate a global houseload from that. We know how many Inverters are connected from a register that is used in PM

**Comment by wills106** [comment]
Are you able to give a screenshot of all the entities starting PM on the Master Inverter.

**Comment by wills106** [comment]
Just so you know I am going to add in PeakShaving later this week.

**Comment by iMatte81** [comment]
> Are you able to give a screenshot of all the entities starting PM on the Master Inverter.

![immagine](https://github.com/wills106/homeassistant-solax-modbus/assets/32608245/bbd65794-c166-492e-a075-3d4e188cca8a)

![immagine](https://github.com/wills106/homeassistant-solax-modbus/assets/32608245/7bccd4e3-cf0d-47dd-b906-509048c58988)

![immagine](https://github.com/wills106/homeassistant-solax-modbus/assets/32608245/932b687a-6d29-4d4a-b0e7-8f408037c143)

![immagine](https://github.com/wills106/homeassistant-solax-modbus/assets/32608245/2024fa4b-c2a7-4145-bf6f-a754b2876adb)

**Comment by wills106** [comment]
I meant with the Values sorry, aren't they listed like:

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/18155231/0c9867f1-f952-48df-aeff-f1e7a3169aac)

On the Integration page?

**Comment by iMatte81** [comment]
> Just so you know I released [2023.09.6](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.09.6) this reverted houseload back to the old style of calculation which I find more accurate and you don't get spikes from Solar affecting it.
> 
> > During the configuration of the two inverters with the solax integration I have selected for both the inverters the checkbox Parallel Mode (Master-Slave), is it right?
> 
> If the Inverters are in a true Master/Slave setup you only need to add in the First Inverter with PM selected. It should then read in the second Inverter. But you only get a limited set of data.
> 
> Are all the Inverters behind the same Modbus Power Meter?
> 
> We might be able to read the measured power (Indicated from the Power Meter) and deduct the Current from Each connected Inverter as that data is per phase is given and then calculate a global houseload from that. We know how many Inverters are connected from a register that is used in PM

The inverter are all behind the same modbus power meter connected only to the master one

I have updated this morning to the new version, but the result are the same, if I set feed in priority the system always charge the battery.

**Comment by iMatte81** [comment]
![immagine](https://github.com/wills106/homeassistant-solax-modbus/assets/32608245/782c59e5-21ea-4aee-8eba-0d83bb469714)


![immagine](https://github.com/wills106/homeassistant-solax-modbus/assets/32608245/692f01ff-5a58-4487-bc03-de88b5ba507c)


![immagine](https://github.com/wills106/homeassistant-solax-modbus/assets/32608245/2b29aaa4-41c3-4759-9158-a70c4cebe69c)


![immagine](https://github.com/wills106/homeassistant-solax-modbus/assets/32608245/5ee0a2a7-5907-4674-a99a-4f8785811bb8)

**Comment by wills106** [comment]
If you manually enable "PM Inverter Count" does it display 1 for 1 slave. Or does it display 2 for Master and Slave?

We could use that to know how many Inverters are connected for a calculation. But we wouldn't know how you have named them.

> house_load = house_load_master + house_load_slave
> pv_power_total = pv_power_total_master + pv_power_slave

Perhaps we need a text entry to input your templated sensors? Unless there is enough info from all of the PM sensors?

**Comment by iMatte81** [comment]
> If you manually enable "PM Inverter Count" does it display 1 for 1 slave. Or does it display 2 for Master and Slave?
> 
> We could use that to know how many Inverters are connected for a calculation. But we wouldn't know how you have named them.
> 
> > house_load = house_load_master + house_load_slave
> > pv_power_total = pv_power_total_master + pv_power_slave
> 
> Perhaps we need a text entry to input your templated sensors? Unless there is enough info from all of the PM sensors?

![immagine](https://github.com/wills106/homeassistant-solax-modbus/assets/32608245/c99602a8-2283-4575-872c-e4fb72fc54bb)

The names are:
- Peimar_10kW
- Peimar_6kW

**Comment by wills106** [comment]
Just wondering if this is an active issue. Or has it been worked around or resolved?

**Comment by wills106** [comment]
Closing down as no response.
