### ISSUE TITLE
Growatt  unrecognized inverter type MIC 2500tl-x

### ISSUE THREAD

**Issue by super-bedst** [wills106/homeassistant-solax-modbus#502]
Please add this 1 phase Growatt inverter MIC 2500tl-x it is without battery and 1 mppt serial is : FVJ4CD708B

**Comment by wills106** [comment]
Is that what the Integration returns in the error log?
(f"unrecognized {hub.name} inverter type - firmware version : {seriesnumber}")

Or the actual Serial Number? On the Growatt it's using the firmware version and not the serial number.

**Comment by super-bedst** [comment]
Here is the string from the log
unrecognized Growatt Mic inverter type - firmware version : GH1.0ZAAA

**Comment by wills106** [comment]
Just released [2023.08.6](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.08.6)

**Comment by wills106** [comment]
Is your Inverter working now?
Can I close this down?

**Comment by wills106** [comment]
Closing down as Inverter should be supported now.

**Comment by super-bedst** [comment]
HiYes it works great 😊 MobilmailMed Venlig HilsenPeter FriisMobil 20654196Den 3. sep. 2023 kl. 13.17 skrev wills106 ***@***.***>:﻿
Closing down as Inverter should be supported now.

**Comment by wills106** [comment]
@super-bedst Is your MIC Inverter reporting Grid Current, Grid Power, Grid Power correctly?

Or do you have the same scaling issue as #727 

```
Grid Current: 0.8A >> 0.08A
Grid Power: 93W >> 9.3W
Grid Power VA: 118 VA >> 11.8 VA
```
