### ISSUE TITLE
[BUG]? Meter Power Factor is missing a unit

### ISSUE THREAD

**Issue by dakaix** [wills106/homeassistant-solax-modbus#508]
**Describe the bug**
The sensor for Meter Power Factor does not have a unit of measurement set, this results in every change being recorded as a state (rather than displaying as a graph) and results in very significant churn in the Home Assistant logbook. 

**Mandatory details**
1. Integration Version: 2023.08.6
2. HA Version: 2023.8.4
3. Inverter Brand: Solis
4. Plugin Used: HACS
5. First 6 digits of Serial: 603015
6. Connection Method: TCP

![Logbook](https://github.com/wills106/homeassistant-solax-modbus/assets/8070376/ad47c792-32fa-4a6b-81ce-02440609d85e)
![States](https://github.com/wills106/homeassistant-solax-modbus/assets/8070376/020f1879-b34e-4f44-8b9c-d2d3b351ef60)

**Comment by wills106** [comment]
Just released [2023.08.7b2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.08.7b2) does it look correct now?

**Comment by wills106** [comment]
I think this needs scaling. Shouldn't PF be 1.0 or -0.55 or 0.58 etc?

**Comment by dakaix** [comment]
Normally yes, and expressed as a unit of “p.f”.

I wonder though how the meter itself expresses it on the display… will be a few days before I can check that though!

**Comment by wills106** [comment]
https://github.com/home-assistant/architecture/issues/469

Looks like I can either define "PERCENTAGE" or "None" so it works as a graph https://github.com/home-assistant/core/pull/85181/files

Which would you prefer?

**Comment by dakaix** [comment]
Interestingly the Eastron meter’s Modbus documentation lists power factor as having no unit and as a float. That suggests Solis themselves may be translating this to a percentage.

https://eastroneurope.com/images/uploads/products/protocol/SDM120-MODBUS_Protocol.pdf

If this sensor is Solis specific then I would say go %, but if it’s generic then None would be better (as other vendors may not be scaling it up).

**Comment by wills106** [comment]
I have changed it to None in [2023.08.7b3](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.08.7b3) and scaled it.

Can you let me know if the Graphing works correctly with None. If it does I'll update the Sofar plugin as well.

**Comment by dakaix** [comment]
So good news, graphing now works... bad news, with "None" as the Unit it literally appends that to the UI!
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/8070376/ac141b58-666d-4545-88df-da310d8d2a73)

**Comment by wills106** [comment]
Should be corrected in [2023.09.1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.09.1)

**Comment by dakaix** [comment]
That’s back to displaying as a state change I’m afraid. 
![IMG_5880](https://github.com/wills106/homeassistant-solax-modbus/assets/8070376/aac765a6-a28c-486d-aeb2-9425b498e2ca)
![IMG_5881](https://github.com/wills106/homeassistant-solax-modbus/assets/8070376/564972bc-b56e-485f-99d0-0898ace5c5f7)

**Comment by wills106** [comment]
I have added in an extra state_class to force it back into a measurement [2023.09.2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.09.2)

**Comment by wills106** [comment]
Did you manage to test 2023.09.2 out?

Just wondering if I can close this down now?

**Comment by dakaix** [comment]
Yes looking much better now! Thanks for jumping on this so quickly! :)

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/8070376/f81229cf-c055-4d40-8cbd-76a3fa63a8f7)

**Comment by wills106** [comment]
I'll close this down then!
