### ISSUE TITLE
Solis House Load - zero readings 

### ISSUE THREAD

**Issue by bulletcom** [wills106/homeassistant-solax-modbus#525]
1. Integration Version: 2023.09.2
2. HA Version: 2023.8.4
3. Inverter Brand: Solis Hybrid 6K
4. Plugin Used: SolaX Inverter Modbus
5. First 6 digits of Serial: 603105
6. Connection Method: Elfin EW11 using this method: https://github.com/Jumpy07/Solis---SolisCloud-and-Home-Assistant

Issue:
Solax House Load is periodically reading zero. All other entities report correctly. Have restarted all components including inverter but still happening. 

![Screenshot 2023-09-04 at 08 42 07](https://github.com/wills106/homeassistant-solax-modbus/assets/104208960/df0202b5-944b-4df1-9886-0c7211f3bef0)

Any ideas? 

SolisCloud readings are ok (albeit at 5 min intervals) so I don't think it's the inverter.

**Comment by alienatedsec** [comment]
Interesting that I have similar readings but never paid any attention to that. I'm using waveshare so it's not the connection method. ![image](https://github.com/wills106/homeassistant-solax-modbus/assets/73167064/e7a007c3-de4b-4595-90bb-b283416218ca)

**Comment by wills106** [comment]
Are actually getting errors when you get a zero reading?
If there isn't, I can't really do anything about it.

**Comment by wills106** [comment]
Release [2023.09.5](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.09.5) won't address communication issues, but should prevent dashboard spikes if a `None` value was sent. But if the Inverter is genuinely sending 0W house load then there isn't much we can do about that as it's just reporting what the Inverter tells it.

**Comment by wills106** [comment]
Closing down as no further response from original poster.
