### ISSUE TITLE
[BUG] Manual mode with force charge / discharge not working

### ISSUE THREAD

**Issue by alibasta** [wills106/homeassistant-solax-modbus#539]
**Describe the bug**
I try to write an automation to force charge the battery when the Tibber energy prices are low and the battery is nearly empty. Currently I try to change manually the following in the Solax HA device settings:

- **Charger Use mode** to **Manual Mode**
<img width="337" alt="Bildschirmfoto 2023-09-20 um 13 31 55" src="https://github.com/wills106/homeassistant-solax-modbus/assets/362022/a7074719-5f6d-43e9-8eba-978c56ef3b24">

- **Manual Mode Control** to **On**
<img width="363" alt="Bildschirmfoto 2023-09-20 um 13 32 15" src="https://github.com/wills106/homeassistant-solax-modbus/assets/362022/1706e7e8-03b8-472d-88b9-61f20b996ec1">

- **Manual Mode Select** to **Force Charge** (also tried force discharge)
<img width="373" alt="Bildschirmfoto 2023-09-20 um 13 32 21" src="https://github.com/wills106/homeassistant-solax-modbus/assets/362022/9c085fb4-b3b2-4686-be44-d1e73b29658d">

In the HA Logfile I can see that the Charger Use mode switches back to the original value and Battery charging / discharging is not working.

**Mandatory details**
1. Integration Version: 2023.02.1
2. HA Version: 2023.8.3
3. Inverter Brand: Solax X3 Hybrid G4
4. Plugin Used:
5. First 6 digits of Serial:
6. Connection Method:

**Comment by wills106** [comment]
Like infradom mentions, if your Inverter is indead "locked" check https://github.com/wills106/homeassistant-solax-modbus#faq Point 3

**Comment by alibasta** [comment]
Thanks guys. It was my fault. The inverter was not unlocked yet! 

"Modbus Power Control (remotecontrol)" looks very exciting and like made for the intended purpose. Do you use the remotecontrol function to charge the battery in winter via a dynamic power tariff?

**Comment by infradom** [comment]
> Do you use the remotecontrol function to charge the battery in winter via a dynamic power tariff?

Yes, I  use a dynamic power tariff and I indeed use it in the winter to charge the batteries when prices are low. In summer, spring, I use it to discharge batteries when prices are high. I also switch to the emulated 'feedin priority' when prices are intermediate.

**Comment by wills106** [comment]
Closing down as initial issue resolved.
