### ISSUE TITLE
[BUG] issues connecting second Solis Inverter

### ISSUE THREAD

**Issue by funks81** [wills106/homeassistant-solax-modbus#554]
I'm having issues connecting my second (string) inverter to the integration.  I'm connecting via Modbus over TCP.  I have an existing hybrid inverter that connects with no problems to home assistant.  If I plug in the new hardware to the existing hybrid inverter then its data shows up in home assistant.  However, when plugging in to my second (string) inverter I get the following error messages:

                      Logger: custom_components.solax_modbus.plugin_solis
                      Source: custom_components/solax_modbus/plugin_solis.py:63
                      Integration: SolaX Inverter Modbus (documentation, issues)
                      First occurred: 17:54:49 (7 occurrences)
                      Last logged: 17:58:42
                      
                      Solis String: reading serial number from address 0x80ec failed; other address may succeed

                      Logger: custom_components.solax_modbus.plugin_solis
                      Source: custom_components/solax_modbus/plugin_solis.py:2293
                      Integration: SolaX Inverter Modbus (documentation, issues)
                      First occurred: 17:54:49 (7 occurrences)
                      Last logged: 17:58:42
                      
                      Solis String: cannot find serial number, even not for other Inverter

Obviously this isn't a hardware or communication issue with home assistant - as it works fine when I plug in to my existing hybrid inverter.

1. Integration Version:  2023.09.7
2. HA Version:  2023.10.1
3. Inverter Brand: Solis
4. Plugin Used:  Solax Modbus
5. First 6 digits of Serial:  180102
6. Connection Method:  Modbus via TCP

**Comment by wills106** [comment]
Closing down as no further feedback.
