### ISSUE TITLE
[BUG] Entities - Unavailable ARM/DSP Firmware version

### ISSUE THREAD

**Issue by matomatusov** [wills106/homeassistant-solax-modbus#570]
**Mandatory details**
1.Integration Version: 2023.10.3
2. HA Version: 2023.10.2
3. Inverter Brand: Solax X3 Gen4 10kW
4. Plugin Used: Solax Modbus
5. First 6 digits of Serial: H34A10
6. Connection Method: ModBus TCP using WaveShare RS485 TO ETH (B)

Solax
After the update to 2023.10.1 it stopped working firmware version.

**Detailed Error Log**
This entity is no longer being provided by the solax_modbus integration. If the entity is no longer in use, delete it in settings.

![1](https://github.com/wills106/homeassistant-solax-modbus/assets/129114957/cde4f42a-58c8-4b2b-9773-704eeed88a3f)

**Comment by cewbdex** [comment]
This is no bug, thing were changed under the hood, so it matches the reality - master for G3 and older and ARM for G4. Remove entities and add the correct new ones:
![obrazek](https://github.com/wills106/homeassistant-solax-modbus/assets/9021297/53800e89-503d-4e61-8104-44d25e1d7316)

**Comment by matomatusov** [comment]
Thank you for the information, it works.

**Comment by wills106** [comment]
I forgot to add it to the change log on 2023.10.1
