### ISSUE TITLE
Expose inverter model to HA

### ISSUE THREAD

**Issue by cewbdex** [wills106/homeassistant-solax-modbus#594]
Inverter model is already known to the integration, however the information is not passed to the HA:
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/9021297/769e93a3-2b58-44cb-9097-928fba6c5f40)
Just a small enhacement.

**Comment by wills106** [comment]
Just released [2024.05.4b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.05.4b1) are your Firmware versions correct in Device Info panel?

**Comment by wills106** [comment]
Released [2024.05.4](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.05.4)
