### ISSUE TITLE
[Bug]: unrecognized inverter type - serial number : H4492AJ666XXXX

### ISSUE THREAD

**Issue by Joerivanrokeghem** [wills106/homeassistant-solax-modbus#600]
### Describe the bug

only shows up 4 entities, in debug I get the following error
2023-11-07 17:07:47.909 ERROR (MainThread) [custom_components.solax_modbus.plugin_solax] unrecognized inverter type - serial number : H4492AJ666XXXX

### Integration Version

2023.11.1

### Homeassistant core version

2023.11.1

### Inverter brand

Solax Power

### Plugin used

Solax

### First 6 digits of Serial

H4492A

### Inverter firmware versions

unable to find

### Connection Method

solax pocket wifi

### Dongle firmware

10.16

### I have done my own research

- [X] Yes, I did

**Comment by wills106** [comment]
This is meant to be posted under https://github.com/wills106/homeassistant-solax-modbus/discussions/520
But that doesn't matter too much.
Main thing I need to know is what exactly is this Inverter as that's a true unique Serial Number so far.

**Comment by Joerivanrokeghem** [comment]
Hi wills106,

the model of this inverter is a X1-Hybride-5.0K-D

**Comment by wills106** [comment]
Just a normal Gen4? Or an updated model?

**Comment by Joerivanrokeghem** [comment]
Yes, a normal Gen4

Met vriendelijke groeten,
Van Rokeghem Joeri

________________________________
Van: wills106 ***@***.***>
Verzonden: Tuesday, November 7, 2023 10:28:41 PM
Aan: wills106/homeassistant-solax-modbus ***@***.***>
CC: Joerivanrokeghem ***@***.***>; Author ***@***.***>
Onderwerp: Re: [wills106/homeassistant-solax-modbus] [Bug]: unrecognized inverter type - serial number : H4492AJ666XXXX (Issue #600)


Just a normal Gen4? Or an updated model?

**Comment by wills106** [comment]
Ok, I just wanted to double check it want a new Generation.
I'll try add it in tomorrow.

**Comment by Joerivanrokeghem** [comment]
thanks in advance!

**Comment by wills106** [comment]
Just released [2023.11.2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.11.2)

**Comment by wills106** [comment]
Can I close this down?

**Comment by Joerivanrokeghem** [comment]
Yes it works, and can be closed. Thanks for the great work!

Met vriendelijke groeten,
Van Rokeghem Joeri

________________________________
Van: wills106 ***@***.***>
Verzonden: Wednesday, November 29, 2023 9:18:32 PM
Aan: wills106/homeassistant-solax-modbus ***@***.***>
CC: Joerivanrokeghem ***@***.***>; Author ***@***.***>
Onderwerp: Re: [wills106/homeassistant-solax-modbus] [Bug]: unrecognized inverter type - serial number : H4492AJ666XXXX (Issue #600)


Can I close this down?
