### ISSUE TITLE
[Bug]: solax PV shadow fix cannot set separately for all inputs

### ISSUE THREAD

**Issue by HA-Supi** [wills106/homeassistant-solax-modbus#628]
### Describe the bug

Hello.,

Since some version I can not set shadow fix via addon for PV1 and PV2 separately, as I can via Qcells / Solax app.

### Integration Version

2023.11.4

### Homeassistant core version

2013.11.2

### Inverter brand

Solax x3 G4.2 ( Qcells hyp g3)

### Plugin used

plugin_solax.py

### First 6 digits of Serial

H34B08

### Inverter firmware versions

Arm 1.31, DSP 1.33

### Connection Method

Qcells pocket wifi 3.0

### Dongle firmware

 3.001.02 

### Detailed Error Log

No log

**Comment by cewbdex** [comment]
I guess it was never possible, as I was the one that added the option and there was never any other. There is a second shadow fix option #599. You can try the changes if they help you (add only the two SolaX entities to your code).
