### ISSUE TITLE
[Bug]: "solax_inverter_current" value is the same as of "solax_inverter_current_l1"

### ISSUE THREAD

**Issue by mbeetle** [wills106/homeassistant-solax-modbus#629]
### Describe the bug

The Sensor solax_inverter_current has the value of the Sensor solax_inverter_current_l1 instead of the sum from
solax_inverter_current_l1 + solax_inverter_current_l2 + solax_inverter_current_l3

### Integration Version

2023.11.4

### Homeassistant core version

2023.11.2

### Inverter brand

Q.VOLT_HYB-G3-3P

### Plugin used

plugin_solax.py

### First 6 digits of Serial

H34C12

### Inverter firmware versions

ARM 1.33 DSP 1.34

### Connection Method

Waveshare Adapter

### Dongle firmware

Modbus

**Comment by wills106** [comment]
I know this got raised first. But is it the same as #667

**Comment by mbeetle** [comment]
Hi Will

Yes it is the same



Am Di., 20. Feb. 2024 um 19:34 Uhr schrieb wills106 <
***@***.***>:

**Comment by mbeetle** [comment]
Hi Will
I am sorry, i did not read correctly. It is not the same. My bug was
Inverter current, not Inverter Power.

Am Di., 20. Feb. 2024 um 19:46 Uhr schrieb wills106 <
***@***.***>:
