### ISSUE TITLE
[Question]: Solax_ev_charger

### ISSUE THREAD

**Issue by matomatusov** [wills106/homeassistant-solax-modbus#630]
Hi,
is this integration working? I can't load the entities.

Thanks

![ev charger](https://github.com/wills106/homeassistant-solax-modbus/assets/129114957/f79f3611-e312-4bbd-8b96-befb14b8940b)

### Integration Version

2023.11.4

### Homeassistant core version

core-2023.11.2

### Inverter brand

Solax Power

### Plugin used

plugin_solax.py

### First 6 digits of Serial

H34A10

### Connection Method

Waveshare adapter

**Comment by PatrikTrestik** [comment]
It depends how you connect it. 
EV Charger has no Modbus TCP option so you have to connect it by wire and Modbus RTU.
But than you cannot connect it ma Modbus to Inverter for smart functions.

We are currently in the middle of testing HTTP API access, but it is in early stage.

**Comment by matomatusov** [comment]
I have it connected to the inverter on the COM port (Modbus RTU).

**Comment by matomatusov** [comment]
Hi,
I am closing this bug.
It is solved through SolaX http.
https://github.com/PatrikTrestik/homeassistant-solax-modbus

Thanks.

**Comment by PatrikTrestik** [comment]
> Hi, I am closing this bug. It is solved through SolaX http. https://github.com/PatrikTrestik/homeassistant-solax-modbus
> 
> Thanks.

Correct link to http api integration: https://github.com/PatrikTrestik/homeassistant-solax-http
