### ISSUE TITLE
[Bug]: Unable to find entities

### ISSUE THREAD

**Issue by jacobsdad** [wills106/homeassistant-solax-modbus#646]
### Describe the bug

I have been unable to find additional entities. I followed the instructions for "Go to the SolaX Integration page. > >Find "+xy entities not shown", etc., but I am unable to find these options anywhere.

### Integration Version

2023.11.3

### Homeassistant core version

2023.11.3

### Inverter brand

Solax G4

### Plugin used

plugin_growatt.py

### Serial prefix

SRYBUL

### Connection Method

Pocket wifi

### Additional context

No additional info

**Comment by wills106** [comment]
If you go to:
Settings
Devices & Services
1 Device, under SolaX Inverter Modbus
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/18155231/ab292bf3-29dc-4ae9-829a-ca14888f04cd)
You will see a couple of +number. In my case under Diagnostic it's +21 entities not shown
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/18155231/074ef61a-405c-424d-8ec5-82992d735c2c)
I also have about +50 Under the Sensors grouping.
The amount you have is determined by your Inverter type.

**Comment by jacobsdad** [comment]
Thanks for your reply. I've looked under all the settings and have nothing like that available:

![Capture](https://github.com/wills106/homeassistant-solax-modbus/assets/41503410/3353e250-617b-4e30-afe8-4b14b04119b0)
![Capture 2](https://github.com/wills106/homeassistant-solax-modbus/assets/41503410/96ae485a-4432-4d3a-a924-6b172b4ceb42)

**Comment by jacobsdad** [comment]
My inverter is X1-Hybrid-G4.

**Comment by wills106** [comment]
You don't have a working Modbus connection to your Inverter.

https://github.com/wills106/homeassistant-solax-modbus#pocket-wifi-30-with-firmware-v300403-and-above-is-only-officially-supported-solax-only-mentions-gen4-hybrid-other-inverters-may-work

If you have an older PocketWiFi 2 or below they are not reliable.

If you have a PocketWiFi 3.0 you may require a Firmware update.
https://homeassistant-solax-modbus.readthedocs.io/en/latest/solax-firmware-update/#pocketwifi-30
SolaX can do this remotely for you, if you email them.

**Comment by jacobsdad** [comment]
Thanks. I will contact them and let you know if there was any success. Appreciate your time.

**Comment by jacobsdad** [comment]
Hello again,

I have heard back from Solax who have updated my pocketwifi to the latest version (please see below). However, I am still only seeing 4 entities. Is there something else I am missing?

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/41503410/30e62b01-7b37-40b6-937a-838e2b57ffc8)

**Comment by lieglw** [comment]
Hi, have a similar issue on Core 2023.11.3, so removed Solax device from integration and than removed the integration from Hacs restored a back up 2023.11.2
After the Back up is installed, got the newest version from the integration. Now it works again.
For my issue I needed to the Core to be 2023.11.2

**Comment by jacobsdad** [comment]
Have closed. Thanks for your help and support.
