### ISSUE TITLE
[Bug]: Cannot set charge times when battery is empty

### ISSUE THREAD

**Issue by mg180** [wills106/homeassistant-solax-modbus#650]
### Describe the bug

I have a reoccurring issue where I often cannot change the start or end time for charge period 1 or 2 if the battery is empty (10%).

If I select a new time from the dropdowns, it waits a second before reverting to the previous time.

I suspect the inverter is going in to some sort of standby mode. I have tried using the unlock and unlock advanced buttons, as well using the 'turn off' and 'turn on' buttons. These have no effect.

I am able to set the charge time via the solax cloud pages and mobile app, although interestingly I do often need to hit the save button a few times before it takes effect. The mobile app sometimes returns a 'request failed' notification. 

Once a value has been sent via solax cloud, I am then able to set new values using the hass integration. Presumably solax cloud is sending some sort of wake-up command to the inverter.

I never have this issue when the battery is above 10%.

This is happening on a Solax X1 G4 hybrid inverter and I am connecting using wired RS485 port (via Waveshare adapter). I also know of someone else who has the same inverter who is having the same issue but using the WiFi dongle.

### Integration Version

2023.09.7

### Homeassistant core version

2023.11.2

### Inverter brand

Solax Power

### Plugin used

plugin_solax.py

### Serial prefix

H4502A

### Inverter firmware versions

Unknown, how can I find this?

### Connection Method

Waveshare Adapter

### Dongle firmware

V1. 486

**Comment by wills106** [comment]
This isn't a bug with the Integration.
It's how Inverters work, once the PV is below the set trigger point and the battery is flat they shut down to conserve electric. The same way a PV only Inverter shuts down when the Sun goes down.

Inverters are designed to generate electricity and not consume.

If you need to charge during the night you need to set a charge window before the Inverter shuts down.
