### ISSUE TITLE
[Bug]: Entity SolaX Battery State of Health and  BMS Battery Capacity

### ISSUE THREAD

**Issue by matomatusov** [wills106/homeassistant-solax-modbus#665]
### Describe the bug

Hi,
what could be the problem that it shows me zero values for 2 entities regarding the battery.
They are the following entities:
- SolaX Battery State of Health 
- BMS Battery Capacity

Thanks

![battery](https://github.com/wills106/homeassistant-solax-modbus/assets/129114957/becf9228-2267-44be-b267-bbd900827f7e)

### Integration Version

2023.12.4

### Homeassistant core version

core-2023.12.1

### Inverter brand

Solax Power

### Plugin used

plugin_solax.py

### Serial prefix

H34A10

### Inverter firmware versions

ARM1.35 DSP1.34

### Connection Method

Waveshare adapter

### Dongle firmware

3.010.16

**Comment by wills106** [comment]
I did mention in the Release notes that not all BMS's return values. [2023.12.1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.12.1)

This is why I normally don't include any BMS registers as they have caused confusion in the past.

**Comment by matomatusov** [comment]
HI,
I just that they are displayed to some and not to some. I am trying to understand why this is so.

Thanks
