### ISSUE TITLE
[Bug]: Unlock Inverter & Unlock Inverter - Advanced

### ISSUE THREAD

**Issue by matomatusov** [wills106/homeassistant-solax-modbus#671]
### Describe the bug

Hi,
after the update Solax modbus (2023.12.5) stopped working two entities.

- Unlock Inverter
- Unlock Inverter - Advanced

Was it intentional?

![unlock inverter](https://github.com/wills106/homeassistant-solax-modbus/assets/129114957/8e6ce351-d5c6-4ce2-8162-6ece6e09e975)

Thanks

### Integration Version

2023.11.5

### Homeassistant core version

core-2023.11.3

### Inverter brand

Solax Power

### Plugin used

plugin_solax.py

### Serial prefix

H34A10

### Inverter firmware versions

ARM1.35 DSP1.34

### Connection Method

Waveshare adapter

### Dongle firmware

3.010

**Comment by cewbdex** [comment]
Yes, look in changelog. They were redundant.

**Comment by matomatusov** [comment]
From this I did not understand that they were useless.

Thanks

**Comment by wills106** [comment]
I disabled the buttons as they are now a duplicate of the Select function. Which provides feedback which "Unlock" mode the Inverter is in.

**Comment by matomatusov** [comment]
thanks, I understood.
