### ISSUE TITLE
Repeated entries for "number:Solax_grid_export_limit" changes in Logbook 

### ISSUE THREAD

**Issue by pickeringar** [wills106/homeassistant-solax-modbus#689]
### Describe the bug

Multiple entries in logbook (which need not be there?) with potential repeated & unnecessary writes to Inverter

![Logbook (Grid Export Limit)](https://github.com/wills106/homeassistant-solax-modbus/assets/110126980/b0cf2155-4398-4051-bb49-c3803ab64375)

### Integration Version

2024.01.2

### Homeassistant core version

2024.1.2

### Inverter brand

Solax X1-Hybrid-G3

### Plugin used

plugin_solax.py

### Serial prefix

H1E5

### Inverter firmware versions

not known

### Connection Method

Modbus over Ethernet into Ethernet port on inverter

### Dongle firmware

WiFi 2 

### Additional context

Still have Solax API running whilst I change over to modbus

**Comment by wills106** [comment]
It's not the Integration writing to the Inverter, but the Inverter letting you know what the Inverter is doing.
It's basically a duplicate of sensor.solax_inverter_power

If you don't want to use [button.solax_grid_export](https://homeassistant-solax-modbus.readthedocs.io/en/latest/solax-G23-operation-modes/#grid-export-gen-3-only) you could just disable it.

**Comment by pickeringar** [comment]
Having tried to follow this, I now relaise how much there is in this INtegration, for which I thank you

**Comment by wills106** [comment]
If you want to export the details are [here](https://homeassistant-solax-modbus.readthedocs.io/en/latest/solax-G23-operation-modes/#grid-export-gen-3-only)

I have a basic [automation example](https://github.com/wills106/homeassistant-solax-modbus/discussions/110#discussioncomment-7738020)

**Comment by pickeringar** [comment]
Will work my way through those documents again having read them last night. 

In the interim I have added "number.solax_grid_export_limit" to the exclusions for "recorder" in the "configuration.yaml" file to stop the entreis in the Logbook
