### ISSUE TITLE
[Bug]: cant Change values on q cells inverter

### ISSUE THREAD

**Issue by HubsiKU** [wills106/homeassistant-solax-modbus#690]
### Describe the bug

Hello,
I worked with the solax modbus integration well. But actual i cant cange soc or so on. I cant press unlock inverter and the dropdown state ist unlocked or unlocked - advanced. What can i do?

### Integration Version

Newest

### Homeassistant core version

2024.1.2

### Inverter brand

Qcells

### Plugin used

plugin_solax.py

### Serial prefix

Srkclr

### Inverter firmware versions

?

### Connection Method

Wifi dongle

### Dongle firmware

?

**Comment by wills106** [comment]
The button's were removed a couple of release ago as they are duplicated in the drop down now.

Is the lock state showing as Locked? If so change the drop down to Unlocked.

**Comment by HubsiKU** [comment]
Hey, the dropdown is also on unlocked - advanced

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wills106** [comment]
So when you try and move the slider on the Battery SOC is just reverts back?

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/18155231/8b7718da-42a4-4a98-942f-6b22e20cd4f0)

**Comment by HubsiKU** [comment]
Exaxtly

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wills106** [comment]
Were you trying to change the entity when the Inverter was [idle](https://homeassistant-solax-modbus.readthedocs.io/en/latest/faq/#unable-to-control-inverter-when-pv-0-battery-soc-is-at-minimum)?

**Comment by wills106** [comment]
Closing down as no further response.
This might be the issue [FAQ](https://homeassistant-solax-modbus.readthedocs.io/en/latest/faq/#unable-to-control-inverter-when-pv-0-battery-soc-is-at-minimum)
