### ISSUE TITLE
[Bug]: After update to 2024.01.4 all Solis entities show as unavailable

### ISSUE THREAD

**Issue by J14111** [wills106/homeassistant-solax-modbus#693]
### Describe the bug

Just a heads up, I don't have much time to troubleshoot but going from 2024.01.3 to 2024.01.4 all my entities for the Solis in HA show as unavailable going back to 2024.01.3 gets it working again, I have tried it twice so there is something breaking in that update

### Integration Version

2024.01.4

### Homeassistant core version

2023.12.4

### Inverter brand

Solis

### Plugin used

plugin_solis.py

### Serial prefix

?

### Connection Method

TCP/IP Adapter

**Comment by wills106** [comment]
Does it give any error in the Log or just `unrecognized XYZ inverter type - serial number : unknown`

**Comment by wills106** [comment]
Just released [2024.01.5](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.01.5) It was trying to define a Bitmask that doesn't exist.

**Comment by J14111** [comment]
Great thanks seems to be all ok now.

**Comment by J14111** [comment]
Love the new calculated string wattage BTW thanks so much :)
