### ISSUE TITLE
[Bug]: Run mode : Normal (R) - will not appear

### ISSUE THREAD

**Issue by matomatusov** [wills106/homeassistant-solax-modbus#699]
Hi,
I don't know why I don't see run mode - normal (R)
Modbus Power Control (remotecontrol power) - activated

![normal_R](https://github.com/wills106/homeassistant-solax-modbus/assets/129114957/9e8d8b92-1def-4592-bca7-f3714a7db2d8)

![DSC_0501](https://github.com/wills106/homeassistant-solax-modbus/assets/129114957/9e358114-f049-4e01-b0a6-6d9c8eaaeeb9)

Thanks

### Integration Version

2024.01.6

### Homeassistant core version

2024.1.3

### Inverter brand

SolaX power

### Plugin used

plugin_solax.py

### Serial prefix

H34A10

### Inverter firmware versions

ARM: 1.35 DSP: 1.36

### Connection Method

Waveshare adapter

### Dongle firmware

3.010.16

**Comment by wills106** [comment]
If you remove the Brackets () so you just have "Normal R"

https://github.com/wills106/homeassistant-solax-modbus/blob/bf9df3ecef2a60db1e64a69f43f4aa56086836be/custom_components/solax_modbus/plugin_solax.py#L3620

Does it display?

**Comment by matomatusov** [comment]
I removed the () and it's the same.
I have Normal mode.

![normal_R_2](https://github.com/wills106/homeassistant-solax-modbus/assets/129114957/fefb2423-bab9-42df-84b4-042b15d9c22f)

**Comment by wills106** [comment]
You are possibly on an older Firmware version then. Where the Modbus side doesn't distinguish between Normal Mode and Normal Mode (R)

Normal Mode (R) isn't in any of the know docs yet.

**Comment by wills106** [comment]
I'm going to close this down as it isn't an issue with the Integration.

The Integration can only report what the Inverter is telling it.

**Comment by matomatusov** [comment]
think fimware ARM, DSP?
It is current.

**Comment by wills106** [comment]
Yes it looks like your Inverter is on the latest?
Perhaps "Normal Mode (R)" got added by mistake and then removed again?

It's hard to know as it's not documented and there are no proper release notes.

**Comment by matomatusov** [comment]
I understand that the check log is not much.
Thank you for the effort and the info.
