### ISSUE TITLE
[Bug]: Battery Minimum Capacity not applied 

### ISSUE THREAD

**Issue by Matz88** [wills106/homeassistant-solax-modbus#703]
### Describe the bug

With an HYD6000 (sofar but rebranded) whenever I try to set the Battery Minimum Capacity or  Battery Minimum Capacity OffGrid, the setting is not applied, and the previous value reverted back in few seconds.
I see no specific errors in the log, do you know if some button need to pressed in order to save the value like for reflux?

### Integration Version

 2024.01.7

### Homeassistant core version

2024.1.2

### Inverter brand

Sofar

### Plugin used

plugin_growatt.py

### Serial prefix

ZM2ES0

### Connection Method

Lan adapter

**Comment by kai-seipp** [comment]
This hier might be related:
Setting the value of "Battery Minimum SOC" also can be set remotely. Once set via UI, it will jump back to the previous setting once the inverters values are read again via modbus.

BUT:
Setting "Force Charge SOC" actually works.
These are the two values you can set within a solis inverter on battery management, so I believe there is a good chance the first one can be set as well.

Both values are on Solis Inverters.

**Comment by cschlipf** [comment]
That's right. This is not working as this is one of the examples, where Sofar requires a lot of registers to be written at once. Obviously it never worked.

However when looking at it I found out that in order just to set the depth of discharge we have to set 23(!) registers containing all the battery parameters. And a lot of these battery parameters are mission critical. Setting one of these parameters to the wrong value can be harmful.

See the documentation here:
<img width="2003" alt="image" src="https://github.com/wills106/homeassistant-solax-modbus/assets/894150/09ee494d-d740-4b01-baf3-5cf4706118e5">

Register we want to change are 0x104D and 0x104E. I intend to work on this issue in stages: Stage 1: Read all the parameters and get a good feeling on how reliably these are read. However given the criticality of these parameters I have a very bad feeling about this and I would rather propose to remove both parameters from the integration.

What is your use case that you want to achieve by changing these values? Maybe we can find another solution?

**Comment by Matz88** [comment]
I see the point.

Was to decrease the DoD in winter to not leave the battery with a low state of charge when there are several days of bad weather. I tried also to limit the discharge staying in passive mode, but this has the drawback that in case the grid has a glitch, the inverter resets and as effect I have a small gap in the house power supply, few sec but enough to power cycle some devices that should not.

**Comment by cschlipf** [comment]
@kai-seipp - this defect is about Sofar. Please don't mix up other brands.

**Comment by cschlipf** [comment]
I know this is not what you are hoping for, but the PR will remove these non-functional controls for now. Closing it as it is very unlikely that these controls will be added back

**Comment by cschlipf** [comment]
Yes, I added that and tested it with my inverter. However I have an HYD 10 KTL-3PH.

**Comment by cschlipf** [comment]
@Matz88 with PR #799 we can start reading the battery parameters that are required in order to set depth of discharge, end of discharge, and EPS buffer.

Once released please activate the entities starting with "BatConfig:" and send me a screenshot of the values. This will be very useful in evaluating whether a write operation ever can be implemented successfully. On my inverter it doesn't look good unfortunately :(

**Comment by Matz88** [comment]
Sorry I was not able to take time for this before, I cannot see any batconfig in the diagnostic, have been they already removed?

**Comment by cschlipf** [comment]
@Matz88 - the values are hidden by default and need to be enabled.

**Comment by Matz88** [comment]
For me too the battery type is wrong:
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/6189282/53b3ed4b-4d0b-454d-b51d-a39f6f7ddd5f)
rest seems ok, settings are ok

**Comment by cschlipf** [comment]
> For me too the battery type is wrong: ![image](https://private-user-images.githubusercontent.com/6189282/314603188-53b3ed4b-4d0b-454d-b51d-a39f6f7ddd5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDI3MzMsIm5iZiI6MTcxMTAwMjQzMywicGF0aCI6Ii82MTg5MjgyLzMxNDYwMzE4OC01M2IzZWQ0Yi00ZDBiLTQ1NGQtYjUxZC1hMzlmNmY3ZGRkNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMDYyNzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTA4ZWU0YWI4ZGJmMDAwNjM3MzljN2I0ODNiMWFiNzI3MDQ2OTZmYTRjMWE5ZjE0ZDZlMjI1MDA2YWM0YjcwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1OxkAbUX6r_5wpOMmOUfsEna-bpDyg4xRPVVUO8rOtQ) rest seems ok, settings are ok

Thank you. Your protocol is also wrong.
