### ISSUE TITLE
[Bug]: MODxxKTL3-XH missing Charge / Discharge Power

### ISSUE THREAD

**Issue by iobrokerneu** [wills106/homeassistant-solax-modbus#718]
### Describe the bug

Hello, first of all I wanted to thank you for your work. I use your software in the Home Assistant and I have a question or it may be a bug. I use a Growatt Mod 5000TL3-XH with an ARK HV battery. Unfortunately, no data from the battery is displayed in your software. I miss the charge in %, discharge and charge in w. Am I doing something wrong or doesn't it exist yet? Unfortunately I didn't know any other way to ask. Thanks and greetings Sascha

### Integration Version

2024.01.8

### Homeassistant core version

2024.1.5

### Inverter brand

Growatt

### Plugin used

plugin_growatt.py

### Serial prefix

JDM0DB

### Connection Method

USR TCP232-410S

**Comment by iobrokerneu** [comment]
Hello again. Attached is a screenshot of an entity. This is always at 0 or is not updated. Greetings Sascha
![Growatt](https://github.com/wills106/homeassistant-solax-modbus/assets/55629670/0bde8d33-4452-4244-ac7a-acc5a1fef479)

sensor.growattmodbus_battery_combined_power

**Comment by wills106** [comment]
Just released [2024.02.5b8](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.02.5b8) does it fix missing"Battery Charge Power" & "Battery Discharge Power" and the combined one?

**Comment by iobrokerneu** [comment]
Hello, there are now more entities, but unfortunately no data is displayed. Greetings Sascha
![Uploading IMG_7347.png…]()

**Comment by iobrokerneu** [comment]
![IMG_7347](https://github.com/wills106/homeassistant-solax-modbus/assets/55629670/d510d2ea-20a5-4d3a-b3ff-638a222bf751)

**Comment by iobrokerneu** [comment]
![IMG_7348](https://github.com/wills106/homeassistant-solax-modbus/assets/55629670/3ad91bde-e862-4c16-8f0d-4dc761e561d5)

**Comment by wills106** [comment]
I have removed those extra entities that return zero and I have move the battery sensors to a different register set in [2024.02.5b9](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.02.5b9) to see if they work.

**Comment by iobrokerneu** [comment]
Hello, the data is now displayed. Thank you for your work!!!

Entity:
growattmodbus battery charge power when charging the battery

Entity: growattmodbus battery discharge power when discharging.

Entity: growattmodbus battery combinend power is also displayed when loading and unloading.

Greetings Sascha
![IMG_7358](https://github.com/wills106/homeassistant-solax-modbus/assets/55629670/759e7fc5-676d-451c-a423-077e48968225)
![IMG_7357](https://github.com/wills106/homeassistant-solax-modbus/assets/55629670/398db044-0038-4961-8813-f4742e203164)

**Comment by iobrokerneu** [comment]
Hello, the data is now displayed. Thank you for your work!!!

Entity:
growattmodbus battery charge power when charging the battery

Entity: growattmodbus battery discharge power when discharging.

Entity: growattmodbus battery combinend power is also displayed when loading and unloading.

Greetings Sascha
![IMG_7359](https://github.com/wills106/homeassistant-solax-modbus/assets/55629670/e2986df1-75d8-4e9c-8080-0e705f7f9cbb)
![IMG_7360](https://github.com/wills106/homeassistant-solax-modbus/assets/55629670/7bac563c-0929-434b-a162-c01491a585b3)

**Comment by wills106** [comment]
Glad it's working.
Can this be closed down now?
