### ISSUE TITLE
[Bug]: Dry Contact Mode

### ISSUE THREAD

**Issue by DLindi** [wills106/homeassistant-solax-modbus#719]
### Describe the bug

The entity "Dry Contact Mode" belongs not to the group sensors, but to switches with values: Loadmanagement and Generator Control.
Loadmanagerment contains: deactivate, Manual Mode(on/off) und SmartSave(....).
Generator Control has no further sub entities.
Dry contact mode is important to control heat pumps for example.

### Integration Version

2024.01.8

### Homeassistant core version

2024.1.6

### Inverter brand

SolaX Power

### Plugin used

plugin_solax.py

### Serial prefix

H34A10

### Inverter firmware versions

ARM 2.03, DSP 2.07

### Connection Method

Solax Pocket Wifi 3.0

### Dongle firmware

Pocket_WIFI_V3.010.16

**Comment by ernst10** [comment]
Hi Wills106,
I´m reading throug all infos about your Solax addin for HA. Great work many thanks.
I also would like to have access to dry contact information if the contact for starting a heat pump for example has been done. I con´t find any info about this. I can set in the App from Solax a specific value when dry contact will be issued and also when it will be reverted. But can´t find any related info in your addin. I only could find an entry about adapter box but this does tell me nothing what it ill do.
Would be nice to get some feedback on this.
many thanks

**Comment by wills106** [comment]
> The entity "Dry Contact Mode" belongs not to the group sensors, but to switches with values: Loadmanagement and Generator Control.

There is the select element and the feedback sensor. I forgot to add the DCB flag to the sensor. Are you not able to see the select?

ernst10 did you select the Dry Contact Box option when setting up the Inverter?

**Comment by ernst10** [comment]
Hi Wills106
Set inverter is setup with dry contact option and i can set loadmanagement with the handy app. Also i can see Dry contact mode set to loadmanagement inside HA. But i can´t get any information about the status of dry contact. So if it is closed and HeatPump has been started for example or open and HP has been stopped. This info would be great to have as it will tell how often PV has more power than used by house. For me i´m switching on and off an elektrical heater in the buffer of my heating system to bring the water to a higher temerature. so there are some option Dry contact could be used and status info would give additional info.

**Comment by wills106** [comment]
I don't think there are any feedback sensors. I can't find anything that looks like they could be.

**Comment by ernst10** [comment]
Many thanks for your feedback. So i will go another way to get this info. I will try to setup a second relais which i will connect in parallel to the already present Dry contact relais. This relais will be connected to a GPIO pin of a WEMOS mini ant then sent via MQTT to HA.
Hope this will work as expected. The WEMOS is alrady reading the energy data from the main grid meter by SML and Tasmota. So it will get an additional job to do.
Many thanks Ernst10

**Comment by wills106** [comment]
Closing down as no further response in past couple of months.

Feel free to reopen if needed.
