### ISSUE TITLE
missinentity x1 gen3 

### ISSUE THREAD

**Issue by motclem** [wills106/homeassistant-solax-modbus#72]
if I look at the entities list for the solax modbus  integration there does not seem to be an entity for pv power as there was in devious versions.

**Comment by motclem** [comment]
<img width="865" alt="Screenshot 2022-05-06 at 17 13 12" src="https://user-images.githubusercontent.com/83984333/167171679-5dcddb5c-74ce-4233-b0eb-897ae85947a8.png">

**Comment by wills106** [comment]
@motclem I'm assuming from your post here https://github.com/wills106/homsassistant-solax-modbus/discussions/26#discussioncomment-2255645 you are using an Inverter that has a serial number starting H1E5?

**Comment by wills106** [comment]
Looks like you have a different Gen3 X1 then.

What's your Charge / Discharge current - as indicated on the Inverter LCD or Cloud, not in the Integration?

I am just about to add another Inverter so I can add your's in as well.

**Comment by motclem** [comment]
trying to confirm the s/n but have locked myself out of my solax cloud account! can I find it on the device itself do you know?

**Comment by wills106** [comment]
Yea I think it's Advance - Battery - Charger on the LCD, off the top of my head.

It will probably only allow you to go upto 20 or maybe 25A

**Comment by motclem** [comment]
20 for both I think

**Comment by wills106** [comment]
I have just released 0.5.5 which should work for your Inverter.

**Comment by motclem** [comment]
@wills106 you're a legend :)
<img width="304" alt="Screenshot 2022-05-06 at 17 59 51" src="https://user-images.githubusercontent.com/83984333/167178793-888141d2-e505-42cf-8c8b-97ceb71f25ee.png">

<img width="865"

**Comment by wills106** [comment]
Closing this issue down as I believe the Integration is working correctly for you.
If there are any further issues please raise a new Issue.
