### ISSUE TITLE
[Bug]: Data from some sensors resetting at 2358 and a few seconds to zero e.g. sensor.solax_today_s_solar_energy

### ISSUE THREAD

**Issue by UK-JustinSmall** [wills106/homeassistant-solax-modbus#724]
### Describe the bug

I seem to have a issue with some data resetting values to zero at a fraction before 00:00:00 hours resulting in last value being reported for the day as zero. e.g. for daily solar generation sensor.solax_today_s_solar_energy I get zero values in my chart all throughout January.

![solax 1 hour error](https://github.com/wills106/homeassistant-solax-modbus/assets/129121587/d96a1654-8977-46a9-9fc3-f21d361da629)
![2024-02-07_00-45-20](https://github.com/wills106/homeassistant-solax-modbus/assets/129121587/8289f8b8-9116-45d1-8bbd-c2c4e1449fa9)
![Snag_1bd701a](https://github.com/wills106/homeassistant-solax-modbus/assets/129121587/a74925ea-ddff-4113-87f9-071d88e651dc)

Date is correct timezone on ubuntu server and on the inverter

### Integration Version

2023.12.1

### Homeassistant core version

20231208.2

### Inverter brand

Solax

### Plugin used

plugin_solax.py

### Serial prefix

H4752A

### Inverter firmware versions

3.001.02

### Connection Method

Waveshare Adapter

### Dongle firmware

12.01

**Comment by UK-JustinSmall** [comment]
Appears some entities are updating at a 23:58 and a few seconds each night and resetting the values at that time to zero. So then the history is then showing the value at 00:00:00 any chance this could be set so that the time these entities update are a few seconds after midnight so it captures the value for end of day in my apex charts.

type: picture-elements
image: /local/solar/card-medium-03.png
elements:
  - type: custom:tabbed-card
    style:
      top: 25%
      left: 50%
      width: 97%
      height: 50%
    tabs:
      - attributes:
          label: Daily
        card:
          type: custom:apexcharts-card
          experimental:
            brush: true
          brush:
            selection_span: 30d
          graph_span: 180d
          span:
            end: day
          header:
            show: true
            title: ''
            floating: false
            show_states: false
            colorize_states: true
            standard_format: true
          apex_config:
            chart:
              height: 380px
          all_series_config:
            type: column
            stroke_width: 1
            show:
              legend_value: false
            statistics:
              type: state
              period: day
              align: end
          yaxis:
            - min: 0
              max: 60
              decimals: 0
          series:
            - entity: sensor.solax_today_s_solar_energy
              name: Solar Total
              color: rgb(249,191,0)
              offset: +1d
              show:
                in_brush: true
          card_mod:
            style: |
              ha-card {
                background-color: rgba(0,0,0,0);
                border: none;          
              }
card_mod:
  style: |
    ha-card {
      background-color: rgba(0,0,0,0.5
      );
      border: none;
    }

**Comment by UK-JustinSmall** [comment]
![2024-02-07_00-45-20](https://github.com/wills106/homeassistant-solax-modbus/assets/129121587/ac61aaed-7724-42eb-8260-9a6a01c85203)
![Snag_1a63f46](https://github.com/wills106/homeassistant-solax-modbus/assets/129121587/ad56ee8e-598f-495b-b488-0c03248848dd)

**Comment by wills106** [comment]
The zeroing of the graphs is handled by Home Assistant.

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/18155231/59b5fdfc-adec-479a-85d5-d4d40b0eb632)

Are you sure your Inverter is synced time wise? It looks like it's drifted out by 1m 10s

**Comment by wills106** [comment]
Closing down as no response.
