### ISSUE TITLE
[Bug]: Integration doesn't work correctly with multiple Inverters

### ISSUE THREAD

**Issue by RSX2613** [wills106/homeassistant-solax-modbus#729]
### Describe the bug

Hello, I operate 3 Solax inverters: 1 x X3 Hybrid and 2 x X1 mini.
I can add these and everything works fine. But after restarting HA, out of 2 inverters the entity is no longer available? How could I fix this problem?

### Integration Version

2024.01.1

### Homeassistant core version

2024.2.0

### Inverter brand

Solax 

### Plugin used

plugin_solax.py

### Serial prefix

H34B08

### Inverter firmware versions

ARM 2.03 DSP 2.07

### Connection Method

3 x Solax WiFi 3.0 

### Dongle firmware

3.001.02

**Comment by wills106** [comment]
The Integration hasn't been tested a whole lot with multiple Inverters.
The main multi inverter setup I know had two identical Inverters.

I have exposed the Serial Number in the Device Info section with [2024.02.3b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.02.3b1) does that help the Integration to differentiate between the Inverters correctly?

If it doesn't correct the Inverters following a restart of HA you might need to remove all 3 Instances of the Integration, restart HA and add them back in.

**Comment by RSX2613** [comment]
> If it doesn't correct the Inverters following a restart of HA you might need to remove all 3 Instances of the Integration, restart HA and add them back in.
Yes, this is the only way to get all three inverters working again at the same time. But of course after restarting HA the whole thing has to be repeated. However, this is not a really usable method for users with more than one inverter!

**Comment by wills106** [comment]
I meant to get them working again after trying out [2024.02.3b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.02.3b1) then hopefully they'll carry on working correctly and survive restarts etc.

**Comment by RSX2613** [comment]
Oh my mistake, I'll test it!

**Comment by RSX2613** [comment]
Can you tell me how I can Install the Beta Version?

**Comment by wills106** [comment]
Did you use HACS? You can redownload it and select the Beta options.
Then select 2024.02.3b1 from the list.

https://hacs.xyz/docs/faq/select_version

**Comment by RSX2613** [comment]
Ahh I find it. Thank You!

**Comment by wills106** [comment]
If the Beta is installed correctly each Inverter should display it's serial, under Device info.
Hopefully that will allow HA to know which Inverter is which correctly.

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/18155231/cb3bff4c-84d3-463b-9060-e18cabb98a12)

**Comment by RSX2613** [comment]
I tried it today and all three inverters are working. The serial numbers are also displayed correctly.
But unfortunately only 2 of 4 strings are displayed correctly. As either PV1 and PV2 from the Solax X3 or twice PV 1 from my 2 Solax X1 mini.

**Comment by wills106** [comment]
Could you try [2024.02.3b2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.02.3b2) I have added the serial number into device_info identifiers.
Hopefully this will allow HA to keep all of the Inverter entities separate from each other.

**Comment by RSX2613** [comment]
I tested versions 2024.02.3b2 and 2024.02.3b3.
But unfortunately the X3 inverter doesn't work after restarting HomeAssitant.
Most entities of the X3 are not available after restarting HA.
The two X1s run without problems.

![Ohne Titel 2](https://github.com/wills106/homeassistant-solax-modbus/assets/155590346/c834bd96-8c29-4f73-9b33-f85978111c35)

**Comment by wills106** [comment]
> ### Dongle firmware
> 3.001.02

Are you sure all 3 are on that version? As it's over 3 years old now.

You can check by following the [FAQ](https://homeassistant-solax-modbus.readthedocs.io/en/latest/solax-faq/)
The Internal code is the Firmware Version, the one that say Firmware always reads 3.001.02

I'm just wondering if the Pocket WiFi on the X3 is earlier than the X1's and that's what's causing you to keep loosing it. As early Firmwares on the PocketWiFi weren't stable.

**Comment by wills106** [comment]
If you add them in a different order do you lose the first type on Inverter added on restart?

1st X3 then the two X1 = Losing the X3 on restart
1st X1, X1 and then X3 = Losing the X1's on restart

**Comment by RSX2613** [comment]
No it is not working in a different order.
And all three working on Firmware version 3.001.02.
But I made a mistake on the X3 is a Wifi Dongle V2 workin (the white on) and on the X1 Wifi Dongle V3.

**Comment by wills106** [comment]
If you use a PocketWiFi 3.0 on the X3 does it survive a restart and you start getting issues with which ever X1 that then has the PocketWiFi2?

**Comment by wills106** [comment]
If you are still getting the same issue where the Hybrid fails try [2024.02.4b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.02.4b1) I have merged the two SensorEntityDescription's into a single one.

Other than that I'm not sure what else to try as I only have a single Inverter to test on.

**Comment by RSX2613** [comment]
Now I can install only version 2024.02.3.
I test it tomorrow!
I noticed that when I switched off the two X1s (no more sun) the X3 worked again?

**Comment by wills106** [comment]
I'm thinking https://github.com/wills106/homeassistant-solax-modbus/blob/a558ca3999ec6518d09e2cae932400e1f05003d7/custom_components/solax_modbus/plugin_solax.py#L6526 is stopping your Hybrid from working, while it can read a "MIC" Your X1 Mini's use the same registers as MIC.

Which I have removed in 2024.02.4b1 and merged them into one.

Let me know how you get on tomorrow.

**Comment by RSX2613** [comment]
In the new version the X3 works but the X1 no longer works at all. In addition, when adding inverters, they are always added twice.
![1](https://github.com/wills106/homeassistant-solax-modbus/assets/155590346/8ece6f93-e388-4ba3-a7fb-ff087d9fb6db)
![2](https://github.com/wills106/homeassistant-solax-modbus/assets/155590346/2281d489-cb0f-4046-903a-930f4abe64d1)
![3](https://github.com/wills106/homeassistant-solax-modbus/assets/155590346/2519d7dd-ab7d-4035-8935-31d76df6785b)

**Comment by wills106** [comment]
The two devices per Inverter was fixed in 2024.02.5 Beta branch [2024.02.5b2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.02.5b2) I forgot to mention it.

**Comment by RSX2613** [comment]
I updated to the latest version and added everything new.
The X3 is running but X1 is added but no data is read out. In addition, they now have 77 entities.
When they were still functioning there were 25 entities

![4](https://github.com/wills106/homeassistant-solax-modbus/assets/155590346/459d103a-4123-4b5a-ad1b-47456913596c)

**Comment by RSX2613** [comment]
Yes

**Comment by wills106** [comment]
Are you able to add the following to your configuration.yaml
```
logger:
  default: info
```
Then in the logs search for solax and "Load Full Logs"
Then download the file and then send it to me. I want to see how it's trying to configure itself.
You can hide any personal info like serials. But leave enough that I can tell which of the 3 Inverters is which.

**Comment by RSX2613** [comment]
[home-assistant_2024-02-13T18-01-56.612Z.log](https://github.com/wills106/homeassistant-solax-modbus/files/14270549/home-assistant_2024-02-13T18-01-56.612Z.log)

**Comment by wills106** [comment]
Are your two X1's actually in Run mode or have they both gone to sleep now? Due to lack of Solar PV?

**Comment by RSX2613** [comment]
sleep now

**Comment by wills106** [comment]
That'll be why they won't work at the moment then.

Can you try again tomorrow and send me the log of them trying to communicate.

**Comment by RSX2613** [comment]
When Im back from work I will send you a new log.

**Comment by wills106** [comment]
I have released [2024.02.5b3](https://github.com/wills106/homeassistant-solax-modbus/tree/2024.02.5b3) I think a number of the 77 entities for each X1 is picking up AC/Hybrid registers. I have been over the AC/Hybrid list and properly assigned them.

I think there are only about 30 or 30 registers for the X1 PV Inverters.

**Comment by RSX2613** [comment]
Unfortunately I can't try out the version 2024.02.5b3 because it isn't available for selection in HA.
Otherwise everything is like yesterday, I attached the log file.

[home-assistant_2024-02-14T14-45-51.139Z.log](https://github.com/wills106/homeassistant-solax-modbus/files/14281116/home-assistant_2024-02-14T14-45-51.139Z.log)

**Comment by wills106** [comment]
Not sure what was up with 2024.02.5b3? I have just pushed the same out as 2024.02.5b4 which shows up.

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/18155231/0804e912-765a-44df-8f89-d09b0d584c8d)

**Comment by wills106** [comment]
It looks like I was correct and it's trying to mix Hybrid and PV only registers together.
2024.02.5b4 should get rid of that issue.

**Comment by RSX2613** [comment]
Now it works!
A big thank you.
Hopefully it will still work when I put an X3 Mic into operation soon.

![5](https://github.com/wills106/homeassistant-solax-modbus/assets/155590346/e5df8719-815b-4951-a5c7-97172fd98daf)

**Comment by wills106** [comment]
Did you manage to test with all 3 Inverters?

**Comment by RSX2613** [comment]
a short feedback on the current status.
The X3 runs very well, the X1 with 78 entities also runs wonderfully.
Only the X1 with 27 entities has to be added again and again so that it runs again.
I had to add this again after the last update and therefore only has 27 entities, which is probably leading to the problems.
![6](https://github.com/wills106/homeassistant-solax-modbus/assets/155590346/a4000a1b-9860-4765-8919-778a626e0a9f)

**Comment by wills106** [comment]
I don't think they are setup correctly.
The X1 Mini's shouldn't have 78 entities. 27 Sounds correct.

Personally I would remove all 3 Inverters. Restart and add them back in. Then you know for sure they are all using the corrected code. You still have 2024.02.5b3 code loaded on one of the X1's

**Comment by RSX2613** [comment]
All inverters added again.
And again problems with the one X1, first it freezes and the data stops and after restarting it is not available.

[home-assistant_2024-02-17T08-29-06.219Z.log](https://github.com/wills106/homeassistant-solax-modbus/files/14318196/home-assistant_2024-02-17T08-29-06.219Z.log)

**Comment by wills106** [comment]
Is that log after restarting HA with the 3 Inverters connected?

**Comment by wills106** [comment]
Is IP .84 the Garage Inverter?

**Comment by RSX2613** [comment]
Yes IP.84 is the Garage Inverter.

**Comment by RSX2613** [comment]
log after restarting HA.

[home-assistant_2024-02-17T14-27-32.983Z.log](https://github.com/wills106/homeassistant-solax-modbus/files/14319135/home-assistant_2024-02-17T14-27-32.983Z.log)

**Comment by wills106** [comment]
From what I can see multiple Inverters are working together ok on the latest Beta releases #743 the only difference I can see if the use of Waveshare's on the X1's but I wouldn't expect that to make a difference?

**Comment by RSX2613** [comment]
I've tried several times in the last few days but always have the same problem.

![6](https://github.com/wills106/homeassistant-solax-modbus/assets/155590346/f1d101e3-4792-452d-bdf0-d1220e4088a0)
![7](https://github.com/wills106/homeassistant-solax-modbus/assets/155590346/5feb6f98-7af7-4671-8c3b-317f4e2cfa88)
[home-assistant_2024-02-20T11-38-32.131Z.log](https://github.com/wills106/homeassistant-solax-modbus/files/14343710/home-assistant_2024-02-20T11-38-32.131Z.log)

**Comment by wills106** [comment]
Did you get all Inverters working? Can this be closed now, as other users have managed to get multiple SolaX Inverters working together.

**Comment by RSX2613** [comment]
Yes all works good. Can be closed.
