### ISSUE TITLE
[Bug]:  After the update, the inverter was split into two items

### ISSUE THREAD

**Issue by vitjurasek** [wills106/homeassistant-solax-modbus#742]
### Describe the bug

After a normal update within Home Assistant, a new version of MODBUS integration for Solax G4 was installed. Originally one instance of the inverter has split into two. The original one is working. The other is completely dead, but cannot be deleted.
After a reboot of HA it now takes several minutes, sometimes tens of minutes, to establish communication with the inverter.

![bug1](https://github.com/wills106/homeassistant-solax-modbus/assets/145932919/95c7169c-a09c-478e-80f2-1b630c9d15c5)
![bug2](https://github.com/wills106/homeassistant-solax-modbus/assets/145932919/2993d86c-ff49-4238-a74b-dc0e10b33b0c)

### Integration Version

2024.02.4

### Homeassistant core version

2024.2.1

### Inverter brand

SolaX Power G4

### Plugin used

plugin_solax.py

### Serial prefix

H34A10

### Inverter firmware versions

-

### Connection Method

Solax pocket wifi

### Dongle firmware

-

**Comment by wills106** [comment]
This was introduced in 2024.02.3 and corrected in 2024.02.4
If it hasn't corrected it's self press the 3 dots to delete it. Then add it back in again.

If you name it the same all the history will still be there.

**Comment by matomatusov** [comment]
Hi, I have a similar problem.
It also appeared to me when I updated to 2024.02.4.

**Comment by matomatusov** [comment]
@wills106 your delete and add procedure didn't help.

**Comment by wills106** [comment]
I just downgraded and it is indeed still there.

[2024.02.5b4](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.02.5b4) is working fine.
You will possibly need to delete and read it. As 2024.2.5 is changing the way multiple Inverters are handled.

**Comment by matomatusov** [comment]
@wills106
solax shadow fix function level split into 2 entities?

SolaX Shadow Fix Function Level PV1 (GMPPT)
SolaX Shadow Fix Function Level PV2 (GMPPT)


"You will possibly need to delete and read it."
I do not understand the meaning to read?

Thanks

**Comment by wills106** [comment]
> solax shadow fix function level split into 2 entities?
> 
> SolaX Shadow Fix Function Level PV1 (GMPPT) SolaX Shadow Fix Function Level PV2 (GMPPT)

That got added in with #599 and released in [2024.01.3](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.01.3)

> "You will possibly need to delete and read it." I do not understand the meaning to read?

It's a typo should be "readd" (to add again)

> If it hasn't corrected itself press the 3 dots to delete it. Then add it back in again.
> 
> If you name it the same all the history will still be there.

**Comment by vitjurasek** [comment]
> > solax shadow fix function level split into 2 entities?
> > SolaX Shadow Fix Function Level PV1 (GMPPT) SolaX Shadow Fix Function Level PV2 (GMPPT)
> 
> That got added in with #599 and released in [2024.01.3](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.01.3)
> 
> > "You will possibly need to delete and read it." I do not understand the meaning to read?
> 
> It's a typo should be "readd" (to add again)
> 
> > If it hasn't corrected itself press the 3 dots to delete it. Then add it back in again.
> > If you name it the same all the history will still be there.

Not work for me.

**Comment by Stepsilein** [comment]
No way, ist a terrible bug still.
I used all posdible versions, even beta ...2.5b.
But the Fake inverter still dhown (but dead as always)
I stopped and deleted the integration, HA restart snd installed the 2024.2.2 (last bugfree working version) again.
Now clean 1 inverter dhown working nicd as before.

I will definitily wait for a future bugfree version... or never ever update to that buggy ones.
Keep on the good work, but try to workbout that bug please.
🙋🏼‍♂️

**Comment by wills106** [comment]
You can go from 2024.02.2 to 2024.02.5b4 without an issue.

Although if you own an SolaX Air, Boost, Mini or MIC / MIC Pro you will possibly need to delete and readd the Inverter, as part of the change for correctly supporting multiple Inverter installations.

**Comment by cschlipf** [comment]
I have the same problem with a Sofar Inverter after updating today.

Device 1 shows most of the sensors and some controls
<img width="1030" alt="image" src="https://github.com/wills106/homeassistant-solax-modbus/assets/894150/5c5a6936-23f6-4413-b6df-b6403b8e809a">

Device 2 shows options:
<img width="1021" alt="image" src="https://github.com/wills106/homeassistant-solax-modbus/assets/894150/074db8be-e3df-4a1d-96d1-867f88c4ba8c">

**Comment by wills106** [comment]
Either go back to 2024.02.2 or use 2024.02.5b4

> If it hasn't corrected it's self press the 3 dots to delete it. Then add it back in again.
> 
> If you name it the same all the history will still be there.

You may need to do the above.

**Comment by wills106** [comment]
2024.02.3 and 2024.02.4 have been deleted from the Releases page.

**Comment by wills106** [comment]
Hopefully 2023.02.5b4 will be pushed out soon as a full release and fix for #729 which will benefit anyone with multiple Inverter installs.
I appreciate it's a pain at times when this Integration breaks, but it's difficult to test every scenario with only a single Inverter out of the vast many supported so far.

**Comment by cschlipf** [comment]
Totally understood. Thanks so much for your awesome work. Enjoy your Ko-Fi ;-)

**Comment by Stepsilein** [comment]
Thanks a lot for your work with this veeery helpful Integration 😍👍👍👍👍

**Comment by sahomm** [comment]
I observed the same issue, search about that and I read it's observed.

202!!!4!!!.02.5b4 tested, done! Grate job, well done! 👍

**Comment by wills106** [comment]
I'm closing this down as I have released [2024.02.5](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.02.5)
