### ISSUE TITLE
[FR]: Support Swatten Inverters

### ISSUE THREAD

**Issue by lgisler72** [wills106/homeassistant-solax-modbus#744]
### Describe the bug

Swatten : no devices or entities
[home-assistant_solax_modbus_2024-02-15T16-18-22.093Z.log](https://github.com/wills106/homeassistant-solax-modbus/files/14299520/home-assistant_solax_modbus_2024-02-15T16-18-22.093Z.log)

### Integration Version

2024.02.5b5

### Homeassistant core version

2024.2.1

### Inverter brand

Swatten

### Plugin used

plugin_growatt.py

### Serial prefix

S0067692380000910000 

### Connection Method

Waveshare RS485 to ETH

**Comment by wills106** [comment]
We could have carried on the discussion / development in the discussion page.
But I'll stick to using the issue going forward, then the conversation will be in one place.

Good news is that the Inverter is responding and I can tell if it's Single or 3Phase from what it returns. I was worried I would need to probe another register to workout if it was Single or 3Phase.

**Comment by wills106** [comment]
I have just released [2024.02.5b6](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.02.5b6) hopefully it will return a few entities now.

**Comment by lgisler72** [comment]
Now it is showing something; It returns : 1device, 19 entities.
Here is the log file: 
[home-assistant_solax_modbus_2024-02-15T20-55-09.131Z.log](https://github.com/wills106/homeassistant-solax-modbus/files/14302361/home-assistant_solax_modbus_2024-02-15T20-55-09.131Z.log)
Thank you.
(I will be away for 2 days but I'm looking forward to continuing the tests as soon as possible)

**Comment by wills106** [comment]
Can you take a screenshot of the values returned?

From the "error log" it's looking promising though!

**Comment by lgisler72** [comment]
Here you have
![Capture d’écran du 2024-02-15 22-16-50](https://github.com/wills106/homeassistant-solax-modbus/assets/153561364/abf27f26-2c1f-42c1-b8ff-b8c17328077d)
![Capture d’écran du 2024-02-15 22-18-36](https://github.com/wills106/homeassistant-solax-modbus/assets/153561364/7698a7be-6aec-4297-a860-44eefcaf6be7)

**Comment by wills106** [comment]
Ok further work is required on PV current, and PV Total.
Also "Phase" isn't returning what I hoped for. Luckily "Model Type" can be used to determine if the Inverter is Single or 3Phase.
So "Phase" can be removed.

Would be good to see a screenshot during the day when the PV is fully active.

**Comment by wills106** [comment]
I have just released [2024.02.5b7](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.02.5b7)
I have changed endianness on order32 to LITTLE so `PV Power Total` & `Total Output Power` should return better looking values.
RTC has been changed to an input register, to see if it returns the time (Don't use `Sync RTC` yet!)
Removed `Phase` as didn't provide what's expected and no longer required.

**Comment by wills106** [comment]
I just wanted to check a couple of registers were working correctly before adding the rest in with the previous docs.
Have you been able to check  `PV Power Total` & `Total Output Power` since I changed the endianness?

**Comment by wills106** [comment]
I have released [2024.02.5](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.02.5) containing more entities.
Could you let me know if they look ok or if any scaling needs changing?

**Comment by lgisler72** [comment]
I have solar panels for ~6 year and rcently had the oportuniti to buy the Swatten inverter and the battery. As the hibrid inverter is consuming ~120W permanently so I keep my solars panel on the SolarEdge inverter and do an automation to turn ON/OFF the Swatten inverter dependign of the Battery SOC and solar production. So PV voltage at 0V on the swatten is normal.
(Today it is raining; Heat-pump is running)
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/153561364/9c794ba5-e0c1-45c1-9996-d044469fd6df)
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/153561364/459272dd-0be5-4a40-baa1-07712aae0e8b)

**Comment by lgisler72** [comment]
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/153561364/66ec7b15-b4cb-4faa-9628-9687647c0014)

**Comment by wills106** [comment]
Do you think this can be closed down now? Or are they any missing sensors?
I know you can't test the PV side of things.

**Comment by lgisler72** [comment]
Hello, Yes you can close the case now. Thank you fro your work.
