### ISSUE TITLE
[Bug]: All entities and sensors disabled after update to 2024.02.6

### ISSUE THREAD

**Issue by md091979** [wills106/homeassistant-solax-modbus#773]
### Describe the bug

All entities and sensors disabled after update to 2024.02.6 , they are not more available

### Integration Version

2024.02.6

### Homeassistant core version

20242..3

### Inverter brand

Solax X3 Hybrid

### Plugin used

plugin_solax.py

### Serial prefix

H34A08

### Inverter firmware versions

-

### Connection Method

-

### Dongle firmware

-

### Detailed Error Log

-

### Additional context

-

**Comment by spetrie13** [comment]
Same for me with Solis inverter

**Comment by Alfred99-HA** [comment]
Same for me.
It seems that also Solax Cloud doesn't show values as a consequence

**Comment by the-sim87** [comment]
Same for me for Growatt inverter - reload of solax-modbus plugin helped for now.

**Comment by mc4wrk** [comment]
I have the same problem.
I had a integration for my X1-Hybrid-G4 using modbus and after update HA, all my sensors are gone and loose the connection to the USB dongle. I have made a rollback using the backup files and now I can't get any info from the integration. Any advice will be most welcome. Thanks
