### ISSUE TITLE
[Bug]: SolaX EPS Yield Total wrong value

### ISSUE THREAD

**Issue by LubikR** [wills106/homeassistant-solax-modbus#864]
### Describe the bug

SolaX EPS Yield Total has wrong value. I have 2 891 kWh in the Home Assistant but FVE is running only two month in EPS mode. In the Solax cloud page there is 288.60kWh. It seems that value from integration is ten times bigger than reality.

### Integration Version

2024.04.3

### Homeassistant core version

2024.4.1

### Inverter brand

X3-Hybrid-G4

### Plugin used

plugin_solax.py

### Serial prefix

H34A15

### Inverter firmware versions

1.38, 1.38

### Connection Method

LAN+Wifi dongle and also RS485

### Dongle firmware

1.002.09

**Comment by Clausimauz** [comment]
Same on my X3-Hybrid-G4, H34A08, Firmware 1.40 / 1.41,
In my Solax App, EPS Yield Total is shown 21 kWh in Homeasistant 215 kWh.
Looks like 10 times more.
Edit plugin_solax.py (line 4798) and add scale = 0.1 and rounding = 1 in this section
then EPS Yield Total value displays correct. 
    SolaXModbusSensorEntityDescription(
        name = "EPS Yield Total",
        key = "eps_yield_total",
        native_unit_of_measurement = UnitOfEnergy.KILO_WATT_HOUR,
        device_class = SensorDeviceClass.ENERGY,
        register = 0x8E,
        register_type = REG_INPUT,
        unit = REGISTER_U32,
        scale = 0.1,
        rounding = 1,
        allowedtypes = AC | HYBRID | GEN3 | GEN4 | GEN5 | EPS,
