### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wartungsmonteur** [wills106/homeassistant-solax-modbus#884]
### Describe the bug

seit Version 2024.05.2 sind viele Entitäten nicht mehr verfügbar, diese sind nur noch grau hinterlegt, siehe Screenshots

### Integration Version

2024.05.2

### Homeassistant core version

2024.5.1

### Inverter brand

Solax X3

### Plugin used

plugin_solax.py

### Serial prefix

H34C10

### Inverter firmware versions

2.03

### Connection Method

Modbus TCP

### Dongle firmware

waveshare TCP

**Comment by wartungsmonteur** [comment]
<img width="340" alt="Bildschirmfoto 2024-05-05 um 22 43 35" src="https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/953796d2-5093-4522-9ffd-d2c8f1e8f47b">
<img width="340" alt="Bildschirmfoto 2024-05-05 um 22 44 07" src="https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/a46a7c8c-95b9-46e3-9df4-43d11085015f">
<img width="340" alt="Bildschirmfoto 2024-05-05 um 22 44 36" src="https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/f4ebb3f3-ae68-4fe8-8d35-ec9811c797ea">
<img width="340" alt="Bildschirmfoto 2024-05-05 um 22 45 12" src="https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/1d8e9720-103f-48a5-9b88-11f5b0dec9db">
<img width="340" alt="Bildschirmfoto 2024-05-05 um 22 45 40" src="https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/0d7ac50e-2527-44ac-aa08-9d6c77023b08">

**Comment by wills106** [comment]
This looks to be a duplicate of #878

**Comment by wills106** [comment]
Closing down as duplicate.
