### ISSUE TITLE
X1-Hybrid-G3 e-charge today wrong value 

### ISSUE THREAD

**Issue by Claudio1L** [wills106/homeassistant-solax-modbus#89]
hi

the sensor "sensor.solax_e_charge_today" seems providing wrong value.

It shows about 80 kwh per day, when should be no more than 7-8 kwh

![immagine](https://user-images.githubusercontent.com/97904190/180636845-e658202b-6edc-410e-973e-dfc8de392216.png)

The total counter, instead, is reporting the correct increase for the same period

![immagine](https://user-images.githubusercontent.com/97904190/180636925-71a9aa02-0262-4750-9687-b0a86716bff8.png)

**Comment by Claudio1L** [comment]
comparing between the E_charge today and Battery input_energy today, it seems a scaling (10x) issue.

￼  ￼

**Comment by wills106** [comment]
I can't even remember what E Charge is meant to be for?

Just Turned mine back on as it's off by default. Does yours only increase when you grid charge? As mine is just sat at 0, but I haven't charged from the grid in months.

**Comment by Claudio1L** [comment]
E Charge should be the kWh provided to the battery inverter to charge the battery (AC side). Battery input Energy should be the same in DC, not including the lost efficiency of the inverter. Same thing for the Solax today Yield (AC side) vs Battery output energy (DC side)- That's my understanding and seems confirmed by the similar value and trends, with a small difference given by the inverter loss.

**Comment by Claudio1L** [comment]
It is also confirmed by the difference between the "e Charge total" vs the "e charge today". About 8 kwh variation in the total vs the 80 kwh in the today graph

**Comment by wills106** [comment]
Should be fixed in [0.5.10](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/0.5.10)

**Comment by wills106** [comment]
My E Charge only increases when I force charge from the Grid. It doesn't increase from any PV diverted power going into the battery.

So for the Energy dashboard I don't know how useful it is? Unless you are using it as a separate consumption device only.

**Comment by Claudio1L** [comment]
I see charge increase perhaps because I have different inverters for PV and Battery, so my charge will come always from "outside" regardless if PV or Grid

**Comment by Claudio1L** [comment]
seems ok with 0.5.11-Beta

**Comment by wills106** [comment]
Closing as release [0.5.11](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/0.5.11) fixes issue.
