### ISSUE TITLE
X1-Hybrid-G3 update to 0.5.9 broken entities

### ISSUE THREAD

**Issue by Claudio1L** [wills106/homeassistant-solax-modbus#90]
after update to 0.5.9 most of the entities went "unknown".  Rolling back to 0.5.8 fixed issue.

**Comment by wills106** [comment]
Have you tried the 0.5.9a Prerelease?

https://github.com/wills106/homeassistant-solax-modbus/releases/tag/0.5.9a-beta

Did you get any errors in the logs?

**Comment by wills106** [comment]
The new release [0.5.10](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/0.5.10) has the same fix as 0.5.9a if you were having the same issue as the Gen2's

**Comment by Claudio1L** [comment]
I'll check 0.5.10 and let you know

**Comment by Claudio1L** [comment]
same issue. Log:

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/solax_modbus/__init__.py:553
Integration: SolaX Inverter Modbus (documentation, issues)
First occurred: 07:43:07 (3 occurrences)
Last logged: 07:43:37

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/solax_modbus/__init__.py", line 224, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/config/custom_components/solax_modbus/__init__.py", line 281, in read_modbus_data
    return self.read_modbus_holding_registers_0() and self.read_modbus_holding_registers_1() and self.read_modbus_holding_registers_2() and self.read_modbus_input_registers_0() and self.read_modbus_input_registers_1() and self.read_modbus_input_registers_2()
  File "/config/custom_components/solax_modbus/__init__.py", line 553, in read_modbus_holding_registers_2
    inverter_model_number = decoder.decode_string(20).decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf4 in position 3: ordinal not in range(128)

**Comment by Claudio1L** [comment]
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/solax_modbus/sensor.py:93
Integration: SolaX Inverter Modbus (documentation, issues)
First occurred: 07:43:23 (1 occurrences)
Last logged: 07:43:23

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 762, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 388, in state
    value = self.native_value
  File "/config/custom_components/solax_modbus/sensor.py", line 93, in native_value
    self._hub.data[self.entity_description.key]*self._attr_scale
TypeError: unsupported operand type(s) for *: 'datetime.datetime' and 'int'

**Comment by wills106** [comment]
Have you manually installed or through HACS?

Also can you try removing the integration from the Integration page. Restarting HA and then try adding it again. Do you still get the same error?

**Comment by wills106** [comment]
Could you also share the first 4 digits of your Serial number so I know exactly which X1 Gen3 you have.

**Comment by Claudio1L** [comment]
Same thing.

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/solax_modbus/__init__.py:553
Integration: SolaX Inverter Modbus (documentation, issues)
First occurred: 08:32:14 (2 occurrences)
Last logged: 08:32:29

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/solax_modbus/__init__.py", line 224, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/config/custom_components/solax_modbus/__init__.py", line 281, in read_modbus_data
    return self.read_modbus_holding_registers_0() and self.read_modbus_holding_registers_1() and self.read_modbus_holding_registers_2() and self.read_modbus_input_registers_0() and self.read_modbus_input_registers_1() and self.read_modbus_input_registers_2()
  File "/config/custom_components/solax_modbus/__init__.py", line 553, in read_modbus_holding_registers_2
    inverter_model_number = decoder.decode_string(20).decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf4 in position 3: ordinal not in range(128)

**Comment by wills106** [comment]
Your inverter is missing 1 or 2 registers. Can you share your first 4 digits of your Serial number so I filter out your Inverter

**Comment by Claudio1L** [comment]
sure: XRE372BB14xxxx

**Comment by wills106** [comment]
Can you please try 0.5.11-Beta. Before upgrading remove the Integration from the Integration page. Update and restart and then add it back in.

**Comment by Claudio1L** [comment]
looks working now, only few sensors disappeared. Asap will let you know wich one are missing

**Comment by wills106** [comment]
You are missing the two that don't exist on yours.

Battery Install Capacity
Inverter Model Number

Or you are at least missing - Inverter Model Number as that's what it was failing on.

**Comment by Claudio1L** [comment]
yes correct, 

Battery Install Capacity
Inverter Model Number

so, it seems fine now

**Comment by wills106** [comment]
Closing as release [0.5.11](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/0.5.11) fixes issue.
