### ISSUE TITLE
[Bug]: 'Solax' - 'G4 X1 Hybrid' A number of sensors are showing as unavailable and have error related to blocking call

### ISSUE THREAD

**Issue by UK-JustinSmall** [wills106/homeassistant-solax-modbus#900]
### Describe the bug

Log Details (WARNING)
Logger: homeassistant.util.loop
Source: util/loop.py:99
First occurred: 10:35:19 (1 occurrences)
Last logged: 10:35:19

Detected blocking call to import_module inside the event loop by custom integration 'solax_modbus' at custom_components/solax_modbus/__init__.py, line 142: plugin = importlib.import_module( (offender: /config/custom_components/solax_modbus/__init__.py, line 142: plugin = importlib.import_module(), please create a bug report at https://github.com/wills106/homsassistant-solax-modbus/issues

Additionally following entities have become unavailable after upgrading past 2024.04.2 so cannot upgrade past this version number

![0bc3b262-4187-4e09-a4d2-87167872f1c2](https://github.com/wills106/homeassistant-solax-modbus/assets/129121587/64cd80ad-b215-4122-9f66-f5a3720d061e)

### Integration Version

2024.04.2

### Homeassistant core version

2024.5.4

### Inverter brand

Solax

### Plugin used

plugin_growatt.py

### Serial prefix

SOLAX

### Connection Method

Waveshare

### Detailed Error Log

2024-05-18 10:35:19.139 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module inside the event loop by custom integration 'solax_modbus' at custom_components/solax_modbus/__init__.py, line 142: plugin = importlib.import_module( (offender: /config/custom_components/solax_modbus/__init__.py, line 142: plugin = importlib.import_module(), please create a bug report at https://github.com/wills106/homsassistant-solax-modbus/issues

### Additional context

No additional text

**Comment by wills106** [comment]
Missing entities is documented #878 
Blocking call #876

**Comment by UK-JustinSmall** [comment]
Thanks but it is these internal sensors that are being referenced in jinga2 code thus breaking our application. Can you please reconsider and add these entities back in please.
