### ISSUE TITLE
[Question]: Does someone know how to configure this inverter so that it works with a Growatt inverter

### ISSUE THREAD

**Issue by Sicos1977** [wills106/homeassistant-solax-modbus#903]
### Describe the bug

This is not a bug but a question ... but could not find a place to ask this.

I know that the standard Waveshare RS485 to ethernet module does not work but I have this one --> https://www.waveshare.com/RS232-485-TO-ETH.htm

It supports modbus_tcp 

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/6692947/00bdc974-f0c2-4435-8ba6-99ba848a1f0a)

I configured SolaxX modbus integration in HA as follow.

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/6692947/88bc8bad-87db-409c-8539-e2cabdc1b004)

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/6692947/207333e3-8aab-4829-8765-6cee50384a72)

I see that it starts initalizing...

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/6692947/0f23c8d4-7a3a-4e53-8707-e2e20f152eb0)

And I see in the waveshare module that data is received...

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/6692947/ae8e0ec8-e71a-41ba-86e0-2b6a6fddfab8)

But nothing comes back...

I check the wiring between the waveshare module and my Growatt MOD 6000TL3-X inverter... I don't have any 120 Ohm resistors on both sides.. I can't find any documentation anywhere if this is needed in this situaties... I'm a noob when it comes to modbus.

### Integration Version

2024.05.3

### Homeassistant core version

2024.5.4

### Inverter brand

Growatt MOD 6000TL3-X

### Plugin used

plugin_growatt.py

### Serial prefix

2024.5.4

### Connection Method

RS232-485-TO-ETH WaveShare

### Additional context

.

**Comment by 001Tycoon** [comment]
Hello, I have a USR-W610
My settings
USR-W610
Work Mode TCP Transparent (None)

SolaxX modbus
ModBus RTU over TCP

I hope it helps

**Comment by wills106** [comment]
Closing down as not an issue. Please use the discussions as mentioned.
