### ISSUE TITLE
[Bug]: firmware sensors missing

### ISSUE THREAD

**Issue by pchaves1** [wills106/homeassistant-solax-modbus#909]
### Describe the bug

firmware sensors are not available anymore!?

### Integration Version

2024.05.5

### Homeassistant core version

2024.5.4

### Inverter brand

Solax Power

### Plugin used

plugin_solax.py

### Serial prefix

H4752

### Inverter firmware versions

DSP v1.36 ARM v1.39

### Connection Method

Waveshare

### Dongle firmware

could not find

**Comment by pchaves1** [comment]
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/45390982/3e992c29-5c51-493d-a320-70d1433160ba)

**Comment by wills106** [comment]
Aren't they displayed in the "Device info" panel as per [2024.05.4](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.05.4)?

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/18155231/0babad37-da34-4e51-b484-a27f5aeb7aeb)

**Comment by pchaves1** [comment]
on "Device info" panel, yes.
Were the sensors removed? 
If yes, is there a way to create a sensor just with the firmware, like the one existing on the panel?

**Comment by wills106** [comment]
Sensors are removed as per the release notes. The "Device info" gets updated when reloading the Integration and HA.

I'm trying to reduce the amount of registers constantly being polled.

Do you really need to check them that often?

**Comment by pchaves1** [comment]
I see, so it's not a bug then. My bad.
I was using it to check when a request firmware upgrade was completed (on the history), but that's ok, I will start checking it on the panel.

**Comment by wills106** [comment]
Device info has live sensors in [2024.07.0b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.07.0b1)
