### ISSUE TITLE
[Bug]: House Load with 2nd energy source (inverter) on Meter2

### ISSUE THREAD

**Issue by t3lmoazevedo** [wills106/homeassistant-solax-modbus#910]
### Describe the bug

The House Load value needs a fix when a second inverter is connect to Meter 2 and injecting also in the house.

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/41584793/e63e4660-609c-49af-9e1f-9734fde7fce3)

```
323 W (PV Power Total) + 307 W (Meter 2 Measured Power) - 68 W (Grid Export) - 36 W (Battery Power Charge)
= 
526 W (House Load)... and is showing 203 W

```
Close datetime screenshot from the setup and current values:

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/41584793/63882b24-187c-453c-a7b4-adf88f8cd027)

### Integration Version

2024.05.5

### Homeassistant core version

2024.5.4

### Inverter brand

Solax X1 gen 3 hybrid

### Plugin used

plugin_solax.py

### Serial prefix

 H1E502

### Inverter firmware versions

Not available

### Connection Method

LAN

### Dongle firmware

LAN

**Comment by wills106** [comment]
Just released [2024.05.6b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.05.6b1) can you let me know if the 'House Load' looks correct now?

**Comment by t3lmoazevedo** [comment]
Hi @wills106, its perfect now! Thanks you very much for this great project ;)

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/41584793/79f57990-93a9-47c7-b952-9091afa531af)

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/41584793/07d62b2b-c41d-4bb8-ba46-892614bef5d6)

**Comment by wills106** [comment]
Ok thanks, Just released it as a normal version then.
No difference to the beta, so no need to update again.
