### ISSUE TITLE
[Bug]: Multiple Solax Inverters

### ISSUE THREAD

**Issue by Bl00d-B0b** [wills106/homeassistant-solax-modbus#934]
### Describe the bug

Hello,
I use several SolaS Inverters (G2 & G4) and EV charger via Modbus, As I can see, when You add multiple inverters, they report wrong information:

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/23188529/14e9b92b-140c-4677-b064-6060d393c77a)

My solax 8K type is X3-MIC-8K-G2, when I add it alone, then information is correct, but when I add two inverters both shows last added model and firmware inforamtion:

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/23188529/69075dbe-dfcd-4a21-b9f9-ec20810fa38c)
and 
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/23188529/4a70acde-0eb2-4378-af02-2fe5347a75d0)

EV Charger is showing unknow !!!

### Integration Version

2024.6.3

### Homeassistant core version

2024.6.3

### Inverter brand

SolaX

### Plugin used

plugin_solax.py

### Serial prefix

MC208T for MIK-8K

### Inverter firmware versions

latest

### Connection Method

Pocket Wifi 3.0 to 8K, and modbus to 15K

### Dongle firmware

latest

**Comment by wills106** [comment]
This should be corrected in [2024.07.0b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.07.0b1)

**Comment by wills106** [comment]
Did you check one of the latest Beta's such as [2024.07.0b4](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.07.0b4)

**Comment by wills106** [comment]
Closing down as released [2024.08.1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.08.1)
