### ISSUE TITLE
[Bug]: changeless value 'SolaX Battery Charge Max Current'

### ISSUE THREAD

**Issue by t3lmoazevedo** [wills106/homeassistant-solax-modbus#942]
### Describe the bug

The register for 'SolaX Battery Charge Max Current' can't be changed now, returning always for the value manually changed on the remote settings app.
Everything else changes correctly, and the inverter is on 'Unlocked' state, just not this value anymore.

![x1](https://github.com/wills106/homeassistant-solax-modbus/assets/41584793/31acc82f-a65b-4b2e-ae07-610fecbbf617)

Thanks for all the suport, and I hope its not something else related, and I could be missing it.

### Integration Version

2024.05.7

### Homeassistant core version

2024.6.4

### Inverter brand

Solax X1 gen 3 hybrid

### Plugin used

plugin_solax.py

### Serial prefix

 H1E502

### Inverter firmware versions

Not available

### Connection Method

LAN

### Dongle firmware

LAN

**Comment by t3lmoazevedo** [comment]
Found a usage pattern for the problem.
When the value is changed, it returns to the original one, and then jumps automaticly to the new value, exact 5 minutos after.

Example: it was 13.6A, I select 7A, and it gets back to 13.6A. After 5 minutes goes to the request 7A.
Tested several times, same behaviour with the 5 minutes interval.

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/41584793/f06a6544-34f8-4161-ba0f-5f7150d36839)

**Comment by wills106** [comment]
Mine exactly the same on DSP v3.32 ARM v3.28
Never noticed before as I don't alter it.

I'm guessing it's a quirk of the Inverter?

**Comment by t3lmoazevedo** [comment]
It was working perfectly in sync for the last 3 years, like the other registers also.
(I charge the batteries with cheap energy at a low amperage during the night, to use the next rainy day with low solar)
Maybe collateral efect from an inverter firmware update :(

**Comment by wills106** [comment]
If it was an Integration issue I would expect Battery Discharge to function the same as they work in the same manner.

Did you know there is another way to limit import / export.

https://homeassistant-solax-modbus.readthedocs.io/en/latest/solax-G23-operation-modes/#grid-export-gen-3-only

If you use a positive value you can charge that way as well. Say 2000w

Is there a reason you want to limit charging from the grid? Do you get charged more if you import above a certain value?

**Comment by t3lmoazevedo** [comment]
I will try the export procedure with a positive value. Thanks for the tip.

In the last years, and having only 3.4 kW power contract from the grid, I set the inverter Charge Use Mode 'Force Time Use' during the night to use the grid to charge the battery with a limited power, since I also need more power for the home consuption that includes charging an electric vehicle.
It's also useful to use cheap tariff during the night to use that energy during the rainy days (with high price tariff).

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/41584793/13b5471a-107d-4bff-9fa7-0f0aec56b6c2)

**Comment by wills106** [comment]
Closing down as not an Integration issue.
