### ISSUE TITLE
[Bug]: Logbook of EVC Integration is logging the Time

### ISSUE THREAD

**Issue by Philipp-X1** [wills106/homeassistant-solax-modbus#950]
### Describe the bug

I am getting a Logbook entry every 10 seconds about the RTC. ( 10 sec is my reading intervall of the integration )
So every 10 seconds it Logs the Date and Time.
I dont know if this behavior is wanted, but the Inverter Integration doesnt do this at all.

Just wondering if this logging can be removed?

### Integration Version

newest

### Homeassistant core version

newest

### Inverter brand

Solax X3-EVC-11K

### Plugin used

plugin_solax_ev_charger.py

### Serial prefix

N/A

### Inverter firmware versions

1.13

### Connection Method

Waveshare RS485 to ETH

### Dongle firmware

-

### Detailed Error Log

As mentioned here https://github.com/wills106/homeassistant-solax-modbus/issues/805 @PatrikTrestik asked me to open up a new Issue.
Would be grateful if you can take a look into it :)

**Comment by wills106** [comment]
RTC is normally disabled by default. Have you enabled it then?

**Comment by Philipp-X1** [comment]
Actually i dont know. Is there a difference between the Inverter and the EV Charger?

I dont see any possibility to enable or disable it.

I only got this control button:

![Screenshot 2024-07-03 154818](https://github.com/wills106/homeassistant-solax-modbus/assets/146736973/7735855a-92e0-466c-b4e5-baae57dd5a4c)


![Screenshot 2024-07-03 154838](https://github.com/wills106/homeassistant-solax-modbus/assets/146736973/02c3cda6-ba0f-4f52-b6e3-d72060397cd5)

**Comment by wills106** [comment]
It should be disabled by default.

Click the sensor so the box pops up
Click the Gear (Settings)
Then toggle "Enabled" so it's turned off.

**Comment by Philipp-X1** [comment]
Thank you! 
Yes, I did enable it back then.
Wasn’t even thinking about this…

Disabled it now and it isn’t logging anymore, thanks.
