### ISSUE TITLE
[Bug]: Platform solax_modbus does not generate unique IDs

### ISSUE THREAD

**Issue by jamespreedy** [wills106/homeassistant-solax-modbus#975]
### Describe the bug

Log (error) on HASS startup.

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:764
integration: Sensor (documentation, issues)
First occurred: 4:51:23 PM (2 occurrences)
Last logged: 4:55:23 PM

Platform solax_modbus does not generate unique IDs. ID SolaX_inverter_frequency is already used by sensor.solax_inverter_frequency - ignoring sensor.SolaX_inverter_frequency

### Integration Version

2024.8.1

### Homeassistant core version

2024.7.4

### Inverter brand

SolaX

### Plugin used

plugin_solax.py

### Serial prefix

H34A10

### Inverter firmware versions

n/a

### Connection Method

PocketLAN 3.0, Waveshare Modbus

### Dongle firmware

n/a

### Detailed Error Log

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:764
integration: Sensor (documentation, issues)
First occurred: 4:51:23 PM (2 occurrences)
Last logged: 4:55:23 PM

Platform solax_modbus does not generate unique IDs. ID SolaX_inverter_frequency is already used by sensor.solax_inverter_frequency - ignoring sensor.SolaX_inverter_frequency

**Comment by wills106** [comment]
Corrected this in [2024.08.2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.08.2)
