### ISSUE TITLE
[Bug]: 'SolaX' - 'Gen3' crash on add integration "KeyError: 'support-battery'"

### ISSUE THREAD

**Issue by MrRickwi** [wills106/homeassistant-solax-modbus#976]
### Describe the bug

Same like Growatt bug. Reported here to have different label on it. Additionally, some entities are missing after getting the integration up and running with a hack. See also other reported bug.

### Integration Version

2024.08.02

### Homeassistant core version

2024.7.4

### Inverter brand

SolaX Gen3

### Plugin used

plugin_solax.py

### Serial prefix

H34C06

### Inverter firmware versions

DSP v1.29 ARM v1.31

### Connection Method

USB Modbus Adapter

### Dongle firmware

None

**Comment by MrRickwi** [comment]
Latest version is working for me. Missing entities have been found, are disabled by default.

**Comment by wills106** [comment]
I'll close this down then.

**Comment by ruimmsimoes** [comment]
I’m having the same issue when adding a SolaX inverter after upgrading to 2024.08.08

**Comment by wills106** [comment]
Just released [2024.09.3](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.09.3) which hopefully fixes this error.
